### PR TITLE
fix: fix a bad exception in DJPP

### PR DESCRIPTION
**Pull request by monperrus**
fix bad exception in DJPP after heavy transformation, no way to reproduce in a test case.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
This PR looks like a workaround of some deeper problem. So I would say it is not good idea to merge it.

It looks like that heavy transformation produced an inconsistent spoon model, where an element (parent) has some children, but these children doesn't point back to that parent. Their parent is uninitialized.

May be 
1) run a spoon model consistency check
2) found which element is invalid and which code made it
3) fix the spoon code which allows producing such inconsistencies

WDYT?

**Comment by monperrus** [comment]
The transformation code was working very well with previous versions of Spoon, so it can be considered as a regression. As for all regressions, I prefer to fix it in Spoon's core and not in the client code.

It's a semi-workaround, the alternative fix would be to identify the intercession method that did not set the parent, but I cannot find it.

This PR fixes the regression.

**Comment by pvojtechovsky** [comment]
this PR is fixing secondary problem.

>  to identify the intercession method that did not set the parent,

that would be fix of the primary problem

**Comment by monperrus** [comment]
agree, hope we'll find the primary problem at some point!

(actually, I'm surprised because we have a strong test on whether setters set the parent)

**Comment by pvojtechovsky** [comment]
> unless getStatements() returns a super-list similar to those you have in the role part.

yes, that would make sense.
In future I would like to refactor whole Spoon model by way all the multivalue properties are read/write and automatically binds new items with parent and sends change events - like "in the role part"

**Comment by monperrus** [comment]
agree, see https://github.com/INRIA/spoon/issues/1916

**Pull request merged**
