### PR TITLE
Set Type arguments in reference

### PR DESCRIPTION
**Pull request by diorcety**
The reference doesn't copy the CtMethod ActualTypeArguments

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Can you add a test case for this PR? 

Thanks in advance!

**Comment by monperrus** [comment]
Hi @diorcety,

Thanks for the proposal. However, we don't fully see your problem.

getActualTypeArguments() almost never returns the formal type parameters.

Let's consider the following example:
```
public  <E> List<E> get() {...}

class Foo<F> {
main() {
  <F>get();
  <String>get(); 
}
```

for `<F>get();` getActualTypeArguments() returns [F]
for `<String>get();` getActualTypeArguments() returns [String]

I don't see yet a reason to have a default link between  formal type parameters and actual type arguments.

what's your initial problem?

**Comment by diorcety** [comment]
The test show my issue. From a ExecutableReference i can't get any information about TypeArguments (formal in this case). Maybe the fix is not good, but there is a lack about the reference provided data

**Comment by monperrus** [comment]
So what you want is `execRef.getDeclaration().getFormalTypeParameters()`?

this one should contain 'E'.

**Comment by diorcety** [comment]
Oh yes maybe. I didn't use this code anymore. Sorry

**Pull request closed without merging**
