### PR TITLE
fix getFile() for serialization

### PR DESCRIPTION
**Pull request by Egor18**
Hi! I found out that filename from `SourcePosition` is lost during serialization (it's null). Although line number, column, etc. are present in deserialized model.
This happens because `getFile()` uses `compilationUnit`, which is null in deserialized model.
I fixed that by introducing field '`file`' in `SourcePosition`.
Also, I provided some tests. Particularly, without this fix the following assertions fail:
```
assertTrue(type.getPosition().getFile().equals(typeFromFile.getPosition().getFile()));
....
assertTrue(elem1.getPosition().getFile().equals(elem2.getPosition().getFile()));
```

Really want this fix, because without it we can't get any filename from SourcePosition from deserialized model.

### CODE REVIEW

**Comment by monperrus** [comment]
OK for me.

**Comment by pvojtechovsky** [comment]
OK for me too

**Comment by surli** [comment]
Hi @Egor18 thanks for the fix! Could you just add a contract in comment of the test, then I'll merge the PR?

**Comment by Egor18** [comment]
Thanks!

**Pull request merged**
