### PR TITLE
review: fix(control-flow): Process constructor call in control flow graph

### PR DESCRIPTION
**Pull request by Mr-Pine**
Currently, a standalone constructor call doesn't appear in the control flow graph. With this PR it is processed like any other statement

### CODE REVIEW

**Review by MartinWitt — APPROVED** [review]
LGTM will merge

**Comment by MartinWitt** [comment]
@Mr-Pine there is a conflict.

**Comment by Mr-Pine** [comment]
Is resolved not @MartinWitt

**Comment by I-Al-Istannen** [comment]
@MartinWitt :sparkles: ping :sparkles:

**Pull request merged**
