### PR TITLE
fix part of serialization problem

### PR DESCRIPTION
**Pull request by pvojtechovsky**
After this PR is applied the #955 will pass the tests.

### CODE REVIEW

**Comment by monperrus** [comment]
wy do you say "part of" in the title? it looks like a complete fix for #955

**Comment by pvojtechovsky** [comment]
It is complete fix for #955 if it is merged together with #955. This PR without #955 will not solve the origin serialization problem.

**Comment by monperrus** [comment]
OK. @tdurieux can merge your fix in his PR.

**Comment by monperrus** [comment]
thanks a lot for the fix!

**Pull request closed without merging**
