### PR TITLE
feat: add new variable refactoring class

### PR DESCRIPTION
**Pull request by basedrhys**
Simply takes out the main functions of the local variable refactoring class and changes the type to be a generic CtVariable. Useful for research purposes.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot! In Spoon we aim at having at least one test case per feature. Would you add a test case to specify the behavior? Thanks :-)

**Comment by basedrhys** [comment]
I've added a test and an extra little comment on the main class, hopefully it covers what you're after. Thanks :)

**Comment by monperrus** [comment]
Great, thanks a lot for your swift response and excellent test.

Now we need:

1. to make CI happy :smile: 
1. to add one sentence in the documentation about this cool new refactoring.

Thanks!

**Comment by basedrhys** [comment]
I've made those changes :)

The build is failing due to invalid URLs in the docs: I've put a link to where the new generic renaming class _will_ be once the changes are pushed, but at the moment it's technically an invalid URL. Do you want to leave the URLs to the new files out of the docs until these changes are merged or are you happy to press on?

**Comment by monperrus** [comment]
Really nice. LGTM to merge. Thanks a lot for your contribution.

**Comment by monperrus** [comment]
Thanks a lot for your contribution!

**Pull request merged**
