### PR TITLE
feature: CtRole#getSubRole(Object)

### PR DESCRIPTION
**Pull request by pvojtechovsky**
It is often needed to detect type of sub role. So CtRole can do it now.

### CODE REVIEW

**Comment by monperrus** [comment]
I agree with the general idea, this will be powerful.

I'm not sure about the API. Some questions to make progress:

* what is `CtElement#getRoleInParent()` expected to do? returning the least specific (eg TYPE_MEMBER) or the most specific role (eg METHOD)? (we should clarify the Javadoc)
* can it happen that there are several sub roles?
* what about naming it `getMostSpecificRole()`?

**Comment by monperrus** [comment]
OK, thanks for the explanation.

>what about naming it getMostSpecificRole()?

>>Is it still needed if we have only one level of sub roles?

Super explicit names are always better :)

>  Could you make a PR with such comment?

It would be great and meaningful to integrate this comment change in this PR.

What about to make getSubRole() static? (`CtRole.TYPE_MEMBER.getSubRole(null);` is not good because the receiver is never used.)

**Comment by pvojtechovsky** [comment]
>> what about naming it getMostSpecificRole()?

>Super explicit names are always better :)

note that there already exists `CtRole#getSubRoles()`, which returns all possible sub roles of main role. The new method name `getSubRole(Object)` matches with existing method ...
WDYT? Will we rename also `getSubRoles` to `getMostSpecificRoles` ? ... and deprecate old name?

**Comment by monperrus** [comment]
Yes, we should have a unified API.

Currently, the API is spread over two classes:

* `CtElement#getRoleInParent()`
* `CtRole#getSubRoles()`
* `CtRole#getSuperRole()`

For the new one, instead of putting it in CtRole, I would propose to put it in CtElement: `CtElement#getRoleInParentSpecific()`.

The we could write `el.getRoleInParentSpecific()` as well as `el.getRoleInParentSpecific().getSuperRole()`

WDYT?

**Comment by monperrus** [comment]
> * `CtRole#getSubRoles(Object)` works on unassigned CtElement too. And note that this method is used before the element is assigned to parent and before it becomes part of it's children.

It seems to me that we at least need a parent. Do you mean that getSubRole works when you have the parent, but the object is not yet in the children?

**Comment by pvojtechovsky** [comment]
> It seems to me that we at least need a parent. 

no, parent is useless for getSubRole. Or I did not understood your idea.

**Comment by monperrus** [comment]
Now, I understand, did a small refactoring (name + type).

OK for you?

**Comment by pvojtechovsky** [comment]
It is OK for me and ready for merge.

**Pull request merged**
