### PR TITLE
chore: Remove slarse as integrator

### PR DESCRIPTION
**Pull request by slarse**
Hello everyone!

It's been years since I made any meaningful contribution to Spoon. I've been meaning to get back into it for the longest time, but it's time to face the fact that it's simply not going to happen. Given my other interests, I just can't make the time for it anymore.

So, this is making my resignation as an integrator official. I should have handed it in a long time ago, but it's simply going to have to be a "better late than never" kind of PR :)

Best of luck!

Ps. Don't forget to remove my write privileges to the repository!

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]
Hej!

Thank you for your work on spoon. I wish you all the best! I assume @monperrus needs to take care of any permissions.

**Comment by I-Al-Istannen** [comment]
Thank you, Slarse! We sadly never managed to meet up while I was there, but I am thankful for the time you put into reviewing random stuff I made, it improved the results considerably :^)

I hope you won't be axe murdered in the future and wish you all the best! Enjoy your free and quality time — as well as other projects — with one less thing nagging you in the back of your mind :)

**Comment by MartinWitt** [comment]
Hey,

Thanks @slarse, for your contributions. I had the pleasure of meeting you in person. I also saw you changed your job, good luck with your new position. Furthermore, I will handle the permission update.

**Review by MartinWitt — APPROVED** [review]

**Comment by slarse** [comment]
Thanks, everyone. Officially being relieved of duty is a bit of a weight off my shoulders :)

@SirYwell Everything is fair game, I have no plans to resume work on Spoon anytime soon.

@I-Al-Istannen I've actually almost never been axe murdered, so the trends seem favorable!

@MartinWitt Yeah, I've been bouncing around a bit trying different things :). Thanks!

**Pull request merged**
