### PR TITLE
review chore: Add a script to update pom.xml for running pit-descartes

### PR DESCRIPTION
**Pull request by surli**
This script intends to be used only in jenkins CI to update pom.xml before running pit-descartes as the plugin is not yet released.

### CODE REVIEW

**Comment by monperrus** [comment]
could we host this experimental stuff in Jenkins or Gakoci directly?

**Comment by surli** [comment]
The script is now available in http://spoon.gforge.inria.fr/jenkins/pit-descartes/

**Comment by surli** [comment]
I made a mistake: the code of http://spoon.gforge.inria.fr/jenkins/ is replaced by doc/jenkins automatically at each deployment. 
I propose then to move the content of this PR inside doc/jenkins/spit-descartes: + it guarantees to keep a version of those files in the repo.

**Comment by surli** [comment]
The job is now running and working.

**Comment by monperrus** [comment]
thanks!

**Pull request merged**
