### PR TITLE
chore: Upgrade to org.eclipse.jdt:org.eclipse.jdt.core:3.12.3

### PR DESCRIPTION
**Pull request by pvojtechovsky**
This JDT is newer and has published sources in maven repository, so it is easier to debug...

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
looks like it is compiled with JDK 1.8 :-( so not for Spoon ... yet ...

**Comment by surli** [comment]
We can ignore the status of the non-working CI check for this one. 
However I wonder if we could upgrade to the **org.eclipse.jdt:org.eclipse.jdt.core:3.12.3** released in march or to **org.eclipse.tycho:org.eclipse.jdt.core:jar:3.13.0.v20170516-1929** released in june?
See https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core vs https://mvnrepository.com/artifact/org.eclipse.tycho/org.eclipse.jdt.core

**Comment by monperrus** [comment]
I'm fine with both of them.

**Comment by pvojtechovsky** [comment]
I personally agree with everything what has accessible sources, so it is easier to debug problems or to understand how it works. So newer is better

**Pull request merged**
