### PR TITLE
review: fix: Simplify code using Map.computeIfAbsent

### PR DESCRIPTION
**Pull request by lyxell**
This pull request fixes [1 violation](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&open=AWtJlStabu-R5OS58r29&resolved=false&rules=java%3AS3824&types=CODE_SMELL) of [Sonar rule S3824](https://rules.sonarsource.com/java/RSPEC-3824) ("Map.get" and value test should be replaced with a single method call).

This patch was generated automatically using [Logifix](https://github.com/lyxell/logifix).

### CODE REVIEW

**Review by slarse — APPROVED** [review]
LGTM, will merge after 24-hour wait period

**Comment by algomaster99** [comment]
> merge after 24-hour wait period

I have seen that you have commented the quoted line in many PRs. Is there some logic behind this? Or do you just wait for others to chime in with their reviews?

**Comment by slarse** [comment]
@lyxell Thanks for the contribution!

@algomaster99 See the [contributing guidelines](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md#the-integrator-code-of-conduct)

**Comment by slarse** [comment]
@lyxell Ooops, I made a mistake in merging this: it should be labeled `refactor` rather than `fix`, as it doesn't change any functionality. It's the integrator's responsibility to check that he correct label is used, but just as an FYI for future PRs, `fix` is for bugfixes, `refactor` for refactorings.

**Pull request merged**
