### PR TITLE
refactor: avoid throw in finally

### PR DESCRIPTION
**Pull request by monperrus**
Fixes https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&severities=CRITICAL&types=BUG

### CODE REVIEW

**Comment by tdurieux** [comment]
Are you aware that you are changing the behavior of the code?

**Comment by monperrus** [comment]
WDYT?

**Comment by nharrand** [comment]
Wouldn't that PR introduce a behavior where when `code.run();` throws an exception, the stack `sourceFragmentContextStack` is no longer cleared?
So if someone attempt to print a model, fails, and try to correct it, it will no longer be printable?

**Comment by tdurieux** [comment]
At least this PR changes that behavior. I m not sure what does core.run().

**Comment by monperrus** [comment]
Agree, maybe it's not worth breaking something to fix a Sonarqube rule.

**Pull request closed without merging**
