### PR TITLE
chore: Disable automatic Gradle Dashboard upload

### PR DESCRIPTION
**Pull request by slarse**
See #4269 for discussion

See [this part of the docs](https://docs.gradle.com/enterprise/maven-extension/#publishing_on_demand) for on-demand publishing.

### CODE REVIEW

**Comment by slarse** [comment]
@monperrus Regarding static analysis noise, is that :point_up:  going to show up on every PR now?

**Comment by monperrus** [comment]
No! See https://github.com/INRIA/spoon/pull/4928

**Review by I-Al-Istannen — COMMENTED** [review]
If I knew how the build scan should be used, I would be better able to tell whether skipping tests is a problem here. If this PR just wants to be a change to on-demand, it should probably edit the workflow file too.

If you don't think it's worthwhile that's fine with me too.

**Comment by I-Al-Istannen** [comment]
Dito. If I understood [their advertisement](https://blog.gradle.org/introducing-build-scans) correctly it is for helping maintainers debug why builds for clients (or themselves) are slow or failing. Instead of looking at your log you can look at their website version of the log and users can share (deep-)links to the reports. This might be easier than having users upload the full maven build log, which might even miss information. 

So far, I haven't really seen people complain that their *spoon build* is failing — they normally just use it.  
If no integrator has ever used it either (Current count: 4/6) then maybe just deleting it in the first place really is the better solution.

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
I merged this for now, and we can discuss the removal of the plugin in the issue where we already started it.

**Pull request merged**
