### PR TITLE
refactor: move resources to testclasses in filters

### PR DESCRIPTION
**Pull request by zielint0**
@surli 
@monperrus 
@pvojtechovsky 

To move a Foo class, I needed to change an interface Foo to IFoo. Is it ok?
I needed to change Foo from package access to public access. Is it ok?

I am ready to merge.

### CODE REVIEW

**Comment by zielint0** [comment]
@surli 
Why this check (pull_request-INRIA-spoon-newtestcheck — [INFO] BUILD FAILURE) complains about double Foo class?

```
[ERROR] /tmp/gakoci/src/test/java/spoon/test/filters/testclasses/Foo.java:[4,8] duplicate class: spoon.test.filters.testclasses.Foo
```

There is only 1 Foo.
What I am missing?

I don't this error compiling by IDE (IDEA), mvn compile.

**Comment by surli** [comment]
It looks ok to me. @pvojtechovsky @monperrus WDYT?

**Comment by pvojtechovsky** [comment]
ok for me

**Comment by zielint0** [comment]
@pvojtechovsky 
Ahoj, thank you for feedback!

**Comment by zielint0** [comment]
@surli 
I re-introduced this PR in https://github.com/INRIA/spoon/pull/2222
Hereby I close this one (cannot push to this branch anymore).

**Pull request closed without merging**
