### PR TITLE
REVIEW fix: fix crash with SpoonException in sniper mode

### LINKED ISSUE #3204: Bug: Cannot transform class that references inner type when using sniper mode
I get the following stacktrace when transforming:

```
Exception in thread "main" spoon.SpoonException: Inconsistent child fragment class spoon.support.reflect.reference.CtTypeReferenceImpl has unexpected parent class spoon.support.reflect.reference.CtTypeReferenceImpl
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:313)
	at spoon.support.sniper.internal.ElementSourceFragment.add(ElementSourceFragment.java:279)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:308)
	at spoon.support.sniper.internal.ElementSourceFragment.addChild(ElementSourceFragment.java:196)
	at spoon.support.sniper.internal.ElementSourceFragment.access$000(ElementSourceFragment.java:46)
	at spoon.support.sniper.internal.ElementSourceFragment$1.enter(ElementSourceFragment.java:155)
	at spoon.reflect.visitor.CtScanner.visitCtTypeReference(CtScanner.java:762)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.accept(CtTypeReferenceImpl.java:73)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:81)
	at spoon.reflect.visitor.CtScanner.visitCtTypeReference(CtScanner.java:765)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.accept(CtTypeReferenceImpl.java:73)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.visitCtLocalVariable(CtScanner.java:516)
	at spoon.support.reflect.code.CtLocalVariableImpl.accept(CtLocalVariableImpl.java:48)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:81)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:294)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:55)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:551)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:56)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:81)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:330)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:56)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:81)
	at spoon.reflect.visitor.EarlyTerminatingScanner.visitCtCompilationUnit(EarlyTerminatingScanner.java:158)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.accept(CtCompilationUnitImpl.java:406)
	at spoon.reflect.visitor.EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:143)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:119)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:165)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.support.sniper.internal.ElementSourceFragment.addTreeOfSourceFragmentsOfElement(ElementSourceFragment.java:179)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.getOriginalSourceFragment(CtCompilationUnitImpl.java:358)
	at spoon.support.modelobs.SourceFragmentCreator.onChange(SourceFragmentCreator.java:30)
	at spoon.support.modelobs.ChangeCollector$ChangeListener.onListAdd(ChangeCollector.java:177)
	at spoon.support.reflect.declaration.CtElementImpl.addComment(CtElementImpl.java:531)
	at -----.Main.main(Main.java:52)
```

Main:
```java
public class Main
{
  public static void main(String[] args)
  {
    Launcher launcher = new Launcher();
    Environment env = launcher.getEnvironment();
    Factory factory = launcher.getFactory();
    env.setLevel("info");
    env.setAutoImports(true);
    env.setPrettyPrinterCreator(() -> {return new SniperJavaPrettyPrinter(env);});

    launcher.addInputResource(Paths.get("C:/Workspaces/wsmaster-spoon-test/projects/spoon/src/main/java/test/TestInnerType.java").toString());

    env.reportProgressMessage("Building model");
    launcher.buildModel();

    CtModel model = launcher.getModel();
    CtClass ctClass = model.getElements(new TypeFilter<>(CtClass.class)).get(0);

    ctClass.addComment(factory.Code().createComment("test", CommentType.BLOCK));

    env.reportProgressMessage("Processing");
    launcher.process();
    env.reportProgressMessage("Writing");
    launcher.prettyprint();
  }
}
```

TestInnerType:

```java
package test;

import java.util.*;

public class TestInnerType
{
  private void test()
  {
    Map.Entry<String, String> test;
  }
}
```

When `Map.Entry` is replaced with `Entry` no stacktrace is given.
It also works when sniper mode is not used.

### PR DESCRIPTION
**Pull request by woutersmeenk**
Testcase for #3204 

+ fix #3204

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the failing test.

**Comment by monperrus** [comment]
Could you allow maintainers to push to your branch? Thanks!

**Comment by woutersmeenk** [comment]
It was already checked:
image

I unchecked it and checked it again. Is it ok now?

**Comment by monperrus** [comment]
perfect, it works.

**Comment by monperrus** [comment]
ready to merge

**Comment by nharrand** [comment]
LGTM! Thanks @woutersmeenk (and @monperrus )!

**Pull request merged**
