### PR TITLE
WIP ongoing work on non fqn types in sniper mode

### PR DESCRIPTION
**Pull request by moraispgsi**
Test for #3176

### CODE REVIEW

**Comment by moraispgsi** [comment]
@monperrus I only managed to replicate part of the problem yet from #3176. This one shows how the inline package is being added to the types.  I am facing difficulties in replicating the problem as it only happens when I link 4 processors to an android project with around 10 files and a lot of jar libs. All of the problems I am facing are related to the Sniper printer.

**Comment by monperrus** [comment]
Thanks for the PR, will look at it when time permits. --Martin

**Comment by monperrus** [comment]
I confirm that I can reproduce the failure locally.

As far as I understand, the problem here is that the newly added code contains fully-qualified type names (with package name). Is that correct?

**Comment by moraispgsi** [comment]
@monperrus That is right Martin, there are other problems that I mentioned in the issue, they were not replicated in this pull-request. I may have a way for us to debug spoon in android projects. I have a gradle plugin that integrates spoon with android projects (more or less), it is part of my master's thesis, if it would help I could make it available, I must, however, retain ownership of it. I need to have the sniper pretty printer working properly for my thesis to be complete, by making this available to the spoon team we can make the sniper pretty printer better and spoon will have another perk for adoption. Martin, is this something you would like to consider?

**Comment by monperrus** [comment]
Hi Ricardo. Thanks for the bug report, the problem is now clear.

@pvojtechovsky any idea on where to look at to pretty-print new elements in short version when using the sniper mode?

**Comment by moraispgsi** [comment]
@monperrus He doesn't seem to be available, can we fix this without his help?

**Comment by monperrus** [comment]
yes, we'll try, but it will be hard. the sniper pretty-printer is a very sophisticated piece of
code, see research papers in #1284

**Comment by monperrus** [comment]
I have a fix. Please set the pull-request option that the Spoon maintainers can push to PR branch (in this case `TQRG/spoon:master`)

**Comment by moraispgsi** [comment]
Nice, it is already on.

**Comment by monperrus** [comment]
Probably not:

```
git push ssh://github.com/TQRG/spoon 3181:master
ERROR: Permission to TQRG/spoon.git denied to monperrus.
```

**Comment by moraispgsi** [comment]
I have "Allow edits from maintainers" checked. Are there any other options that need to be enabled?

**Comment by moraispgsi** [comment]
Added you as a collaborator, that should do it.

**Comment by monperrus** [comment]
> I have "Allow edits from maintainers" checked. 

Strange, it does not work. Maybe because your repo requires two-factor auth for everybody.

Anyway, accepted the invitation and pushed. Does the fix work for you?

**Comment by moraispgsi** [comment]
It does seem to fix the package suffixes. I still have a problem with the catch Exception types being glued to the variable name like shown in #3176. I can't seem to be able to replicate the issue on a small scale test case.

**Comment by moraispgsi** [comment]
Here is the progress that was made. https://www.diffchecker.com/nn7ba6cL
We can see that if there are fully qualified names in the original file, they are removed. This is not the expected behavior I suppose. Also, a lot of parentheses are added for no reason and catch clause Exception types are being glued to the name of the variable.

**Comment by monperrus** [comment]
then could you add a new failing test case to this PR? that's super useful. Thanks!

**Comment by moraispgsi** [comment]
@monperrus Martin, I don't mean to be rude, but would you please address my earlier comments, some of the comments remained unanswered. I told you that I could not replicate this part of the issue, I instead ask if there is another alternative to implementing a small failing test case. I also said that I have a small android application where I am able to replicate the problem, however, I need to have a bunch of jars in the classpath, including the Android SDK jar. The other thing I said was that I have a tool that is able to integrate an android project, and I suggested that I would make it available for further improvement of the sniper pretty-printer. Also, I asked if that would be something that you would find useful, and if so, what would be the next steps. Thank you so much for your help so far.

**Comment by monperrus** [comment]
> I also said that I have a small android application where I am able to replicate the problem, however, I need to have a bunch of jars in the classpath, including the Android SDK jar.

Very good. You can push it to the repo, we replicate the bug, we fix it and then we remove all those big files before merging.

> I have a tool that is able to integrate an android project, and I suggested that I would make it available for further improvement 

Nice, your contribution is highly welcome, mostly likely in a separate pull-request since it's a new feature.

**Comment by moraispgsi** [comment]
Great to hear, I make it available in the near future. Thanks, you can close this one then.

**Comment by monperrus** [comment]
superseeded by #3194

**Pull request closed without merging**
