### PR TITLE
Sonarqube-repair - add no-argument constructor in SubFactory

### PR DESCRIPTION
**Pull request by ashutosh1598**
This PR repairs [three sonarqube bugs](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&rules=squid%3AS2055&types=BUG). Classes ModuleFactory, PackageFactory, and DefaultCoreFactory extend SubFactory and are Serializable. But SubFactory is not Serializable and should contain a no-argument constructor according to [Sonar Rule 2055](https://rules.sonarsource.com/java/type/Bug/RSPEC-2055).

Even though I enabled comments, spoon did not pick up the commented out code and hence this diff. But that block is commented since 5 years and is itself marked as a [code smell](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&issues=AWIvav2IRIyoeYNsnf03&open=AWIvav2IRIyoeYNsnf03) by Sonarqube.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
I would say that it is a bug that some Spoon SubFactory classes are serializable. We never serialize them, but we attach new instance of these factories to deserialized Factory.

**Comment by monperrus** [comment]
Is that exactly the sniper-mode pretty-printing?

(it is interesting that the commented method is completely removed by the sniper)

**Comment by ashutosh1598** [comment]
Yes this was the exact file printed by sniper mode.

**Comment by monperrus** [comment]
Could you prepare an alternative PR with the other solution (removing "implements Serializable") so that we can compare the impact?

**Comment by ashutosh1598** [comment]
Yes I'm doing that right now.

**Comment by ashutosh1598** [comment]
Fixed in https://github.com/INRIA/spoon/pull/2173

**Pull request closed without merging**
