### PR TITLE
doc: update supported java version in readme.md

### PR DESCRIPTION
**Pull request by MartinWitt**
To my best knowledge, we support up to java 20, so we should update the doc.

### CODE REVIEW

**Comment by slarse** [comment]
Do we really support all features up until Java 20? Or do you mean that Spoon _runs_ on Java 20?

**Comment by MartinWitt** [comment]
The latest non preview features were: records and type patterns, both are implemented (see CtRecord and CtTypePattern). Java 20 has no new non preview feature relevant for spoon(see https://openjdk.org/projects/jdk/20/). So yes, we support all non preview features up to java 20 and spoon runs on java 20.

**Comment by slarse** [comment]
Hmm, isn't it a bit misleading to claim that Spoon _fully_ supports version X when it does not implement any preview features? Minor semantics here, but perhaps drop the "fully"?

**Comment by MartinWitt** [comment]
Agree, I removed the `fully`.

**Review by slarse — APPROVED** [review]
LGTM, thanks @MartinWitt :)

**Pull request merged**
