### PR TITLE
Feature: Java 12 Switch Expressions

### LINKED ISSUE #3011: feat: add support for java 12
Hello! I was wondering, what's current situation about java 11 (12?) ? I looked at roadmap, but it's still open. And you write only about java 10 on the main page.
I tried to parse file compiled by java 11 with var and it was okay for me.

I only need to parse source and get fields for all classes, does everything work right now for java 11? or is it still in progress? I think I am interested only about jep-323, as I understand it's not supported right now, what's the plan about it? Thanks!

### PR DESCRIPTION
**Pull request by Egor18**
Fix #3011
This PR is to support Java 12 Switch Expressions preview feature and new syntax.
More info:
https://openjdk.java.net/jeps/325
https://openjdk.java.net/jeps/354
https://docs.oracle.com/en/java/javase/13/language/switch-expressions.html

Roadmap:
1. Update eclipse JDT [DONE]
2. Support new arrow syntax (`case 1 -> x = 1;`) in switch [DONE]
3. Support multiple expressions (`case 1, 2, 3 -> x = 1;`) in case [DONE]
4. Support switch expression (`int x = switch(i) {...};`) [DONE]

Moreover, Java 13 introduced `yield` keyword to replace break in switch. We should probably add this one later as well.

Note: Right now Switch Expressions are a preview feature, but I believe it will be in standard Java 14.

### CODE REVIEW

**Comment by monperrus** [comment]
yeah! supporting Java 12 will be great.

**Comment by Egor18** [comment]
Well, I think Java 12 is here.
Code review or additional unit tests are welcome!

**Comment by monperrus** [comment]
Hi @Egor18 

Thanks a lot for this very important PR.

Reviewed it, looks great. Plus `263 of 285 new or added lines in 24 files covered. (92.28%)`, perfect!

LGTM.

**Comment by nharrand** [comment]
LGTM as well!

**Pull request merged**
