### PR TITLE
refactor: CtFormalTypeDeclarer extends CtTypeMember

### PR DESCRIPTION
**Pull request by pvojtechovsky**
What about this small change in spoon model?

### CODE REVIEW

**Comment by monperrus** [comment]
what's the purpose?

**Comment by pvojtechovsky** [comment]
The code which collects formal type arguments of declaring types is **little** bit simpler if CtFormalTypeDeclarer extends CtTypeMember, because it is so. CtFormalTypeDeclarer already extends CtFormalTypeDeclarer, but it is not declared in model.

But if you have any reason why it is not good idea then close this PR. I have no problem with that.

**Comment by monperrus** [comment]
> CtFormalTypeDeclarer already extends CtFormalTypeDeclarer
what do you mean exactly? :-)

**Comment by pvojtechovsky** [comment]
That all existing implementations of `CtFormalTypeDeclarer` already implements `CtTypeMember`

**Comment by monperrus** [comment]
Then I'm fine to merge this one. If somebody disagrees, drop a comment :-)

**Comment by msteinbeck** [comment]
look good to me

**Pull request merged**
