### PR TITLE
chore: Add a windows build for Java 1.8

### LINKED ISSUE #3691: Discussion(CI): Which jdks for testing?
As we have a new JDK every half year and [java 16](https://openjdk.java.net/projects/jdk/16/) isn't that far away. We could starting a discussion what JDK versions are interesting for CI usage. Currently we use 8, 10 and 11. We could use all JDKs for testing, but the CI takes already really long for testing.
### travis limits:
A job gets canceled 
- When a job produces no log output for 10 minutes.
- When a job on a public repository takes longer than 50 minutes.
- When a job on a private repository takes longer than 120 minutes.

### JDKs
- 8 minimal version we support, important to test. 
- 9 breaking changes because module system
- 10 only `var` as interesting change, but shouldn't break anything.
- 11,12,13,14 nothing really interesting
- 15 latest/bleeding edge is always good to test

We could create a job for each JDK, or choose 3 (?) interesting for default CI and run with all JDKs only when some condition is met(if travis supports this, probably exploration needed). The condition could be : 
- A PR is marked as review
- A merge/commit is done to master
- A new version/snapshot gets released
### Other OS containers
Another discussion is, if we want to use windows containers in travis for more testing. Java on Windows should produce the same results as on unix, but sometimes tests are platform dependent without a good reason. For MacOS the situation is more complex, because travis changed the costs and MacOS seems not free anymore. Supporting MacOSin the CI, would either need free credits from travis or a macos docker container.
### Discussion 
Which JDK versions do you think are the best/most interesting for using in the CI?
Shall we extend the CI with windows runners?
Shall we split the CI in different complexity depending on the PR state?
Or do you want performance increases?

### PR DESCRIPTION
**Pull request by slarse**
fix #3691 

Trying to add a Windows build.

### CODE REVIEW

**Comment by slarse** [comment]
@MartinWitt Initial windows results:

```
Tests run: 1854, Failures: 53, Errors: 4, Skipped: 18
```

That's not too bad, really.

**Comment by MartinWitt** [comment]
I´m surprised I thought we get way more errors on windows. A solution for the failing tests could be `@DisabledOnOs(WINDOWS)` first and then look step by step into each tests if it could be ported to windows. Fixing 53 testcases can take some time. Is there a timer how much the windows build slows the CI down?
`

**Comment by slarse** [comment]
The last Windows job took 12m36s, while the corresponding Linux job took 11m7s. Total build time was 12m50s for all jobs, so it seems like the Windows job only slowed it all down by a minute or so. Build times will of course vary quite a bit from build to build, and the total time will vary by the amount of available workers, but just given that data, running one Windows job is only slightly slower than running one Linux job.

Overall, I'd say that's a perfectly acceptable performance hit. Note that I'm only running the Windows build for one version of Java, I think that's sufficient.

**Comment by slarse** [comment]
And yes, I think disabling the failing tests is the most feasible next step.

**Comment by slarse** [comment]
@MartinWitt Unfortunately, the `DisabledOnOs` annotation doesn't work for Spoon's test suite as it uses the JUnit4 test annotation `org.junit.Test`. Swapping that out for the JUnit5 annotation `org.junit.jupiter.api.Test` lets the `DisabledOnOs` annotation function, but then there are some incompatibilities with JUnit4 specific features. I'd have to migrate the affected test classes (17 of them in total) to JUnit5 in order to use the annotation.

There's no equivalent JUnit4 annotation, but the following works:

```java
@Test
public void someTest() {
    org.junit.Assume.assumeFalse(System.getProperty("os.name").toLowerCase().contains("windows"));
    // run test
}
```

It's not as explicit, but at least we don't have to contend with having both JUnit4 and JUnit5 test cases in the test suite. What do you think?

**Comment by MartinWitt** [comment]
Look at the testcases we should first stop using \n for newlines and use `System.lineSeparator()`. Error Prone[0] helps a lot with platform depended problems like these. But this is an other topic, we can discuss in a other issue if needed.

For the problem we have 2 solution possibilities:
- Convert 17 tests to junit5
- Create testhelper
 
Converting even 17 test cases from junit 4 to 5 is a big task and if we start converting test cases from junit 4 to 5 we have to ask ourselves why we only convert some. But removing junit 4 is a really big task and isn't the goal of this PR. Mixing junit4 and 5 would even reduce the sometimes poor test quality. Therefore we should step away from it.

Adding a assumption for the tests cases and create a issue for a rewrite in windows friendly style is a much simpler solution oriented approach. A single PR can't fix the whole world. A step by step improvement is fine for me. But I would create a test helper like the following wrapping the assumption and add a TODO/FIXME for each testcase.
```
public static void assumeNotWindows() {
    org.junit.Assume.assumeFalse(System.getProperty("os.name").toLowerCase().contains("windows"));
}
```

[0] https://github.com/google/error-prone

**Comment by slarse** [comment]
> Looking at the testcases we should first stop using \n for newlines and use `System.lineSeparator()`. Error Prone[0] helps a lot with platform depended problems like these. But this is an other topic, we can discuss in a other issue if needed.

That depends on the use case. For example, when testing the sniper printer, it is entirely correct to use a literal `\n` in an assertion if that's what's in the source file. The sniper should use the line separator found in the source file and not the default line sep for the system.

> For the problem we have 2 solution possibilities:
> 
>     * Convert 17 tests to junit5
> 
>     * Create testhelper
> 
> 
> Converting even 17 test cases from junit 4 to 5 is a big task and if we start converting test cases from junit 4 to 5 we have to ask ourselves why we only convert some.

I miscounted, there are 16 affected test classes (but on the order of 100 test cases in them).

>  But removing junit 4 is a really big task and isn't the goal of this PR. Mixing junit4 and 5 would even reduce the sometimes poor test quality. Therefore we should step away from it.

I agree that it's not the goal of this PR, but it's not necessarily that big a task. Most of it can be automated, e.g. IntelliJ IDEA has automatic conversion (it's not bulletproof, but it mostly works). I've done it quite a few times, and it's typically straightforward if you know both frameworks reasonably well. There's actually already some JUnit5 used throughout the tests, I found uses in these classes:

```
src/test/java/spoon/generating/CorrectIdentifierTest.java
src/test/java/spoon/test/factory/TypeFactoryTest.java
src/test/java/spoon/test/model/SwitchCaseTest.java
src/test/java/spoon/test/model/TypeTest.java
src/test/java/spoon/test/module/TestModule.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/processing/ProcessingTest.java
src/test/java/spoon/test/processing/processors/ParallelProcessorTest.java
src/test/java/spoon/test/refactoring/RefactoringTest.java
src/test/java/spoon/test/reference/ExecutableReferenceTest.java
src/test/java/spoon/test/variable/VariableTest.java
```

So completely migrating to JUnit5 would probably be worthwile, imo. It has many nice features that JUnit4 lacks, such as better support for parameterized tests, awesome temporary directory handling, a certain annotation that I wanted to use here, etc.

> Adding a assumption for the tests cases and create a issue for a rewrite in windows friendly style is a much simpler solution oriented approach. A single PR can't fix the whole world. A step by step improvement is fine for me. But I would create a test helper like the following wrapping the assumption and add a TODO/FIXME for each testcase.
> 
> ```
> public static void assumeNotWindows() {
>     org.junit.Assume.assumeFalse(System.getProperty("os.name").toLowerCase().contains("windows"));
> }
> ```

I agree that this is the best solution for the time being. I'll return to this next week, have a bunch of other open-source stuff to tend to over the weekend.

> Edit: I believe creating a follow up PR fixing all testcases for windows takes a few hours. I could provide the PR if no one wants to /can do it

I don't have a Windows dev environment, so I'm not a great candidate to do it at least.

**Comment by slarse** [comment]
Woop, it worked.

```
Tests run: 1854, Failures: 0, Errors: 0, Skipped: 75
```

**Comment by slarse** [comment]
I'd say this is ready for review. I opened #3752 regarding fixing of Windows-related test failures/errors.

**Comment by monperrus** [comment]
LGTM, thanks Simon!

@MartinWitt WDYT?

**Comment by MartinWitt** [comment]
It`s a really good solution and a big step for gaining the platform independent property back. +1 for merge

**Comment by slarse** [comment]
@MartinWitt The test suite code should be portable to any Windows environment. The build script in `tests.yml` would of course have to be adapted to Travis', and we'd have to work around the fact that [Java does not appear to be an officially supported language in Travis' Windows environment](https://docs.travis-ci.com/user/reference/windows/).

**Comment by monperrus** [comment]
Thanks a lot @slarse

**Pull request merged**
