### PR TITLE
sonarqube-repair "missing transient modifiers" in StandardEnvironment.java

### PR DESCRIPTION
**Pull request by ashutosh1598**
This repair is made by an automatic sonarqube-repair tool that I'm currently writing. It repairs the [bug](https://rules.sonarsource.com/java/type/Bug/RSPEC-1948) by adding transient modifier to all non-serializable fields in this class.

The diff is ugly because sniper mode of spoon is not yet available. But the only changes are that transient modifier is added to 9 fields.

The [repair tool](https://github.com/kth-tcs/sonarqube-repair) uses spoon itself and currently has fixes for 5 bugs : [sonar-bugs](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&rules=squid%3AS1854%2Csquid%3AS1948%2Csquid%3AS2055%2Csquid%3AS2259&types=BUG) and another one to close resources properly.

I would like to get feedback from the community. My goal is to make more pull requests in future and remove all the [sonarqube bugs](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&types=BUG) from spoon.

### CODE REVIEW

**Comment by monperrus** [comment]
without the Sniper mode, we really need to do something about the extraneous parentheses!

**Comment by monperrus** [comment]
I would propose to wait for another run of sonarqube-repair, Ashutosh and Pavel are working on
fixing the first version of the sniper mode (thanks to them!).

**Comment by monperrus** [comment]
same question: why is there a warning here?

**Comment by ashutosh1598** [comment]
Because StandardEnvironment implements Serializable and these fields are not serializable.

**Comment by monperrus** [comment]
OK, so the reasoning is that Environment is serializable, probably to (de)serialize a model. 

it seems to me that all the fields in this PR are not required to load, read, and even manipulate a model, so I'm OK to merge it.

**Comment by surli** [comment]
LGTM

**Pull request merged**
