### PR TITLE
refactor: remove unused exceptions from tests

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
rebase?

**Comment by zielint0** [comment]
@pvojtechovsky 
Yes! Here:
- https://github.com/INRIA/spoon/pull/2547
- https://github.com/INRIA/spoon/pull/2548

**Comment by pvojtechovsky** [comment]
@zielint0 you do not have to crate new PR for rebase. You can 
1) rebase
2) force push into your branch - ask long as you are the only one who works on that branch, the force push is OK.

**Comment by zielint0** [comment]
@pvojtechovsky 
Thank you for this suggestion! However I cannot use it because I am not fluent with git. I messed my Spoon fork multiple times (you even helped me some time ago with my git problem).
I can only re-introduce in separate PRs.

**Pull request closed without merging**
