### PR TITLE
My fixes for the #480 and #481 for the Stable branch

### PR DESCRIPTION
**Pull request by fanlong**
My own fixes for the parsing error and the serialization error. Testcases are included.

### CODE REVIEW

**Comment by monperrus** [comment]
thanks. 

in the Spoon project, we use the convention that one PR = one issue (because PR is the unit of discussion and merging).

Can you split the PR in two?

**Comment by fanlong** [comment]
I am not very used to the pull request system in the github. I tried but I cannot figure out how to split a pull request.  Basically my first two commits are for the serialization bug, and my third commit is for the parse error.

**Comment by monperrus** [comment]
OK. We'll cherry-pick. Thanks.

**Comment by GerardPaligot** [comment]
I separated your pull request in 2 ([here](https://github.com/INRIA/spoon/pull/486) and [here](https://github.com/INRIA/spoon/pull/487)).

Thanks for this first contribution. We hope this isn't the last one. :)

PS : For information, pull requests are made on the master branch and not the stable. Stable is used for hotfix.

**Pull request closed without merging**
