### PR TITLE
No innerclass import

### PR DESCRIPTION
**Pull request by alcides**
When "with-imports" option is turned on, the generated output code will add:

import pkg.Klass$InnerKlass

with code defined as
```java
package pkg
public class Klass {
public class InnerKlass {}
}
```

This pull requests prevents those imports from being generated (as in my case, I have the import of the Klass class). However, I believe that it should be replaced by pkg.Klass.InnerKlass, although I am not sure how this works with non-static inner classes.

### CODE REVIEW

**Comment by GerardPaligot** [comment]
You have a merge commit in your PR. Can you remove it and add a test case for your PR?

**Comment by monperrus** [comment]
This contribution looks valuable, thanks.

Could you rebase, remove the merge commit from the PR, and add a test case please? (so that the diff view of the PR is clear)

Best,

--Martin

**Comment by GerardPaligot** [comment]
I [rebased your branch](https://github.com/GerardPaligot/spoon/tree/QA_no_innerclass_import) and removed the commit of @petitpre but impossible to reproduce your bug!

Do you have a sample? You can give it in this issue, I'll develop the test case.

**Comment by monperrus** [comment]
cleaning the old pending PRs.

if the bug is still there, feel free to open an issue

**Pull request closed without merging**
