### PR TITLE
WIP test case for StackOverflowError for absurdly-long strings Issue #3570

### PR DESCRIPTION
**Pull request by darius-sas**
Pull request for issue #3570.

It seems that the error is caused by the absurdly-long string created in `src/test/resources/issue3570/DefaultTeXHyphenData.java` (copied from CoreNLP project).
If the class is removed from the project the analysis runs as expected.
I created a test case to replicate the issue: `src/test/java/spoon/Issue3570Test.java`.

Note that the exception might be raised while the debugging statement I added is called (therefore the stack trace includes OutputStreamWriter and other similar classes). If you remove the statement (`src/main/java/spoon/reflect/visitor/EarlyTerminatingScanner.java:145`) though, that doesn't happen and the error is the same as described in issue 3570.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the failing test case, that's very useful. Would you give it a try to find a fix?

**Comment by monperrus** [comment]
@darius-sas what happens if you increase the stack size of the JVM running the tests, eg `java -Xss512M` or `java -Xss4096M`?

**Comment by darius-sas** [comment]
The test passes and the class is parsed properly.

Sorry for not replying to you, but I am busy with another project ATM. If you haven't found a fix yet, I'll try give it a look next week.

**Comment by monperrus** [comment]
OK, so this is a performance problem not a functional bug: we take too many calls per depth in the binary addition operation tree.

With the default stack size, what happens if you disable the checks with `launcher.getEnvironment().disableConsistencyChecks()`

**Comment by darius-sas** [comment]
Consistency checks were already disabled.
```Java
            Launcher launcher = new Launcher();
            Environment environment = launcher.getEnvironment();
            environment.setEncoding(StandardCharsets.UTF_8);
            environment.disableConsistencyChecks();
            environment.setComplianceLevel(9);
            environment.setIgnoreDuplicateDeclarations(true);
            environment.setCommentEnabled(false);
            environment.setNoClasspath(true);
            environment.setShouldCompile(false);
            environment.debugMessage("ALL");
```

**Comment by monperrus** [comment]
Per our [contribution process](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md), we're closing stale PRs, with no activity in the last 3 months. Should we restart working on this, we'll re-open it.

Thanks!

**Pull request closed without merging**
