### PR TITLE
fix: fix NullPointerException (issue #3514)

### LINKED ISSUE #3514: Analyzing project creates a NullPointerException
Hi @ll,

when I try analyzing the project [1] I am getting the following exception
```
[main] INFO spoon.Launcher - Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable StereotypeAPI at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action.repository/src/org/palladiosimulator/simulizar/action/repository/black/ProfilesLibrary.java:76).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable LOGGER at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:371).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable state at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:373).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable LOGGER at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectInterpreter.java:396).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.slidingwindow/src/org/palladiosimulator/simulizar/slidingwindow/probeframework/SlidingWindowProbeFrameWorkListenerDecorator.java:100).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar.slidingwindow/src/org/palladiosimulator/simulizar/slidingwindow/runtimemeasurement/SlidingWindowRuntimeMeasurementsRecorder.java:88).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:66).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Supplier at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:70).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java:122).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable String at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/ResourceEnvironmentSyncer.java:289).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MetricDescriptionUtility at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java:72).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable MonitorRepositoryUtil at (./Palladio-Analyzer-SimuLizar/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java:200).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable SimuLizarMockUtils at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:73).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:100).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable Streams at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:142).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable EcoreUtil at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:142).
[main] DEBUG spoon.support.compiler.jdt.JDTTreeBuilder - Could not find declaration for variable e at (./Palladio-Analyzer-SimuLizar/tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/test/SimuLizarTestExtension.java:165).
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.reflect.declaration.CtTypeImpl.getPackageReference(CtTypeImpl.java:312)
	at spoon.support.reflect.declaration.CtTypeImpl.shouldIncludeSamePackage(CtTypeImpl.java:286)
	at spoon.support.reflect.declaration.CtTypeImpl.getUsedTypes(CtTypeImpl.java:278)
	at App.lambda$main$1(App.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at App.main(App.java:12)

Process finished with exit code 1

```

The minimal example to reproduce the exception looks as follows:
```
import spoon.Launcher;
import spoon.reflect.CtModel;

public class App {
    public static void main(String[] args) {
        // https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar
        String path = "./Palladio-Analyzer-SimuLizar";
        Launcher launcher = new Launcher();
        launcher.addInputResource(path);
        launcher.getEnvironment().setNoClasspath(true);
        CtModel model = launcher.buildModel();

        model.getAllTypes().forEach(type -> {
            type.getUsedTypes(false).forEach(usedType -> {
                System.out.println(usedType.getSimpleName());
            });
        });
    }
}
```

I am new to Spoon, thus I have no idea whether it is my fault or if there might be a bug.

Regards,
Sandro

[1] https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar

### PR DESCRIPTION
**Pull request by MartinWitt**
Fix #3514

### CODE REVIEW

**Comment by MartinWitt** [comment]
Currently waiting for CI but works local.

**Comment by monperrus** [comment]
Thanks a lot @MartinWitt, LGTM.

Could you add `Fix #3514` in the top-level PR description such as the issue is closed automatically when merging?

**Comment by MartinWitt** [comment]
sure done

**Comment by monperrus** [comment]
Thanks a lot @MartinWitt!

**Pull request merged**
