### PR TITLE
review: fix: Filter resources to replace version placeholder

### LINKED ISSUE #4249: ${spoon.version} displayed for version 3.5
```
[INFO] --- spoon-maven-plugin:3.5:check (spoon-test) @ xwiki-commons-blame-api ---
[INFO] Running in FULLCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Spoon version ${project.version}
[INFO] running Spoon...
[INFO] start processing...
[INFO] org.xwiki.tool.spoon.JUnit5JUnit4Processor
[INFO] end of processing: 
[INFO] no errors, no warnings
```

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
Closes #4249

### CODE REVIEW

**Comment by MartinWitt** [comment]
How about this small formatting change? Otherwise LGTM.

**Comment by I-Al-Istannen** [comment]
I added that conciously to separate plugins and resources :( But sure :P

**Review by monperrus — APPROVED** [review]
LGTM

**Comment by monperrus** [comment]
thanks @I-Al-Istannen

**Pull request merged**
