### PR TITLE
docs(presentation): Code transformation with Spoon.

### PR DESCRIPTION
**Pull request by GerardPaligot**

### CODE REVIEW

**Comment by GerardPaligot** [comment]
@monperrus PR ok.

**Comment by monperrus** [comment]
I propose to add a link to the presentation from the website

**Comment by GerardPaligot** [comment]
@monperrus PR ready.

**Comment by monperrus** [comment]
why are there PNG figures? are they used in the presentation? should they be in the ZIP file?

**Comment by GerardPaligot** [comment]
They are used in the presentation.

**Comment by monperrus** [comment]
why not putting them in the zipped folder then?

**Comment by GerardPaligot** [comment]
The zip folder contain the key file but I can put them in the zip if you want.

**Comment by monperrus** [comment]
OK. then we would simply add the key.zip, the PDF and we modify the MD doc file.

**Pull request merged**
