### PR TITLE
refactor: delete unused testclass - VisitorFake

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
This class is a test itself. If CtAbstractVisitor misses some method from CtVisitor, then `VisitorFake` class compilation will fail - test fails. So we should keep this file even if it looks like unused.

**Comment by zielint0** [comment]
@pvojtechovsky 
Good to know! Thank you Pavel! It was tricky! ;-)
Could you add some comment to prevent such situation in future?

**Comment by pvojtechovsky** [comment]
> Do you see any problem if I move it to "testclasses" directory?

it is special kind of test class. It is not analyzed by Spoon. So it probably doesn't belong to test classes.

> add some comment

there is already a comment which explains the purpose of that class.

**Comment by zielint0** [comment]
@pvojtechovsky 

> there is already a comment which explains the purpose of that class.

Yes! I meant something like: *This class is not explicitly used by other classes but required. Don't delete it!*

**Comment by pvojtechovsky** [comment]
It is good idea. Please make a PR which adds such comment.

**Comment by zielint0** [comment]
@pvojtechovsky 

> It is good idea. Please make a PR which adds such comment.

add warning notive to Visitor #2287

**Pull request closed without merging**
