### PR TITLE
WIP: no Javadoc for classes in the default package

### PR DESCRIPTION
**Pull request by monperrus**
fix #3330

### CODE REVIEW

**Comment by monperrus** [comment]
@slarse what do you think of this one?

**Comment by slarse** [comment]
@monperrus I haven't had a time to have a look at this yet, but I'll get around to it ASAP.

**Comment by monperrus** [comment]
cool, thanks

**Comment by slarse** [comment]
@monperrus I've had a look now, and there's one thing I'm not sure about. When a comment is put at the very end of a file (after all type declarations), it's attached to the package declaration. That doesn't really make sense; it's as far away from the package declaration as is possible. It happens for example with this comment: https://github.com/INRIA/spoon/blob/f8a96bdb648f598ce86dbf3bc5d4cd287f59531a/src/test/java/spoon/test/comment/testclasses/BlockComment.java#L102-L106

Previously, such comments were attached to the compilation unit. I think it would make sense to attach comments at the end of a file to the closest preceding type declaration. What do you think?

**Comment by monperrus** [comment]
>  I think it would make sense to attach comments at the end of a file to the closest preceding type declaration

Yes, it would be better

**Comment by slarse** [comment]
> > I think it would make sense to attach comments at the end of a file to the closest preceding type declaration
> 
> Yes, it would be better

Should I have a go at it, or are you working on it?

**Comment by monperrus** [comment]
Per our [contribution process](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md), we're closing stale PRs, with no activity in the last 3 months. Should we restart working on this, we'll re-open it.

Thanks!

**Pull request closed without merging**
