### PR TITLE
WIP: feature: add flag for skipping deleted types in printing

### PR DESCRIPTION
**Pull request by MartinWitt**
As described in #3183 this is the first iteration for the feature. There are some design decisions and printer specific questions. Do we add printer modes like this with flags in environment or is there a better place? Adding a method to an interface could be a breaking change, but we could add a default implementation to the method if we want to avoid this.

I would avoid using shell comands like `git rm,` but we could implement (and document) deleting types if sourceFolder = outputFolder. Assuming we implement this, do we want a flag to enable/disable this behavior, because removing source code as a result of a bad configuration is pretty bad experience for a user. We need to keep in mind not every project is part of a git repository and the code is not always restorable.   

### Open Work
There is still some work missing. These are more Printer specific topics.
#### Documenting
How and where should we document a new printer flag? Is there some manuell where I need to add it?
#### Naming
Some good idea for naming the flag? 
=> resolved `omitDeletedTypes`
#### Setter
Do we need to allow deactivating the flag after activating it?
#### Default mode
Maybe a topic we should discuss after heavy testing, but shall the mode be on as default?

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks @MartinWitt 

I would have two concerns:
* I'm not sure it's the responsibility of `JavaOutputProcessor` to do code analysis. Its responsibility is to print everything that is in the model.
* Per #3183, we focus on deleted types, a deleted type is more conceptual, it's not a type that `hasOnlyDefaultConstructor(type)`

WDYT?

**Comment by MartinWitt** [comment]
Yeah i thought about my approach later and you are correct. The printer should only check a flag. I changed the behavior to a flag in `CtType`. The `isRemoved` flag is set to true if the user calls `CtType.delete()`. But resetting it again to false, is more difficult. 
If we make 2 assumptions this could be possible: 
1. If a `CtType` has no parent it isn't part of the AST and can be omitted. 
2. If a deleted `CtType` gets a new parent we assume it's part of the AST again.

Assumption 1 seems correct, but about assumption 2 I'm unsure. Do you have some idea about identifying the adding a deleted type to AST?

**Comment by monperrus** [comment]
Do you mean that we would have two alternatives for deletion, one is the flag, the other is automated inference?

If yes, I think the flag is enough.

**Comment by monperrus** [comment]
Per our [contribution process](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md), we're closing stale PRs, with no activity in the last 3 months. Should we restart working on this, we'll re-open it.

Thanks!

**Pull request closed without merging**
