### PR TITLE
chore: added vscode files to .gitignore

### PR DESCRIPTION
**Pull request by Strum355**
As requested in https://github.com/INRIA/spoon/pull/3549#issuecomment-682325394

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks. It seems to me that `*.gradle` would remove `build.gradle`. WDYT?

**Comment by Strum355** [comment]
I did this under the assumption that spoon would be staying with Maven and not using Gradle or both (having to maintain both Maven and Gradle files). If something else is under consideration, I'd be happy to adjust for it

**Comment by monperrus** [comment]
FYI, we already have some gradle in subprojects, see https://github.com/INRIA/spoon/blob/master/spoon-dataflow/build.gradle

**Comment by Strum355** [comment]
Is it desirable to not gitignore gradle files at the root of the repo which exists as a maven project? If so, I can amend the gitignore to reflect that.
As it currently exists, these gitignore changes only affect from the root of the repo, so the files in spoon-dataflow/ would be unaffected.

**Comment by monperrus** [comment]
Thanks!

**Pull request merged**
