### PR TITLE
test: delete junit 4 dependency

### PR DESCRIPTION
**Pull request by MartinWitt**

### CODE REVIEW

**Comment by MartinWitt** [comment]
I restarted the CI because there were some Qodana problems.

**Comment by slarse** [comment]
I killed the workflow, Qodana had been running for over 2 hours.

**Review by slarse — APPROVED** [review]
LGTM, will merge

**Comment by MartinWitt** [comment]
@slarse see https://github.com/INRIA/spoon/pull/4618#issuecomment-1047082573

**Comment by monperrus** [comment]
bye bye junit4, it was a pleasure working with you over the years.

**Pull request merged**
