### PR TITLE
doc: change "upcall" to "call"

### PR DESCRIPTION
**Pull request by chammp**
Just fixing a small typo in a couple of Javadoc comments. Methods just _call_ each other 😉

### CODE REVIEW

**Review by I-Al-Istannen — APPROVED** [review]
There are upcalls between functions, but AFAIK they typically are up from a deeper layer in e.g. a hierarchical architecture. [One use I know is for scheduler upcalls when using a hybrid threading model](https://lkml.iu.edu/hypermail/linux/kernel/9809.3/0922.html).

Spoon is probably not *quite* at that level yet :P Thanks, will merge :)

**Comment by slarse** [comment]
"Upcall" is sometimes used in the sense of "calling a callback function". I think the word is esoteric at best and don't mind seeing it removed.

**Comment by I-Al-Istannen** [comment]
Thanks @chammp!

As an aside:
Your commit was authored by a mail not associated with your GitHub account so GitHub insisted on changing it to one that is. If you do not want this to happen, you should probably either add the gmail address to your GitHub profile or commit with the GitHub mail. If the discrepancy is intended, we might be able to figure something out next time :)

**Comment by chammp** [comment]
> Thanks @chammp!
> 
> As an aside: Your commit was authored by a mail not associated with your GitHub account (I assume) 

True. That was a mistake on my side when manually configuring the email address for this repo with git command line X_x. Thanks for the heads up :)

**Pull request merged**
