### PR TITLE
test: migrate CompilationUnitPrintTest to junit 5

### PR DESCRIPTION
**Pull request by MartinWitt**
#3919
The following has changed in the code:
Replaced junit 4 test annotation with junit 5 test annotation in test
Transformed junit4 assert to junit 5 assertion in test

### CODE REVIEW

**Comment by monperrus** [comment]
thanks @MartinWitt  would you share the code of the transformation?

**Comment by MartinWitt** [comment]
The project is more or less here, https://github.com/MartinWitt/laughing-train.

**Comment by algomaster99** [comment]
@monperrus We could use the script for bumping Junit4 to Junit5 in gumtree-spoon. I can head that.

**Comment by algomaster99** [comment]
@MartinWitt How could I apply transformations for updating Junit for [this project](https://github.com/SpoonLabs/gumtree-spoon-ast-diff)? The README for your project considers three separate transformations.

**Comment by MartinWitt** [comment]
Oh, I have three different kind of bad smell fixes planed, but currently the only real working and useful is JUnit transformation. 
You have three ways to apply it.
## Single File:
```java	
@Test
	void refactorTests3() throws IOException, InvalidRemoteException, GitAPIException {
		new TransformationEngine().applyToGivenPath(
				"PathToTests",
				"NameOfClassToRefactor", RunMode.FULL);
	}
```
## All Files
```java	
@Test
	void refactorTests3() throws IOException {
		new TransformationEngine().applyToGivenPath(
				"PathToTests",
				 RunMode.FULL);
	}
```
## Git Repo with changelog
For the git version you need to edit https://github.com/MartinWitt/laughing-train/blob/master/code-transformation/src/main/resources/app.properties
```java
@Test
public void bar() throws IOException, InvalidRemoteException, GitAPIException {
String path = ProjectPath
String filename = TypeToRefactorName
String repoPath = PathToLocalGitRepo
CommitBuilder.refactorRepo(repoPath, path, filename,
	(v, u) -> {
		return new TransformationEngine().applyToGivenPath(path, filename, RunMode.FULL);
})};
```
If you want to change which processor is used uncomment them here https://github.com/MartinWitt/laughing-train/blob/master/code-transformation/src/main/java/xyz/keksdose/spoon/code_solver/TransformationEngine.java#L73

**Pull request merged**
