### PR TITLE
Fixed nullpointer in hasTypeInImports.

### PR DESCRIPTION
**Pull request by retuxx**
I found that `hasTypeInImports` may throw a NullPointerException due to `context.compilationunitdeclaration.imports` being null. I'm not entirely sure if this is the correct place to fix the bug but at least this PR shows that there is one.

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Do you have a snippet where this fix is necessary?

**Comment by GerardPaligot** [comment]
Do you try to make something here @retuxx? I see an empty merge commit.

**Comment by retuxx** [comment]
I just merged current master into PR. I'll give you an example later. I'm in a rush at the moment.

**Comment by monperrus** [comment]
> I'll give you an example later.

any news, @retuxx?

**Comment by retuxx** [comment]
>any news, @retuxx?

I just came back from a workshop. I'm working on it.

**Comment by GerardPaligot** [comment]
Due to this issue https://github.com/INRIA/spoon/issues/671, I can reproduce the bug in a test case and, unfortunately, your patch is too light. I close your PR and I'll make a new PR soon with a better patch.

**Comment by GerardPaligot** [comment]
Ok, after more research, your fix was good and I wrote a test case. PR here: https://github.com/INRIA/spoon/pull/633

**Comment by retuxx** [comment]
Thanks @GerardPaligot.

**Pull request closed without merging**
