### PR TITLE
test: fix junit extension and false flags

### PR DESCRIPTION
**Pull request by MartinWitt**
It appears that my IDE fooled me, and failing test cases from a 'Testwatcher' is not permitted (the exception is only logged), but failing test cases from a 'AfterEachCallback' is permitted. It should now work properly. Using a 'Testwatcher' may work depending on your junit-engine version (see https://github.com/junit-team/junit5/issues/1775). I've added four test methods to this PR so that the reviewer can confirm that it now works correctly. Following that, the methods will be removed.
And this PR moves the state from the extension to the junit store mechanism.

### CODE REVIEW

**Comment by slarse** [comment]
@MartinWitt What's the state of this PR?

**Comment by slarse** [comment]
@MartinWitt Looks passing now, ready for review?

**Comment by MartinWitt** [comment]
Yes

**Review by I-Al-Istannen — COMMENTED** [review]
I'd suggest testing that, but I am not sure if you can even do that without causing surefire to fail… Looks similar enough to my fix though :)

**Review by slarse — COMMENTED** [review]
@MartinWitt Confirmed that it works. If you remove the test cases I can approve for merge!

**Comment by MartinWitt** [comment]
The test case is already removed, or did I miss something?

**Comment by slarse** [comment]
> The test case is already removed, or did I miss something?

I read the opening post and assumed that the parameterized test that you split up were the "test tests" :face_exhaling: 

But now I see that was just the split of the pre-existing test.

**Comment by slarse** [comment]
@MartinWitt Ready to merge, yes? Looks all spiffy to me.

**Comment by MartinWitt** [comment]
Yes ready2merge.

**Pull request merged**
