### PR TITLE
WIP: debug sniper mode with full project

### PR DESCRIPTION
**Pull request by moraispgsi**
@monperrus Hey Martin, I managed to bundle the project here. I was unsure on how to set up this new part within the whole spoon project, I tried to add it to the main lib but unfortunately, I was unsuccessful in transforming it from Gradle to maven(it is due to the fact that the Gradle team does not provide the right and needed dependencies used for the development of Gradle plugin outside of Gradle), and since there is already a Gradle project inside I just added the whole Gradle project as a spoon subproject. I am opening the pull request to gather your input on how to proceed. In the PR you will find two new directories, one is called "leafactor-ci", I simply added my project as-is for now. I am using a published spoon dependency instead of a local one for now (having a local one would be better I guess). The Gradle plugin that leafactor-ci produces is published on the Gradle repository for now. I also added a small android application sample that uses the leafactor-ci plugin. The plugin simply refactors the sample app using the 'refactor' task in Gradle that the plugin provides. @monperrus Please take a look and tell me what you think.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the brainstorming PR.

What's the goal of leafactor? How does it relate to the refactoring classes of Spoon?

**Comment by moraispgsi** [comment]
Leafactor does not relate to Spoon at all, it just uses it, Leafactor is just a set of refactoring rules for removing energy-consuming anti-patterns in Android projects (part of my thesis). What is actually interesting here for Spoon is the way that it works. It provides a Gradle plugin that extracts all project dependencies and provides it to the spoon classpath automatically. This facilitates the adoption of Spoon in for android projects. So you can look at Leafactor as a use case for Spoon in android using this method.  Anyway, Leafactor also has its own way of refactoring anti-patterns, which might also be useful, it is a little bit different, I wouldn't be surprised if you did not like it. Anyway, you can see how easy it is to integrate an android project by looking inside the sample folder. In the app/build.gradle file you can see all I do is provide the plugin, and set some configuration in the launcherExtension.
```
plugins {
    id 'com.android.application'
    id "com.leafactorci" version "1.0.204"
}

launcherExtension {
    sourceOutputDirectory = project.projectDir.path + '\\build'
}
```

**Comment by moraispgsi** [comment]
I provided the entire Leafactor folder in order for us to test the sniper pretty printer with the sample, which as of now is not working properly.

**Comment by moraispgsi** [comment]
@monperrus Right now you can create new refactoring rules for testing the sniper pretty printer and disable the other rules or just provide new processors if that is more confortable. In order to use the plugin, it needs to be published first or find another solution(like producing a jar and somehow adding it to the sample as a plugin, not sure if it is possible).

**Comment by monperrus** [comment]
OK. renaming the PR then.

I guess you need to change the CI config to run the Leafactor tests to show the remaining bugs in
the sniper mode.

**Comment by moraispgsi** [comment]
@monperrus The problem is that the problem does not show in the leafactor tests, because they are run in isolation. They only show up in the sample project. Let me see what I can do to make the testing process automatic. I will be in touch in a few days. Merry Christmas.

**Comment by moraispgsi** [comment]
@monperrus I managed to make it work. As of now, leafactor is built in the pipeline, a jar is constructed and fed as a plugin to the sample project, which in turn runs the plugin 'refactor' task. The result is being output to the sample/app/build/leafactor-ci folder. There are still things to be done, like creating a test and building the spoon-core as a dependency to leafactor.

**Comment by moraispgsi** [comment]
@monperrus Hey Martin, I finally made it work, everything is CI ready. A jar is compiled from the spoon-core and provided to Leafactor. Leafactor is then compiled to a jar and provided to the sample. The sample then uses Leafactor to refactor its source code. The result is being outputted to the sample/app/build/leafactor-ci folder. Finally a Diff command tests for the EasyPaint.java file. Everything seems to be ready. Hope this is enough to help in the debugging process. I will be waiting for your feedback. Thanks.

**Comment by monperrus** [comment]
Thanks. Which test should I run to see the bug?

**Comment by moraispgsi** [comment]
Well, you can see it in Travis or you can just run the following command in a shell (after everything is compiled and the refactoring task is run).
```diff ./sample/app/build/leafactor-ci/release/anupam/acrylic/EasyPaint.java ./chore/test/EasyPaintExpected.java```

For further information on how to build leafactor and the sample, see chore/travis/travis-leafactor.sh file.

**Comment by moraispgsi** [comment]
@monperrus Hey Martin, were you able to run the test?

**Comment by moraispgsi** [comment]
ping @monperrus

**Comment by monperrus** [comment]
not yet

**Comment by moraispgsi** [comment]
@monperrus Is there anything I can do to speed this up? I have to have this fixed by the end of January, otherwise I won't be able to finish my thesis in time.

**Comment by monperrus** [comment]
yes, if you can write a unit failing test case in spoon-core directly, that would be super useful
for debug and fixing.

**Comment by moraispgsi** [comment]
Ok, I will give it a try at the weekend.

**Comment by moraispgsi** [comment]
@monperrus Hi Martin, I managed to provide you with a test, I think this is exactly what you need to debug and fix the problem. I placed leafactor inside the core and added the samples to a resource folder, I used junit to run the leafactor files and a library called Aether to download the dependencies. In this sample no dependencies are needed but I have other samples to test in the future that do require artifacts from maven. Right now the test downloads the android.jar from a url and provides it to the classpath. Let me know if you need anything else.

**Comment by monperrus** [comment]
I merged with latest master and pushed on your branch. I confirm I can compile.

**Comment by monperrus** [comment]
However, I have no failing test case in `src/test`.

For instance, `mvn clean test -Dtest="**.VariableUsed"` does not work.

What's the name of the failing test case in `src/test`?

**Comment by moraispgsi** [comment]
@monperrus The test o there and it fails you can see that it fails in Travis an by running it individually. You can see the diff to see what I have done. I added a new test class called LeafactorTest inside is the test, you can run it and see that it fails.

**Comment by moraispgsi** [comment]
Here is an image to help you out https://pasteboard.co/IPDCEAY.png

**Comment by monperrus** [comment]
I confirm that `LeafactorTest.runTest` fails on Travis and my local machine.

**Comment by moraispgsi** [comment]
@monperrus Any luck so far?

**Comment by moraispgsi** [comment]
The problem with the parenthesis comes from the DefaultPrettyPrinter because it shows when the sniper is disabled.

**Comment by moraispgsi** [comment]
Commenting the following code seems to help a lot.
image
Result: https://www.diffchecker.com/ETgtQGMG

**Comment by moraispgsi** [comment]
Actually my modifications are not reflected after that change :(

**Comment by moraispgsi** [comment]
Hmm, my expected file was a bit wrong, but commenting those lines seems to fix the entire problem. What are the consequences of removing those lines?

**Comment by monperrus** [comment]
> What are the consequences of removing those lines?

These lines are runtime checks to check that everything is under control. @pvojtechovsky is the author of this (Pavel, WDYT of https://github.com/INRIA/spoon/pull/3194/files#diff-32169ed30dc3dddeb3fd38205f5ffde6?)

There are still test failures in Travis. Does it completely fix your problems?

**Comment by moraispgsi** [comment]
@monperrus Well, the rest of the problem is about Tabs and Spaces(can be seen in the diff), so I was wrong about it being completely solved. But at least the code is functional.

**Comment by moraispgsi** [comment]
Also, printing elements during processing seems to be the major cause of the issue, I had to comment two lines where I was printing elements, after that it would throw the "mute" error which was "solved" by commenting the throw statements.

**Comment by monperrus** [comment]
Spent 3 hours on your failing test case.

It was a combination of a misusage and a bug.

- misuage: never call prettyprint in a transformation with sniper-mode, because it can change the state of the AST (in particular the attributes implicit), call toStringDebug() instead
- bug: the one with the exception, see fix in last commit

Works for you?

**Comment by moraispgsi** [comment]
@monperrus Thank you for your generous effort. I wasn't aware that I could not print the elements before, only after debugging did I notice that it interfered with the output, that is why I commented those lines in one of the commits. Glad to know that there is another method for printing. I also processed more than one file which was unnecessary, when I was doing it I thought that the files would need to be processed together because they referenced one another but that is not the case. I did not take the encoding into account, I will be more careful next time. Haven't tested it yet, will do soon. I will check with other samples if there are any more problems.

**Comment by moraispgsi** [comment]
@monperrus I tried the test and it looks good to me. I also checked another sample and it seems to work fine with this fix.

**Comment by monperrus** [comment]
perfect, #3210 is the fix going to master.

thanks for the bug report.

**Comment by moraispgsi** [comment]
I am trying with another sample, https://github.com/ccrama/Slide, and I am having another problem. It is the same one has in https://github.com/INRIA/spoon/issues/3175. This seems to be a problem with the anonymous declaration of an interface that spoon is unable to read. I will investigate and try to provide a test for it.

e.g.:
```
holder.check.setOnCheckedChangeListener(
                        new CompoundButton.OnCheckedChangeListener() {
                            @Override
                            public void onCheckedChanged(CompoundButton buttonView,
                                    boolean isChecked) {
                                //do nothing
                            }
                        });
```

```stacktrace
spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for OnCheckedChangeListener(class spoon.support.reflect.reference.CtTypeReferenceImpl)
	at spoon.support.reflect.declaration.CtElementImpl.getParent(CtElementImpl.java:365)
	at spoon.support.sniper.SniperJavaPrettyPrinter.hasImplicitAncestor(SniperJavaPrettyPrinter.java:195)
	at spoon.support.sniper.SniperJavaPrettyPrinter.printElement(SniperJavaPrettyPrinter.java:210)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:298)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.handleImplicit(JDTTreeBuilderHelper.java:519)
	at spoon.support.compiler.jdt.JDTTreeBuilderHelper.handleImplicit(JDTTreeBuilderHelper.java:484)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:508)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:130)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:124)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:142)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1512)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.traverse(QualifiedTypeReference.java:212)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:682)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1107)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:365)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1415)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:812)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:773)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:423)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:448)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:421)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:365)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:330)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:96)
	at spoon.Launcher.buildModel(Launcher.java:771)
	at spoon.Launcher.run(Launcher.java:722)
	at com.leafactor.cli.engine.CompilationUnitGroup.run(CompilationUnitGroup.java:152)
	at com.leafactor.gradle.plugin.Refactor.lambda$task$3(Refactor.java:195)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.leafactor.gradle.plugin.Refactor.task(Refactor.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by monperrus** [comment]
> I will investigate and try to provide a test for it.

Great. Please make sure to start from latest master.

**Comment by pvojtechovsky** [comment]
> These lines are runtime checks to check that everything is under control. WDYT?

@monperrus, yes something got wrong if this runtime check fails. Hard to say what is wrong. Sniper printer can somehow work, but it would be safer to keep the check there. And to find and fix that primary problem instead.
But you know that :-)
I don't know more without hours of debugging.

**Comment by monperrus** [comment]
Hi Pavel! in between I spent hours in your code :-) and we merged a couple of fixes and refactorings in the sniper, see recent commits.

**Pull request closed without merging**
