### PR TITLE
release of Spoon 10.2.0

### PR DESCRIPTION
**Pull request by monperrus**
Last release was in April 2022.

# New features

* Add support for sealed classes (JEP 409). (PR: #4337)
* Allow passing environment variables in maven launcher invocations. (PR: #4830)
* Use inferred generic type in invocations. (PR: #4844)

# Bug fixes

* Fix getOriginalSourceFragment and getRawJavadoc for zip file inputs. (PR: #4850)
* Print square brackets for manually created array references. (PR: #4888)
* Fix top definitions filtering. (PR: #4873)
* Attach comment to `CtLiteral` nodes. (PR: #4836)
* Maintain insertion of types in a package. (PR: #4832)
* Handle null bodies of while statements. (PR: #4813)
* Build AST with left associative string concatenation. (PR: #4809)
* Clearer message when cannot compare fragments. (PR: #4795)
* Enable creation of packages with repeated simple names in qualified name. (PR: #4770)
* Remove super calls from implicit enum constructors. (PR: #4769)
* Adjust the source position for annotated enum values. (PR: #4780)
* Set source position of type pattern. (PR: #4755)
* Fix type of constructor calls in noclasspathmode. (PR: #4647)
* Stop adding duplicated modules when cloning them. (PR: #4747)
* Do not remove constructor parameters from inner classes. (PR: #4734)
* Respect shadowCache in JavaReflectionTreeBuilder for enclosing classes. (PR: #4709)
* Add for-loop elements to UnsupportedElementSwapper and add warning messages  (#4720). (PR: #4720)
* Remove unnecessary junit dep from spoon-smpl pom.xml. (PR: #4719)
* Search for variable declarations in previous cases. (PR: #4697)
* Use thread-local caching for actual class lookup. (PR: #4671)
* Properly print type parameter reference in instanceof. (PR: #4921)

# Performance

* Don't clone method body when adapting it for isOverriding. (PR: #4862)
* Avoid collection copies in CtPackageImpl "empty" checks. (PR: #4848)
* Override AbstractMap#get in ElementNameMap. (PR: #4849)

# Governance

* Add I-Al-Istannen as integrator. (PR: #4867)
* Add SirYwell as integrator. (PR: #4866)

# Authors
| Name    | Nb Commit |
|---------|-----------|
| renovate[bot] | 72 |
| I-Al-Istannen | 32 |
| MartinWitt | 17 |
| Hannes Greule | 16 |
| Simon Larsén | 9 |
| Martin Monperrus | 7 |
| Mikael Forsberg | 4 |
| Aman Sharma | 3 |
| Guillaume Toison | 3 |
| arsenkhy | 1 |
| chammp | 1 |
| César Soto Valero | 1 |

### CODE REVIEW

**Review by slarse — APPROVED** [review]
LGTM, should we go ahead and make the release?

**Comment by monperrus** [comment]
I also +1

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
As I really dont know how we create releases feel free to merge it @monperrus if everything is ready.

**Comment by monperrus** [comment]
Here what I've done:
* [x] Checkout commit to be released: 
  * `git checkout -b <version> <commit>`
  * eg `git checkout -b 10.2.0 ee73f4376aa929d8dce950202fabb8992a77c9fb`
* [x] Modify the pom.xml 
  * `sed -i -e 's/<version>-SNAPSHOT/<version>/' pom.xml `
  * eg `sed -i -e 's/10.2.0-SNAPSHOT/10.2.0/' pom.xml `
* [x] Create release on Maven Central with `mvn deploy` (using profile `release`, see below)
  * JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64/  mvn clean deploy -Prelease -DskipTests -Dgpg. -Dgpg.keyname=074F73B36D8DD649B132BAC18035014A2B7BFA92
* [X] Create release on Github
    * `git tag spoon-core-<version>`
    * eg `git tag spoon-core-10.2.0`
    * `git push inria spoon-core-<version>`
    * eg `git push inria spoon-core-10.2.0`
- [x] Create Pull request on Github
    - News section in `doc/doc_homepage.md`
- [x] Check if release documentation it up-to-date and improve accordingly: see https://github.com/INRIA/spoon/pull/4974

**Comment by SirYwell** [comment]
Should the description of this PR be updated? It currently does not contain the PRs that where merged after the PR was opened.

**Comment by monperrus** [comment]
You're right @SirYwell, thanks. Fixed with 3 additional bug fixes.

Next time, we'll try to minimize the time between opening and merging of the release PR!

**Comment by SirYwell** [comment]
> Next time, we'll try to minimize the time between opening and merging of the release PR!

I agree, maybe we can even "freeze" the master branch during that time.

**Pull request merged**
