### PR TITLE
fix: add temp file to gitignore and skip jacoco on releases

### LINKED ISSUE #5257: release Spoon 10.4.0
FYI, we're trying the new release pipeline now, see #3890

### PR DESCRIPTION
**Pull request by MartinWitt**
Fixes #5257

### CODE REVIEW

**Comment by MartinWitt** [comment]
We also need to delete the failed release branch afterwards.

**Comment by monperrus** [comment]
Thanks @MartinWitt 

Are we ready for a second try?

**Comment by MartinWitt** [comment]
@monperrus yes we are. As I mentioned in the issue, you have to do a **patch** release for the first time we use the script. This will release 10.4.

**Comment by monperrus** [comment]
Started a `patch` release!

**Pull request merged**
