### PR TITLE
fix actual type arguments resolving

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Fixes #1218

### CODE REVIEW

**Comment by monperrus** [comment]
awesome! could you add a test case?

**Comment by pvojtechovsky** [comment]
I will probably have time tomorrow evening for that.
The problem was that `ClassTypingContext` of `ForwardingNavigableMap$StandardDescendingMap` was asked to adapt parameter `<K>` of superclass `Maps.DescendingMap<K, V>` of `StandardDescendingMap`.
There was error in algorithm that typed parameters was searched only in current type hierarchy and was not search in type hierarchy of enclosing (declaring) class. The test case should be something like
```java
class A<T> {
 class B extends List<T> {}
}
```
where 
```java
new ClassTypingContext(classB).adaptType(classB.getSuperClass().getActualTypeArguments().get(0))
```
failed before, but should return `<T>` of class `A`.

**Comment by pvojtechovsky** [comment]
Test added

**Comment by monperrus** [comment]
thanks a lot Pavel.

**Pull request merged**
