### PR TITLE
add CtTypeInformation.getDeclaredOrInheritedField(fieldName)

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Here you are. New PR just for CtTypeInformation.getDeclaredOrInheritedField(fieldName). Including some tests.

### CODE REVIEW

**Comment by monperrus** [comment]
now that we have shadow classes, I'd propose to put those two methods in CtType and the methods would return CtField (instead of CtFieldReference)

**Comment by monperrus** [comment]
well, no, because it would not be aligned with the rest of the design. ideally, now that we have shadow classes, we could get rid of CtTypeInformation that returns references.

**Comment by pvojtechovsky** [comment]
What do you mean by `shadow classes`? 

In case of PrettyPrinting the references to fields are better, Because their creation is less expensive. PrettyPrinting needs only field name so reference is good.

Anyway I am not sure what exactly would you expect. I do not feel need for that change.

**Comment by monperrus** [comment]
that's fine this way.

> What do you mean by shadow classes? 

CtClasses built by runtime reflection (hence with no  method body)

**Pull request merged**
