### PR TITLE
refactor: make checkstyle happy

### PR DESCRIPTION
**Pull request by zielint0**
Fixed plenty checkstyle violations.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
please discuss with @monperrus first whether we want to have checkstyle in tests too. Actually we enforce checkstyle rules only in runtime code. Test are not checked.
... it might be a lot of effort to fix that ... and it would be shame to waste your effort then.

**Comment by zielint0** [comment]
@pvojtechovsky
@monperrus 
No worries, I can deal with it quickly! :)
The effort is really small and I like it. :)

**Comment by surli** [comment]
Yes actually we don't really care about the checkstyle of the tests: so if you want to take time to fix this, good, but we won't enforce it.
 as @pvojtechovsky stated: 
> ... it might be a lot of effort to fix that ... and it would be shame to waste your effort then.

But here again, as you wish.

**Comment by monperrus** [comment]
conflict here

**Comment by zielint0** [comment]
@monperrus 
Resolved.

**Pull request merged**
