### PR TITLE
chore: next release will be 8.0.0

### PR DESCRIPTION
**Pull request by monperrus**
With the recent major overhaul of imports, there are many cases of changed behavior, so we'll release 8.0.0.

### CODE REVIEW

**Comment by nharrand** [comment]
Do we do a clean 8.0.0 release, with a patch note and a github release?

**Comment by monperrus** [comment]
yes, we'll do that, that's the next PR.

**Comment by nharrand** [comment]
Ok I'll merge then!

**Comment by surli** [comment]
Guys @tmortagne just noticed that we have a release of Spoon 7.6.0 performed recently (2 november) on Maven (see: https://search.maven.org/search?q=g:fr.inria.gforge.spoon%20AND%20a:spoon-core&core=gav) but we don't have any git tag or Github release for it. I suspect it to be related with that PR, but it doesn't feel right to not have the tags/releases on github then...

**Comment by monperrus** [comment]
Correct, I'm taking care of this.

**Comment by tmortagne** [comment]
Thanks @monperrus :)

**Comment by monperrus** [comment]
See #3166

**Pull request merged**
