### PR TITLE
test: Migrate ProcessingTest to Juit5

### PR DESCRIPTION
**Pull request by Rohitesh-Kumar-Jain**
#3919

This PR just migrates ProcessingTest to Junit5, pure refactoring.

Also, I have replaced the string message in assertArrayEquals with a supplier (I believe this is part of refactoring right?)

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
One of the major breaking changes for the Assertions is that the order of the parameters changed with the output message parameter moved as the last parameter. 

And now as we need to change that order, we can replace the String messages with Supplier.

**Comment by slarse** [comment]
@Rohitesh-Kumar-Jain I don't see a good reason to replace the messages with suppliers. Can you justify that change?

**Comment by Rohitesh-Kumar-Jain** [comment]
> @Rohitesh-Kumar-Jain I don't see a good reason to replace the messages with suppliers. Can you justify that change?

I read in a guide that in case we want to enhance our test methods during the migration, we can replace the String messages with Supplier.

Screenshot 2021-05-26 at 2 44 21 PM

[Here's](https://www.baeldung.com/junit-5-migration) the link to the resource, I downloaded it from there only.

**Comment by slarse** [comment]
I have a very hard time seeing the point of that, it just seems like more code for the same result to me. I don't see how it's an enhancement, and the article you linked does not say.

In general, for these migrations, do what you need to do to make it work, and nothing more :)

**Comment by Rohitesh-Kumar-Jain** [comment]
I will replace the supplier with the comment in the next commit

**Review by slarse — APPROVED** [review]

**Comment by slarse** [comment]
@monperrus ping

**Comment by monperrus** [comment]
thanks @Rohitesh-Kumar-Jain

**Pull request merged**
