### PR TITLE
refactor: uncomment a test in VariableReferencesTest.java

### PR DESCRIPTION
**Pull request by zielint0**
I uncommented it and it worked. Should it be permanently enabled?
@surli 
WDYT?

I am ready to merge technically. But politically?

### CODE REVIEW

**Comment by surli** [comment]
@pvojtechovsky apparently you commented this test in #1186 so WDYT about uncommenting back?

**Comment by zielint0** [comment]
@pvojtechovsky 
How about uncommenting this test?

**Comment by pvojtechovsky** [comment]
you can uncomment it. I do not remember why it is commented. I just remember that FieldScope function was hard to implement and is not 100% correct in some cases. But these cases are probably not covered by that uncommented test.

**Comment by zielint0** [comment]
@pvojtechovsky 
Thanks!

**Pull request merged**
