### PR TITLE
review: chore: Switch to oracle JDK 21 in CI until nixpkgs catches up

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
We can now update the CI to use the (oracle) JDK 21 GA build.

### CODE REVIEW

**Comment by SirYwell** [comment]
Would it make sense to also drop Java 20 and add 22-ea?

**Comment by I-Al-Istannen** [comment]
Sounds fine to me

**Comment by MartinWitt** [comment]
This PR requires the java 21 fix, or? Will this conflict with the lockfile update from renovate?

**Comment by I-Al-Istannen** [comment]
It requires the 21 fix, but does not conflict.

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
Thanks @SirYwell

**Pull request merged**
