### PR TITLE
feature CtTypeMember extends CtNamedElement

### PR DESCRIPTION
**Pull request by pvojtechovsky**
WDYT?

### CODE REVIEW

**Comment by surli** [comment]
It's specified in the javadoc : 
> nested class or static/instance initializer).

Am I wrong, or a static initializer is an anonymous block?

**Comment by pvojtechovsky** [comment]
You are right, but CtAnonymousExecutable already implements CtNamedElement and returns "" for the name. So this change is breaking nothing and helps clients (me ;-) ) to query type members by name without casting...

**Comment by surli** [comment]
Hmm, actually I wonder why CtExecutable implements CtNamedElement as many executables are not named (lambda, anonymous executables, ...). @monperrus ?

**Comment by pvojtechovsky** [comment]
I vote to keep it as it is - it is may be not 100% correct from java model point of view, but I think it is good for clients.

**Comment by monperrus** [comment]
OK for me.

**Pull request merged**
