### PR TITLE
Added missing constructors to MavenLauncher and SpoonPom for profile module filtering

### PR DESCRIPTION
**Pull request by Strum355**
Related https://github.com/INRIA/spoon/pull/3569

### CODE REVIEW

**Comment by nharrand** [comment]
Hello @Strum355,

This looks good to me, but could you write a test that use the new parameter `Pattern profileFilter`?

**Comment by Strum355** [comment]
@nharrand previous PR contained tests for this https://github.com/INRIA/spoon/pull/3569/files#diff-a9ee8c1df2b50eb7cf0064b3608384a0 unless you meant for MavenLauncher class? The param is purely passed onto SpoonPom for which there exists tests in the aforementioned PR

**Comment by nharrand** [comment]
My bad, I looked in `MavenLauncherTest` and not in `SpoonPom`. Ok then, LGTM!

**Comment by nharrand** [comment]
Thanks for the contribution!

**Pull request merged**
