### PR TITLE
fix(role): CtPackage.types is CtRole.CONTAINED_TYPE

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Here is the change of role of  CtPackage.types as suggested by @monperrus in #1582

### CODE REVIEW

**Comment by tdurieux** [comment]
please also change this: 

https://github.com/pvojtechovsky/spoon/blob/5ee803799a84c693fb7da377ece094394a168628/src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java#L196

https://github.com/pvojtechovsky/spoon/blob/5ee803799a84c693fb7da377ece094394a168628/src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java#L218

https://github.com/pvojtechovsky/spoon/blob/5ee803799a84c693fb7da377ece094394a168628/src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java#L218

**Comment by pvojtechovsky** [comment]
@monperrus Will we refactor each role change individually in own PR or can I make one bigger PR for that?

Individual PRs are problem, because all of them are changing CtRole class, which then causes conflicts.  So I would prefer to make one PR, which will contain all the CtRole improvements we see now.

WDYT?

**Comment by pvojtechovsky** [comment]
By the way, all other roles have singular form, while this new role is plural. Should we rename 
CtRole.CONTAINED_TYPES
to
CtRole.CONTAINED_TYPE

WDYT?

**Comment by monperrus** [comment]
What about a strong contract: all roles which return a collection/list/set are plural?

**Comment by pvojtechovsky** [comment]
> What about a strong contract: all roles which return a collection/list/set are plural?

I vote for usage "singular always". The meaning of role itself should not contain information about how many items there is.

**Comment by monperrus** [comment]
Actually, you convince me. I now think that always singular is a good idea to make it clear that it is a role and not property/field.

So let's make them all singular.

**Comment by pvojtechovsky** [comment]
I am finished here. It is ready for merge.

**Pull request merged**
