### PR TITLE
Fix: source position when there is a comment character in annotation

### LINKED ISSUE #3606: PositionBuilder modifier positions bug
Given a class similar to the following [1], the PosiitonBuilder fails to attach a position to class modifiers.
When it encounters `/*` in `@Consumes("*/*")`, it treats it as the start of a comment. As such, it continues treating up until the "end of last modifier" position as a comment, therefore never adding a position to it.
When it discovers it has remaining modifiers, it throws an exception, causing the entire top level declaration to have NOSOURCEPOSITION assigned to it.

[1]
```java
// imports, package decl 
@Consumes("*/*")
public class DiscoveryJerseyProvider implements EtcBlahSampleText { ... }
```

### PR DESCRIPTION
**Pull request by andrewbwogi**
Closes #3606

### CODE REVIEW

**Comment by monperrus** [comment]
LGTM, unwip?

**Comment by monperrus** [comment]
@andrewbwogi unwip? ready to merge?

**Comment by andrewbwogi** [comment]
It's ok to merge

**Comment by monperrus** [comment]
Thanks a lot @andrewbwogi

**Pull request merged**
