### PR TITLE
doc: Fix Travis badge link in Readme

### LINKED ISSUE #3672: Doc: Fix links of badge in readme
Spoon moved from travis.org to travis.com, but the badge for build status links to the old travis site. It should be an easy fix to use the correct new link. At the end of the post is a screenshot of it. 
 #### Problematic Badge
image

### PR DESCRIPTION
**Pull request by Artamm**
Just a quick fix of the travis badge link (close #3672)

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks please make sure to have "fix #3672" or "close #3672" in the PR description to automatically close the issue when this is merged

**Comment by MartinWitt** [comment]
> Thanks please make sure to have "fix #3672" or "close #3672" in the PR description to automatically close the issue when this is merged

Maybe one day this should be added to Contribute.md or?
And is the CI flaky again?

**Comment by monperrus** [comment]
> Maybe one day this should be added to Contribute.md

PR welcome :)

**Comment by monperrus** [comment]
Thanks for your contribution @Artamm

**Pull request merged**
