### PR TITLE
WIP : sonarqube-repair : add transient modifiers in CtElementImpl.java

### PR DESCRIPTION
**Pull request by ashutosh1598**
This removes five sonarqube bugs. Sniper mode of spoon computes imports, so the diff isn't nice for imports. Apart from that, transient modifier has been added to five non-serializable fields.

### CODE REVIEW

**Comment by surli** [comment]
It looks like you added transient on some properties that needs to be serialized here.

**Comment by ashutosh1598** [comment]
Can you tell me how can I identify which fields do I need to Serialize? And for that I will have to add `implements Serializable` for the class of that field. But that class might have other non-serializable fields and its subclasses will also become serializable. This will introduce lots of sonarqube bugs.

**Comment by surli** [comment]
> Can you tell me how can I identify which fields do I need to Serialize?

You can at least use the serialization test we have in Spoon: here Travis shows that at least two tests from `SerializableTest` are failing and 4 from `IncrementalLauncherTest`.
For each change you make you can at least execute those tests and check everything is still ok. 

For this specific case here, I think that everything should be serializable except `factory`.

> This will introduce lots of sonarqube bugs.

Indeed but I don't see any other way to work here.

**Comment by ashutosh1598** [comment]
Ok. I didn't look at the CI and thought it was failing because of some indentation error.

**Comment by ashutosh1598** [comment]
As per the comment of @surli , I have changed this pull request to make only factory transient.
@pvojtechovsky sniper mode failed to add some imports of CtRole, so I have added them manually.

For other Fields, I will create another PR to make them serializable.

**Comment by pvojtechovsky** [comment]
@ashutosh1598 I am really happy that you are testing sniper mode and report it's problems. I am working on fixes. 
But if you make a PR from changes made by sniper mode, then I suggest that your PR should contain only necessary changes. So please fix all the problems of sniper mode manually before you make PR. It keeps the history of Spoon sources more readable. WDYT?

**Comment by ashutosh1598** [comment]
Do you mean that the PR should contain only one commit instead of multiple? Tell me if I understood your comment correctly. But isn't it true that even if a PR contains multiple commits, only one merge commit is created in the master branch.

**Comment by pvojtechovsky** [comment]
> Do you mean that the PR should contain only one commit instead of multiple? 

no. I mean that if you for example open tab [Files changed](https://github.com/INRIA/spoon/pull/2117/files) of this PR, then you should see only one change: "added transient keyword". But there is instead a lot of changes, because sniper mode is not working well yet.

**Comment by ashutosh1598** [comment]
`@MetamodelPropertyField(role = CtRole.ANNOTATION)` being changed to `@MetamodelPropertyField(role = ANNOTATION)` was not done by sniper mode. When I added imports in Intellij, it automatically refactored it. I have fixed it and copied the imports from original file.

**Comment by ashutosh1598** [comment]
@surli , for [these kind](https://sonarqube.ow2.org/project/issues?fileUuids=AWIvavK-RIyoeYNsnfPD%2CAWIvavK7RIyoeYNsnfNq%2CAWIvavK8RIyoeYNsnfOF%2CAWIvavK9RIyoeYNsnfOo&id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&rules=squid%3AS1948&types=BUG) of bugs, do you think I should add `implements Serializable` to classes like CtElement, CtAnnotation, CtComment, etc?

**Comment by surli** [comment]
Actually you can make `CtElement` serializable: every part of the Spoon model inherits from the `CtElement` and should be serializable.

**Comment by ashutosh1598** [comment]
Ok thanks for input. I have created another PR https://github.com/INRIA/spoon/pull/2241 for this. By making CtElement Serializable, lots of sonarqube bugs are repaired.

**Comment by pvojtechovsky** [comment]
Closing this one, because factory must not be made transient. factory has to be serialized together with `CtElementImpl`.

**Pull request closed without merging**
