### PR TITLE
Fix NullPointerException resulting from variable accesses in ctors.

### PR DESCRIPTION
**Pull request by retuxx**
`createVariableAccessNoClasspath` throws a NullPointerException if a
variable access is resolved for parameters in constructors as the parent
of constructor node is not available at this point.

### CODE REVIEW

**Comment by retuxx** [comment]
Do you need tests for this PR?

**Comment by surli** [comment]
Thanks for the PR.

> Do you need tests for this PR?

If you can do it quickly it's always better, at least to avoid regression.

**Comment by retuxx** [comment]
Tests will be added in a minute.

**Comment by retuxx** [comment]
Is this test suitable?

**Pull request merged**
