### PR TITLE
review refactor: Change the way simple name is used in ArrayTypeReference

### PR DESCRIPTION
**Pull request by surli**
In `CtArrayTypeReference#getSimpleName` it returns a name based on its component type: IMHO we should mark the method as a derived property. Moreover, the setter is then useless and potentially harmful for the user. So I added the annotation and an empty overridden method in the implementation.

### CODE REVIEW

**Comment by surli** [comment]
@pvojtechovsky there is one remaining failing test in `TemplateTest` maybe you have an idea how to fix it?

**Comment by pvojtechovsky** [comment]
I will have a look

**Comment by pvojtechovsky** [comment]
I am finished with the Template fix. It is ready for merge.

I agree with Simon's changes too. 

@monperrus please review and merge this one.

**Comment by danglotb** [comment]
I merged this one since @monperrus is not available. Thank you!

**Pull request merged**
