### PR TITLE
test: Migrate all the template tests to Junit5

### PR DESCRIPTION
**Pull request by Rohitesh-Kumar-Jain**
#3919

Hi, this PR involves pure refactoring.

I will be working on ```templateTest``` next hence raised the PR for migration.

In one of my previous migrations, @slarse gave a green flag for migration PR(s) involving 100 changes (50 additions - 50 deletions), so as I needed to migrate ```templateTest```,  I thought it would be nice to migrate all the tests in the template directory.

Ik this PR involves 61 additions & deletions which are more than suggested, but the changes are pretty simple.

This PR just involves these three types of changes: 

1) changing imports

2) In some assertions due to the Junit5 rules, the order of the parameters changed with the output message parameter moved as the last parameter.

3) Junit5 doesn't support ```assertThat```, so I have replaced its import with ```import static org.hamcrest.MatcherAssert.assertThat;``` this is also suggested in the [official Junit5 documentation.
](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions)

I hope 61 additions will not be difficult to review 😅

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
Few files in this PR only involved 2-3 changes so I feel it's better to club them.

Ik I am supposed to improve the test strength of the tests, next I will raise a PR for that #3967

**Comment by slarse** [comment]
> In one of my previous migrations, @slarse gave a green flag for migration PR(s) involving 100 changes (50 additions - 50 deletions)

That was a number I grabbed out of the air. 100 changes or 120 changes: same thing different name :)

> so as I needed to migrate templateTest, I thought it would be nice to migrate all the tests in the template directory.

Good call!

> Junit5 doesn't support assertThat, so I have replaced its import with import static org.hamcrest.MatcherAssert.assertThat;

Entirely correct :+1:

I gave it a glance and it looks good, but I'll wait for CI to pass and probably review this tomorrow.

**Review by slarse — APPROVED** [review]
This all looks good to me. @Rohitesh-Kumar-Jain well made decisions here, this is an easy to review PR :)

@monperrus ping for merge

**Comment by monperrus** [comment]
Very nice, thanks @Rohitesh-Kumar-Jain

**Pull request merged**
