### PR TITLE
review feat: Support (partially) JDK9 in Spoon

### LINKED ISSUE #1584: set up travis to build and run the test suite on a Java 9 JVM
see #1583

### PR DESCRIPTION
**Pull request by surli**
The goal of this PR is to be able to use JDK9 to compile and run Spoon. 
However with the introduced changes I also had to use the new version of JDT. 
This PR should fix #1584 #1599

### CODE REVIEW

**Comment by surli** [comment]
Hmmm we might have to late a little bit longer before being able to build Spoon in JDK9: lots of standard Maven Plugin are not yet ready to be used with JDK9.
See: https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw

**Comment by monperrus** [comment]
maven-antrun-plugin can be removed now.

**Comment by surli** [comment]
> maven-antrun-plugin can be removed now.

It's not my issue anymore, apparently Maven enforcer does not support JDK9 yet...

**Comment by surli** [comment]
For now Spoon is still not running on CI because spoon-maven-plugin is not yet compatible with JDK9.
However I manage to run the tests on my machine and obtained the following results:
[ERROR] Tests run: 1186, Failures: 9, Errors: 20, Skipped: 2

<details>
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MavenLauncherTest.spoonMavenLauncherTest:14 expected:<8> but was:<9>
[ERROR]   CtTypeInformationTest.testGetSuperclass:140 expected:<61> but was:<81>
[ERROR]   ImportTest.testMissingImport:211 expected:<[fr.inria.internal]> but was:<[]>
[ERROR]   ImportBuilderTest.testWithSimpleImport:61 expected:<[Type]Annotation> but was:<[Global]Annotation>
[ERROR]   ParentTest.testParentOfCtPackageReference:155 expected:<[com.awesome]> but was:<[]>
[ERROR]   PositionTest.testPositionInterface:87 expected:<77> but was:<96>
[ERROR]   TypeReferenceTest.testInvocationWithFieldAccessInNoClasspath:429 Can't compile TestBot.java
[ERROR]   ReplaceTest.testReplaceAPackageReferenceByAnotherOne:356 expected:<[com.awesome]> but was:<[]>
[ERROR]   TypeTest.test:172 expected:<[android.content.]DialogInterface$OnCl...> but was:<[]DialogInterface$OnCl...>
[ERROR] Errors: 
[ERROR]   AnnotationTest.annotationOverrideFQNIsOK:1013 » NullPointer
[ERROR]   AnnotationTest.testGetAnnotationFromParameter:958 » NullPointer
[ERROR]   CompilationTest.testPrecompile:264 » NullPointer
[ERROR]   NewClassTest.testCtNewClassInNoClasspath:154 » NullPointer
[ERROR]   CtClassTest.testNoClasspathWithSuperClassOfAClassInAnInterface » NullPointer
[ERROR]   CtClassTest.testParentOfTheEnclosingClassOfStaticClass:71 » NullPointer
[ERROR]   CtClassTest.testSpoonShouldInferImplicitPackageInNoClasspath » NullPointer
[ERROR]   ExecutableRefTest.testSameTypeInConstructorCallBetweenItsObjectAndItsExecutable » NullPointer
[ERROR]   ImportAndExtendWithPackageNameTest.testBuildModel:21 » ArrayIndexOutOfBounds 0
[ERROR]   LambdaTest.testFieldAccessInLambdaNoClassPathExternal1Example » NullPointer
[ERROR]   LiteralTest.testCharLiteralInNoClasspath » NullPointer
[ERROR]   ParameterTest.testParameterInNoClasspath » NullPointer
[ERROR]   ElasticsearchStackoverflowTest.testStackOverflow » NullPointer
[ERROR]   TypeReferenceTest.testPackageInNoClasspath » NullPointer
[ERROR]   TypeReferenceTest.testTypeReferenceSpecifiedInClassDeclarationInNoClasspath » NullPointer
[ERROR]   VariableAccessTest.testParameterReferenceInConstructorNoClasspath » NullPointer
[ERROR]   SignatureTest.testArgumentNotNullForExecutableReference » NullPointer
[ERROR]   TypeTest.testPolyTypBindingInTernaryExpression » NullPointer
[ERROR]   AccessTest.testVariableAccessInNoClasspath » NullPointer
[ERROR]   VisibilityTest.testInvocationVisibilityInFieldDeclaration:147 » NullPointer
[INFO] 
[ERROR] Tests run: 1186, Failures: 9, Errors: 20, Skipped: 2
</details>

I had to update version of JDT core and also the internal APIs of Spoon, because of the introduction of modules. 
For now my changes are only to make it compiles, I'll continue to work on it for fixing bugs.

**Comment by surli** [comment]
@monperrus for me it's ready to merge. It's a basis to start improving Spoon model to add Java 9 modules.

**Comment by monperrus** [comment]
OK for me. I'll merge.

**Comment by monperrus** [comment]
thanks a lot for this super important contribution!

**Pull request merged**
