### PR TITLE
Scanning of constructors in Enums added to CtScanner

### PR DESCRIPTION
**Pull request by adamjryan**
* Additional change - Eclipse project file removed as without the
.classpath file the imported project is erroneous, the .classpath file
is subject to evolving 3rd party libraries therefore added instructions
to generate a valid Eclipse project using Maven.

### CODE REVIEW

**Comment by petitpre** [comment]
We should add some tests before merging this PR.

**Comment by adamjryan** [comment]
Let me know if there are any issues with the visual formatting of the README addition or the general structure of the test, cheers.

**Comment by GerardPaligot** [comment]
Hi @adamjryan,

Thanks for your contribution! Unfortunately, contributors (with permissions to merge) of Spoon are on vacation. We'll merge your PR when they'll be returned (in some weeks).

**Comment by monperrus** [comment]
Hi @adamjryan,

Thanks for your contribution, it is fine. Yet it contains two completely different things: the CtScanner bug and the ".project" cleaning. 

In order of having a clean history (see the roadmap and the contribution guidelines), could you create two different commits or two different PRs?

Best,

--Martin

**Comment by adamjryan** [comment]
Done.

**Comment by monperrus** [comment]
Thanks for the cleaning!

**Pull request merged**
