### PR TITLE
doc: fix broken documentation

### LINKED ISSUE #2967: Can't access any documentation
Hello,
when I try to open any web documentation (javadoc) link from any page at http://spoon.gforge.inria.fr I always get "Not Found The requested URL *** not found on this server."
Is it problem on web side or is it some problem with my connection?
Thanks for any reply.

### PR DESCRIPTION
**Pull request by monperrus**
fix https://ci.inria.fr/sos/job/Website%20Deployer/1229/console

fix #2967

### CODE REVIEW

**Comment by MakroCZ** [comment]
@monperrus When could I expect finish of the travis push job because I still can't access documentation and I would like to finish my project as soon as possible.
Thanks

**Comment by monperrus** [comment]
Only the Javadoc is missing, you can browse it on Github, in your IDE or by downloading on Maven Central (<https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/7.3.0/spoon-core-7.3.0-javadoc.jar>).

**Comment by monperrus** [comment]
still, ready to merge

**Comment by nharrand** [comment]
For me, one of the travis job is stuck as `pending` (`continuous-integration/travis-ci/push`).

**Comment by monperrus** [comment]
restarted Travis

**Pull request merged**
