### PR TITLE
WIP: Take qualified name of declaring type into account in equals and hashCode

### PR DESCRIPTION
**Pull request by dnl50**
Fix for issue mentioned in #3365

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the patch proposal @dnl50 . In Spoon, we always add a test case with a patch, showing the fixed behavior. Could you add such a test case? Thanks!

**Comment by dnl50** [comment]
Sure, but there is also a underlying problem with cloning not setting the declaring type of the cloned element, thats why some test cases fail. #3365 contains a more detailed explanation of the problem. I will try to look into it in the coming days.

**Comment by monperrus** [comment]
OK, a failing test case is always super valuable to fully understand the problem.

**Comment by monperrus** [comment]
Revive or close?

**Comment by monperrus** [comment]
Per our [contribution process](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md), we're closing stale PRs, with no activity in the last 3 months. Should we restart working on this, we'll re-open it.

Thanks!

**Pull request closed without merging**
