### PR TITLE
chore: use GitHub actions for beta releases

### PR DESCRIPTION
**Pull request by algomaster99**
Reference: https://github.com/INRIA/spoon/issues/3890#issuecomment-1035118530

I have shifted the scripts from [spoon-deploy](https://github.com/SpoonLabs/spoon-deploy) to this repository itself. It now also uses GitHub actions instead of Travis.

Before merging this PR, there are some secrets that the maintainers need to configure. `SONATYPE_USER`, `SONATYPE_PASSWORD`, and `SPOONBOT_PARAPHRASE`. The first two are the credentials for ossrh server and the paraphrase is for decrypting the gpg key submitted in this pull request. @monperrus I sent you all these credentials over an encrypted channel in October last year. I think the credentials will be the same for Spoon as well. If indeed that is the case, could you configure them as secrets of this repository? I shall forward you that e-mail once again.

I skipped configuring [this script](https://github.com/SpoonLabs/spoon-deploy/blob/master/gpg-create-key.sh). We can do that in a separate PR.

### CODE REVIEW

**Comment by monperrus** [comment]
Great!

As before, we would to put the CD job in the spoon-deploy repo. Would you move the PR there?

**Comment by algomaster99** [comment]
> As before, we would to put the CD job in the spoon-deploy repo. Would you move the PR there?

Any specific reason why? The deployment is related to spoon and in my opinion, it should be a part of workflow this repository instead.

**Comment by slarse** [comment]
I'm also curious about this. Putting deployments in a separate repo adds complexity, so there must be some form of payoff for it to be worthwhile. Especially when using GitHub Actions.

**Comment by monperrus** [comment]
> Any specific reason why?
> so there must be some form of payoff for it to be worthwhile

The advantage is decoupling. Since CD is meant to be executed only for commits on master, it's really hard to test and debug. That's why you would see so many commits "trying CD on master" / "merging for CD", etc.

When you externalize CD to another repo, development, configuration and maintenance is easier. This is why we created https://github.com/SpoonLabs/spoon-deploy in the first place (which indeed contains many trial-and-error commits)

Some called such external CI/CD repo a "meta-repo" see https://medium.com/@marcguilera/effective-meta-repo-ci-cd-pipelines-c18676443d

**Comment by algomaster99** [comment]
> it's really hard to test and debug. That's why you would see so many commits "trying CD on master" / "merging for CD", etc.

That's a really good point. Debugging is indeed easier.

**Pull request closed without merging**
