### PR TITLE
WIP refactor: fix typos and spelling

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by zielint0** [comment]
@pvojtechovsky 
Line 686 is
`//scope methods has some parameters. ...`

Should it be
`//scope methods have some parameters. ...`
or
`//scope method has some parameters. ...`
?

I suspect that correct logic is `//scope method has some parameters. ...`.

**Comment by zielint0** [comment]
@pvojtechovsky 
Thank you Pavel.

**Comment by zielint0** [comment]
@pvojtechovsky 
Could you review changes in https://github.com/INRIA/spoon/pull/2431/files#diff-1f30815ad3488117fadbd2700e03cabf?

**Comment by pvojtechovsky** [comment]
Thank you Tomasz.

**Pull request merged**
