### PR TITLE
review refactor: Remove old mechanism "buildOnlyOutdatedFiles" as it was broken.

### PR DESCRIPTION
**Pull request by surli**
This mechanism aims at be replacing by the PR #1905 It's marked as breaking as it changes the interfaces.

### CODE REVIEW

**Comment by monperrus** [comment]
ok for me, thanks.

**Comment by monperrus** [comment]
For backward compatibility, we should keep the method signatures `buildUnits(JDTBuilder, SpoonFolder, .Array, String, boolean)` and `#buildUnitsAndModel(JDTBuilder, SpoonFolder, .Array, String, boolean)` even if the last parameter is useless. And we document this in the javadoc.

Otherwise, I'm pretty sure we'll break somebody.

**Comment by surli** [comment]
> Otherwise, I'm pretty sure we'll break somebody. 

I can push them back with a deprecated

**Comment by monperrus** [comment]
we don't even need to deprecate, as long as we document properly.
(so many people don't see the deprecation warnings).

**Comment by surli** [comment]
> (so many people don't see the deprecation warnings).

That's not a good reason why we should not use it: it seems irrelevant to maintain methods that have dead arguments in the future! So even for us it's useful to have the deprecated information. It does not necessarily means that we have to delete the methods in the next release....

**Comment by monperrus** [comment]
let's deprecate then!

**Comment by monperrus** [comment]
thanks @surli !

**Pull request merged**
