### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by dufaux**

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Hi @dufaux and thanks for your first PR on the project Spoon.

Everything seems good, I merge your PR as soon as AppVeyor and Travis are ok.

**Comment by dufaux** [comment]
Hi Gerard,
I don't know if ```java  ``` instead of {% highlight java %}   {% endhighlight %} will still work on spoon gforge.
It is still good to generate the forge?

**Comment by GerardPaligot** [comment]
I don't know what do you mean by "generate the forge" but your changes are okay. We can generate the website, deploy it on the server and have a good display.

**Comment by dufaux** [comment]
Great, I meant generate the website using markdown.

**Comment by GerardPaligot** [comment]
I merge.

**Pull request merged**
