### PR TITLE
fixed the FieldWrite bug in OperatorAssignment

### LINKED ISSUE #481: Parsing error of the right hand side of CompoundAssignmentOperators
```
public class Basic {
    Basic a;
    int us;

    public Basic foo() { return null; }

    public int bar() { return 0; }

    public void test() {
        int x = 0;
        int y = 1;
        int z = 0;
        z += a.us;
        return;
    }
}
```

For the above program in the statement "z+=a.us", "a.us" will be parsed as a CtFieldWrite instead of CtFieldRead.

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #481

### CODE REVIEW

**Comment by monperrus** [comment]
and `z+=` should be a CtVariableWrite?

**Comment by GerardPaligot** [comment]
yes, I only recovered the commit of fanlong.

**Comment by GerardPaligot** [comment]
@monperrus PR ok.

**Comment by monperrus** [comment]
some conflicts there

**Comment by GerardPaligot** [comment]
@monperrus PR ok.

**Pull request merged**
