### PR TITLE
feat: allow to access to position of a CtElement sub-part.

### PR DESCRIPTION
**Pull request by petitpre**
This pull-request allow to get more precise locations in original source code.

Implementation support only precise location for variables declaration.

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Nice to see you again!

Can you use our checkstyle file to format your code? It is hard to review your PR. :)

**Comment by tdurieux** [comment]
You never use `addFragment` in your PR, maybe you forgot to add JDTTreeBuilder.

**Comment by monperrus** [comment]
What about using an enum instead of "String part"?

**Comment by petitpre** [comment]
I prefer a string, which is more flexible and easy to hack for specifics needs.

**Comment by monperrus** [comment]
I disagree. An enum is much better for maintenance and documentation.
You can always hack on anEnumValue.toString().

**Comment by GerardPaligot** [comment]
Why not both of them? An enum documented for standard users and for hardcore spooners, a string.

**Comment by GerardPaligot** [comment]
@petitpre Are you waiting for a PR on yours or you'll update by yourself?

**Comment by petitpre** [comment]
This PR is more like a hack than a fully working feature.

I don't know when I can improve it.

**Comment by monperrus** [comment]
after our live discussion, cloning this cowboy PR. 
https://s-media-cache-ak0.pinimg.com/236x/c1/fa/cc/c1facc1f19fdf8fb7d2c0adc7278c9e6.jpg

**Pull request closed without merging**
