### PR TITLE
refactor: add override annotation in CtScanner.java

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by surli** [comment]
OK I checked the failing test: you made a change that impacts the generated classes in Spoon. So the test are only saying that the generated classes have changed now, which makes sense. 
You have to execute `CtGenerationTest` and for the failing one you might copy and paste the newly created files instead of the old ones. There are some comments on the file to indicate the command for copying, such as: 
https://github.com/INRIA/spoon/blob/0f5342e862a38c1c9875b4e23bd17cfc59663483/src/test/java/spoon/processing/CtGenerationTest.java#L140

Then commit the new files in your PR.

**Comment by zielint0** [comment]
@surli 
Mercii, I will drill it a bit.

**Comment by monperrus** [comment]
up?

**Comment by zielint0** [comment]
I tried some times but did not finished it. I would be grateful for enumerating steps in order to speed up progress.

**Comment by monperrus** [comment]
Here are the steps:

1. Update CloneVisitorGenerator so that @Override annotations are also added to CloneVisitor
2. Run CtGenerationTest.testGenerateCloneVisitor locally
3. Add new CloneVisitor to your pull request

**Comment by zielint0** [comment]
@monperrus 
Thank you a lot!

**Comment by monperrus** [comment]
No activity for one month, closing it for reducing the WIP load. Don't hesitate to reopen. Thanks for your proposal!

**Pull request closed without merging**
