### PR TITLE
feature: add support for first class resource in try-with-resource

### LINKED ISSUE #4368: [Bug] Unable to parse TryWithResourcesStatement when the resource list contains a VariableAccess
**Describe the bug**
In Java language specification, the resource list of a try with resource expression can be either a variable declaration or a variable access ([JLS15](https://docs.oracle.com/javase/specs/jls/se15/html/jls-14.html#jls-14.20.3)).
```
TryWithResourcesStatement:
    try ResourceSpecification Block [Catches] [Finally]
ResourceSpecification:
    ( ResourceList [;] )
ResourceList:
    Resource {; Resource}
Resource:
    {VariableModifier} LocalVariableType Identifier = Expression 
    VariableAccess
VariableAccess:
    ExpressionName 
    FieldAccess
```

However, the `VariableAccess` is missing if parsed with spoon.

**To Reproduce**

Input:
```java
/*Code being processed by spoon and leading to the bug.*/

public class Test {
    public void test() {
       AutoClosable resource = null;
       try (resource) {
       
       }
    }
}
```

Processing with Spoon:
```java
/*Code calling spoon on the input and triggering the bug.*/
// N/A
```

Output:
```java
/*Output code or stacktrace if unexpected Exception is raised*/
// N/A
```

The parsing result for the code snippet above will be

```java
public class Test {
    public void test() {
        AutoClosable resource = null;
        try  {
        }
    }
}
```

**Operating system, JDK and Spoon version used**

* OS: macOS 12.2
* JDK: OpenJDK 17.0.1
* Spoon version: 10.0.0

### PR DESCRIPTION
**Pull request by henryhchchc**
This PR fixes #4368.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks. Adding a new metamodel interface is a significant change in Spoon, which we do cautiously. Could you elaborate on why it's needed?

**Comment by henryhchchc** [comment]
Thanks for working on my PR. I think it is well discussed in issue #4368.

**Comment by monperrus** [comment]
@slarse @SirYwell you were involved in the conversation of #4368

WDYT of this PR?

**Comment by SirYwell** [comment]
It's basically the way I would have done it too.
The only critical point are the breaking changes. Some of the methods could be overloaded instead of replacing them, but others would require a different name...

I think we can also not get rid of the generic parameter in `CtResource` as long as it extends `CtTypedElement`, because that would mean that `CtLocalVariable<T>` indirectly extends both `CtTypedElement<T>` *and* `CtTypedElement` (raw), which isn't allowed.

Maybe it would make sense to remove `CtTypedElement` from `CtResource`, that way we can get rid of a lot of `<?>`. WDYT?

**Comment by slarse** [comment]
Essentially what @SirYwell said. We must modify the metamodel here because it's incorrect. We could do it in a less breaking fashion, though. `addReasource` and `removeResource` can be overloaded as suggested by @SirYwell. The others can't be overloaded in the way we want, as methods can't be overloaded on return types at all and it's also not possible to overload on type parameters (due to type erasure). So to mostly keep backwards compatibility there, we'd need to add new methods, which will make the interface more awkward.

**Comment by slarse** [comment]
@monperrus @MartinWitt We should decide what to do here, @henryhchchc has made a nice contribution and I don't like to see it hanging. This is a reasonable solution to the problem, but it _is_ breaking. We therefore can't incorporate it without a major version bump.

Frankly, I can't see a non-breaking solution to this problem.

**Comment by monperrus** [comment]
Agree with you @slarse 

@henryhchchc We need test cases to specify this new feature, would you add them?

**Comment by henryhchchc** [comment]
> Agree with you @slarse
> 
> @henryhchchc We need test cases to specify this new feature, would you add them?

Sorry I am too busy to work on the test cases at this moment. 🥲

**Comment by slarse** [comment]
> Sorry I am too busy to work on the test cases at this moment. smiling_face_with_tear

@henryhchchc That's entirely OK, it happens to all of us. Evidently it happened to us as we were very slow to provide feedback here :)

We'll put this on hold for the time being. If this becomes urgent for someone else, they can use your PR as a starting point. Otherwise, it will be here when you get some time again.

I'll check back in a while.

**Comment by henryhchchc** [comment]
Hi I added a test case checking whether the `try-with-resource` statements are correctly parsed.

**Comment by xzel23** [comment]
Hi, IMHO this is a rather important fix (at least for my own project, that's why I comment). I did not look at the new test cases, but I pulled this PR into my own fork of spoon, and it looks good to me: I have try-with-resources both with  variable declaration and variable access in my code, and with the PR applied all problems with the latter are fixed while former still work as expected.

**Comment by monperrus** [comment]
yes, let's finish this one.

added the natural language contracts and a few test lines to fully cover the new code.

I will merge. 

thanks a lot @henryhchchc for this valuable contribution.

**Comment by monperrus** [comment]
FYI This PR causes a regression in NpeFix see https://ci.inria.fr/sos/job/npefix/

I'm working on it for restoring backward compatibility

**Comment by slarse** [comment]
@monperrus I don't think this can be implemented to be completely non-breaking unless we add a "new api" for the same functionality, see my musings here https://github.com/INRIA/spoon/pull/4371#issuecomment-1028372310

**Pull request merged**
