### PR TITLE
refactor: sort modifiers in ModelStreamerTest.java

### PR DESCRIPTION
**Pull request by zielint0**
*Reports on declarations whose modifiers are not in the canonical preferred order (as stated in the Java Language Specification).*

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
Is it the only occurrence of that problem in tests? If there is more could we make one PR for more/all such changes?

**Comment by zielint0** [comment]
> Is it the only occurrence of that problem in tests? If there is more could we make one PR for more/all such changes?

Only in test classes. Take a look here: https://github.com/INRIA/spoon/pull/2758

**Comment by zielint0** [comment]
@pvojtechovsky 
I am ready to merge.

**Comment by pvojtechovsky** [comment]
So if it is the only place where it is wrong in test case code (all other problems are in test models), then it makes sense to merge it as it is. Thank You Tomasz

**Pull request merged**
