### PR TITLE
feature: add CtModifiable#isTransient and related methods

### LINKED ISSUE #3651: Feature: CtModifiable#isTransient
Looking at CtModifiable class, there a lot of convenience method, but `isTransient` is missing? Is there any reason for it? 
A implementation could be the following. 
```java
public boolean isTransient() {
return this.hasModifier(ModifierKind.TRANSIENT);
}
```

http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtModifiable.html

Edit: I looks like some more Modifiers from `ModifierKind` are missing. Feel free to implement them also.
I created this as good first issue, because it's relative easy and no high priority change. Some1 can have an easy start with this issue.

### PR DESCRIPTION
**Pull request by Artamm**
fix #3651 
Implemented modifiers from ModifierKind (`Transient`, `Volatile`, `Synchronized`, `Native`, `Strictfp`) for  CtModifiable class.

### CODE REVIEW

**Comment by MartinWitt** [comment]
LGTM, nice work!

**Comment by Artamm** [comment]
> LGTM, nice work!

Thank you!

**Comment by monperrus** [comment]
Hi @Artamm 
Thanks a lot for your contribution.

In Spoon we aim at strongly testing all functionalities. 

Could you add test cases to specify those new methods?

Thanks!

**Comment by Artamm** [comment]
@monperrus , thank you for your response. 
I added some test cases in `ModifiersTest`. Maybe I should add another test case/ edit what I did?

**Comment by monperrus** [comment]
Thanks a lot @Artamm , that's good testing. Do you confirm that we test all those new methods with both "true" and "false"?

**Comment by Artamm** [comment]
@monperrus, I think yes, these tests are enough to cover all cases for new methods.
Well, I had in mind to add fields in `ConcreteClass` for additional checks too, but this class extends `AbstractClass` - so it'll just duplicate the code, IMHO.
If it's needed to add something - let me know, I will add.

**Comment by monperrus** [comment]
Big thanks for your contribution @Artamm and thanks a lot @MartinWitt for the shepherding

**Pull request merged**
