### PR TITLE
review: refactor(label): remove labelledStatement that was not used

### LINKED ISSUE #1381: bug: CtContinue#getLabelledStatement should be derived, computed with lookup
and setter setLabelledStatement removed

### PR DESCRIPTION
**Pull request by tdurieux**
The property labelledStatement was always equals to null.

Fix #1381

### CODE REVIEW

**Comment by monperrus** [comment]
What about keeping only the getter `getLabelledStatement()`, put it `@Derived`, and look it up dynamically, as done for references?

**Comment by tdurieux** [comment]
It's nit a so trivial task and this api is buggy since the beginning and nobody complain. I will not spend time on a feature that nobody wants

**Comment by monperrus** [comment]
I understand, thanks for initiating the PR.

 @surli could you have a look at this, thanks?

**Comment by surli** [comment]
>  @surli could you have a look at this, thanks?

You mean to review this PR or to implement it as a derived property?

**Comment by monperrus** [comment]
to implement it as a derived property.

Thanks,

--Martin

**Comment by tdurieux** [comment]
you can test this
```java

public static void main(String[] args) {
		label2:
		{
			System.out.println("block");
			if (args.length != 0 && args[0].equals("test")) {
				System.out.println("block after break3");
				break label2;
			}
			if (args.length ==1 && args[0].equals("test")) {
				System.out.println("block after break1");
				break label2;
			}
			System.out.println("block after break");
		}
		sw:
		switch ("f") {
		case "f":
			label:
			do {
				System.out.println("do");
				while (true) {
					for (int i = 0; i < 4; i++) {
						System.out.println("for");
						label2:
						{
							System.out.println("test");
							break label2;
						}
						System.out.println("for 1");
					}
					break;
				}
				break;
			} while (true);
			break;
		}
	}
```

**Comment by monperrus** [comment]
> Add a new interface

I'm not sure about this. To be discussed.

**Comment by monperrus** [comment]
thanks @tdurieux @surli

**Pull request merged**
