### PR TITLE
chore: fix javadoc and reporting config

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by monperrus** [comment]
Exceptionally, we want to merge this one failing, because the failure upon a javadoc error is the expected behavior.

Then, we restart the build of #2910 which should fix the expected failure.

Sorry for the meta-discussion :-)

**Comment by nharrand** [comment]
Can't we first merge #2910 ? And then merge this one?

**Comment by monperrus** [comment]
yes, let's do that!

**Comment by nharrand** [comment]
I think when #2916 is merged, this can be merged smoothly (without breaking CI).

**Comment by monperrus** [comment]
merge?

**Pull request merged**
