### PR TITLE
feature: add CtElement#descendantIterator and CtElement#asIterable

### PR DESCRIPTION
**Pull request by AndreFCruz**
This is a method for obtaining an Iterator over the CtElement's descendants, as suggested in #1077 .
It aims to make the CtIterator class easier to find.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for this pull-request.

Could you add a test to verify that one can use this feature in a foreach loop?

**Comment by AndreFCruz** [comment]
I added a static method ```CtElement.asIterable``` that I think facilitates the use of the Iterator.

In this way, a user can iterate with the regular for loop:
```java
for (CtElement elem : CtElement.asIterable(ctElem)) {
        ...
}
```
and using the iterator's forEachRemaining
```java
ctElem.descendantIterator().forEachRemaining((CtElement elem) -> ... );
```

And added a test for both methods.

**Comment by monperrus** [comment]
Thanks a lot!

In Spoon, we don't use static interface methods.

Instead of a static method, is it possible to  directly have `Iterable<CtElement> asIterable()` as normal interface method + implementation in CtElementImpl?

Side-note: would you put your test directly in `CtIteratorTest.java`?

Cheers --Martin

**Comment by AndreFCruz** [comment]
Sure, moved the method to the class implementation as non-static, and moved all iteration tests to CtIteratorTest.java

**Comment by monperrus** [comment]
Thanks a lot. I'm OK to merge if nobody disagrees with those two new methods in CtElement.

**Comment by pvojtechovsky** [comment]
I like this PR too 👍

**Comment by monperrus** [comment]
Thanks a lot André for your contribution.

**Pull request merged**
