### PR TITLE
fix(visibility): Field access declared in a default class.

### LINKED ISSUE #245: Building AST for guava (JDT issue) -> action: try with latest version
JDT guys say this is not their bug, maybe you think this this is yours? :)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=468119

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #245

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Wait for Jenkins builds before the merge of this PR.

**Comment by monperrus** [comment]
Closes #245? great! I wait for your ping.

**Comment by GerardPaligot** [comment]
Jenkins is ok with Guava! :)

You can see it [here](http://193.51.236.32:8080/view/Spoon%20Monitor%20View/) (sorry, private link) and due to Guava, we're spooning 1 166 477 lines of code! :)

**Comment by monperrus** [comment]
Excellent, should I merge?

> You can see it here
> <http://193.51.236.32:8080/view/Spoon%20Monitor%20View/> (sorry,
> private link)
This view is really cool!, will it become the public one at
https://ci.inria.fr/sos/view/Spoon%20Monitor%20View/?

**Comment by GerardPaligot** [comment]
> Excellent, should I merge?

PR is okay for me.

> This view is really cool!, will it become the public one at
https://ci.inria.fr/sos/view/Spoon%20Monitor%20View/?

There is work to do this.

**Comment by monperrus** [comment]
> There is work to do this.

Let's do it then.

**Pull request merged**
