### PR TITLE
feat(CoreFactory): add create(Class) so as to create elements by reflection

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by monperrus** [comment]
Indeed it is, it is required otherwise the test also considers the new
create method.

**Comment by tdurieux** [comment]
The PR does not contains test related to the added code.

**Comment by monperrus** [comment]
it does: see SpoonArchitectureEnforcer.java
<https://github.com/INRIA/spoon/pull/949/files#diff-77ab0c75ea41f38f415582afc6510857>

**Comment by tdurieux** [comment]
Your test is not a metamodelPackageRule

**Pull request merged**
