### PR TITLE
review: refactor: use LiteralHelper in DefaultJavaPrettyPrinter

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Next baby step to the #1494

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
It is ready for merge. 

Note that LiteralHelper was made public, because it is used by PrinterHelper and DefaultJavaPrettyPrinter, which are in different packages.

**Comment by monperrus** [comment]
Interesting. This shows that class DJPP and the helpers should be in the same package. Since package `printer` is new and only contains 4 recent, non-API classes, I propose to move them all in package `visitor` and to keep them package visible.

**Comment by pvojtechovsky** [comment]
It is misunderstanding.  Package `printer` is not new. It is old and contais PrinterHelper, which already uses all these helper classes too!

Note in future I will suggest to mark all these usages in PrinterHelper deprecated, so later helpers will be really used only from DJPP. But it is really not the case now.

**Comment by monperrus** [comment]
> It is misunderstanding. Package |printer| is not new.
It's a misunderstanding :-) I know that printer is not new. I propose to remove it and move the
classes in the same package as DJPP so as to keep/restore package-visibility of the helper classes.

--Martin

**Comment by pvojtechovsky** [comment]
Did I understood well, that you suggest to move class PrinterHelper into same package like DJPP?
I like it, but I want the confirmation because it will break compatibility to old versions.

**Comment by monperrus** [comment]
Yes, this is what I mean.

This breaks compatibility, but PrinterHelper was never meant (or documented) to be part of the
public API.

**Comment by pvojtechovsky** [comment]
The helpers were moved to the package of DJPP so they can stay package protected.
It is ready for merge or what else?

**Comment by monperrus** [comment]
OK for me, thanks. Will merge tomorrow if everybody agrees.

**Pull request merged**
