### PR TITLE
review chore: Check if Spoon compile with Maven 3.3.9

### PR DESCRIPTION
**Pull request by surli**

### CODE REVIEW

**Comment by surli** [comment]
This PR aims at fixing #1814. However, I did not reproduce any error by just compiling Spoon using Maven 3.3.9 before the downgrade (see second commit status). I assume the error occured when building a custom processor with Spoon as dependency: could you confirm that @tmortagne? 

On the other hand, downgrading the Maven dependency introduced in Spoon for MavenLaucher to 3.3.9 seems to work without errors. Maven 3.5.0 is not largely deployed so I'm in favor of merging this PR as it is. 

WDYT @pvojtechovsky @monperrus ?

**Comment by monperrus** [comment]
OK for me.

**Comment by tmortagne** [comment]
> I assume the error occured when building a custom processor with Spoon as dependency: could you confirm that @tmortagne?

It's a bit special in my case because I have a <dependencyManagement> with Maven 3.3.9 and at the same time an enforcer plugin rules that check the depencencies version compatibility. And since Spoon "requires" 3.5.0 so the enforcer rule fail.

The other issue I have is that revapi plugin seems to be disturbed by the dependencies coming from Maven 3.5.0 when building with 3.3.9.

In any case it's safer to not use a too recent version of Maven.

**Comment by surli** [comment]
So if everyone agree, please merge it.

**Pull request merged**
