### PR TITLE
question: test: reproduce Sorald's test failure

### PR DESCRIPTION
**Pull request by algomaster99**
https://github.com/ASSERT-KTH/sorald's CI has been failing for some time, and one of the reason is that the classpath is not resolved in one of our tests - https://github.com/ASSERT-KTH/sorald/blob/master/sorald/src/test/java/sorald/ClasspathModeTest.java#L22.

The test used to pass two months ago (https://github.com/ASSERT-KTH/sorald/commit/97758ed25a4c1ec5a62e0045394f69f2c41befeb), and with no new commits to the repository, it now fails. Something may have changed with the GitHub action runner. Please note that the test still passes on local, and hence it is making debugging tougher.

### CODE REVIEW

**Comment by algomaster99** [comment]
@MartinWitt @I-Al-Istannen can you please have a look at it when you have time?

**Comment by I-Al-Istannen** [comment]
I can't reproduce this locally, any tips before I take a close look? :)

**Comment by algomaster99** [comment]
I am unable to produce it locally, as well. The test in this patch passes on my system. It is just the CI which is failing and I don't understand why.

**Comment by I-Al-Istannen** [comment]
Sad times. Looks like I will need to invest some more time then…

**Comment by algomaster99** [comment]
Thanks! I will also try looking into it during the week :)

**Comment by MartinWitt** [comment]
Hey,

you have some maven http blocker in the log, see https://github.com/ASSERT-KTH/sorald/actions/runs/5602147660/job/15176115010?pr=1045#step:11:34. There seems something wrong, you normally should have this error.

**Comment by I-Al-Istannen** [comment]
Alright, this now fails consistently for me. I think the early failure in CI was because CI uses a newer maven version which changed the http defaults around?

But yea, the reasons seems to be that the inria repo (http://maven.inria.fr/artifactory/spoon-public-snapshot/
) uses http and is referenced by the ancient spoon-core 8.0.0 dependency in gumtree. See
```
Error:  Failed to execute goal on project sorald.test.project: Could not
resolve dependencies for project
sorald.test:sorald.test.project:jar:1.0-SNAPSHOT: Failed to collect
dependencies at fr.inria.gforge.spoon.labs:gumtree-spoon-ast-diff:jar:1.24 ->
fr.inria.gforge.spoon:spoon-core:jar:8.0.0 ->
org.eclipse.jdt:org.eclipse.jdt.core:jar:3.16.0 ->
org.eclipse.platform:org.eclipse.core.resources:jar:3.12.0 ->
org.eclipse.platform:org.eclipse.core.expressions:jar:3.5.100 ->
org.eclipse.platform:org.eclipse.core.runtime:jar:3.12.0 ->
org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.1 ->
org.osgi:org.osgi.service.prefs:jar:1.1.1-SNAPSHOT: Failed to read artifact
descriptor for org.osgi:org.osgi.service.prefs:jar:1.1.1-SNAPSHOT: Could not
transfer artifact org.osgi:org.osgi.service.prefs:pom:1.1.1-SNAPSHOT from/to
maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories:
[gforge.inria.fr-release
(http://maven.inria.fr/artifactory/spoon-public-snapshot/, default,
releases+snapshots), maven.inria.fr-snapshot
(http://maven.inria.fr/artifactory/spoon-public-snapshot, default,
releases+snapshots)] -> [Help 1]

```
at https://github.com/INRIA/spoon/actions/runs/5638723373/job/15273145423?pr=5355#step:10:858

**Comment by algomaster99** [comment]
Ah okay. I will update the dependency version in the test resource to the latest version then.

**Comment by I-Al-Istannen** [comment]
Very nice :)

**Pull request closed without merging**
