### PR TITLE
test: upgrade sniper unit tests to JUnit 5

### PR DESCRIPTION
**Pull request by gtoison**
Following the discussion on https://github.com/INRIA/spoon/pull/4780 the new unit test I've added was copied from other existing JUnit 4 tests.
This PR upgrades these similar tests to JUnit 5

### CODE REVIEW

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
LGTM, will merge. Thank you @gtoison

**Comment by MartinWitt** [comment]
It seems like some dependency is providing JUnit 4 as transitive dependency. And the really strange package import were not matched by my analysis. I never thought anyone creates static package imports.

**Comment by gtoison** [comment]
I swear I'm innocent!
I looked into it because https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md says that PR migrating to JUnit 5 are welcome, so maybe this should be amended too?

**Comment by slarse** [comment]
See #4792

**Pull request merged**
