### PR TITLE
doc: update license year and text

### PR DESCRIPTION
**Pull request by pombredanne**

### CODE REVIEW

**Comment by monperrus** [comment]
updated @pombredanne's branch

hope CI will be happy

**Comment by monperrus** [comment]
@MartinWitt could we merge this? WDYT?

**Comment by I-Al-Istannen** [comment]
The qodana warning seems mistaken, at least (but building a regex using string concat is maybe a tall ask).

**Comment by MartinWitt** [comment]
> @MartinWitt could we merge this? WDYT?

Yes we can merge this.

**Pull request merged**
