### PR TITLE
feat(role): add CtRole to CtReference

### PR DESCRIPTION
**Pull request by tdurieux**

### CODE REVIEW

**Comment by monperrus** [comment]
Are there tests to update to verify the well-formedness of these new roles? (eg `!(parent.isSubtypeOf(candidate.getFactory().createCtTypeReference(CtReference.class))` in `MetamodelTest`? other places?

**Comment by pvojtechovsky** [comment]
I have found another CtRole related issue
* CtCatchVariableImpl.type - is CtRole.TYPE
* CtCatchVariableImpl.types - is CtRole.TYPE

CtCatchVariable inherits both
* CtMultiTypedElement#getMultiTypes() - is CtRole.TYPE
* CtTypedElement#getType() - is CtRole.TYPE

Therefore dynamic accessing of attribute value on CtCatchVariable#getValue(CtRole.TYPE) is ambiguous.

I suggest to change
* CtCatchVariableImpl.types  - is CtRole.MULTI_TYPE
* CtMultiTypedElement#getMultiTypes() - is CtRole.MULTI_TYPE

@tdurieux  Thanks! ;-)

**Comment by pvojtechovsky** [comment]
CtTypeParameterReference has ambiguous get() :
	CtTypeParameterReference#getBoundingType() - has role CtRole.SUPER_TYPE
	CtTypeInformation#getSuperclass() - has role CtRole.SUPER_TYPE
CtWildcardReference has ambiguous get() :
	CtTypeParameterReference#getBoundingType() - has role CtRole.SUPER_TYPE
	CtTypeInformation#getSuperclass() - has role CtRole.SUPER_TYPE

I suggest to change:
	CtTypeParameterReference#getBoundingType() - to role CtRole.BOUNDING_TYPE

**Comment by pvojtechovsky** [comment]
What about CtTypeParameterReference and role SUPER_TYPE? There are
* CtTypeReference<?> getBoundingType()
* setBoundingType(CtTypeReference<?> superType)
* setBounds(List<CtTypeReference<?>> bounds)

Problems:
1) setBoundingType and setBounds has same role, but different type
  solution: new CtRole.MULTI_SUPER_TYPE ???
2) there is no method `List<CtTypeReference<?>> getBounds()`
  solution: add this method ??

WDYT?

**Comment by tdurieux** [comment]
> I suggest to change:
CtTypeParameterReference#getBoundingType() - to role CtRole.BOUNDING_TYPE

I will do it.


> What about CtTypeParameterReference and role SUPER_TYPE

I don't really like the idea that a field is linked to several roles. It seems there is a design problem.

**Comment by pvojtechovsky** [comment]
> CtTypeParameterReference and role SUPER_TYPE

may be this is the special case and we should really have one role here. And to use the implementation which accepts both cases - multivalue always. So let's keep this role as it is.

**Comment by pvojtechovsky** [comment]
Now this PR contains all roles needed to implement #1582. And the tests for CtReference are enabled too. @monperrus, @tdurieux  Are you OK with that? Can I merge it? 

... In case of some problems we can make another small PR.

**Comment by tdurieux** [comment]
It is good for me

**Comment by pvojtechovsky** [comment]
@tdurieux many thanks for cooperation!

**Pull request merged**
