### PR TITLE
fix: Remove parentheses around targeted expr in binary or unary op

### PR DESCRIPTION
**Pull request by Egor18**
fix #3021
I think there is no need to wrap any `CtTargetedExpression` in parentheses when it is used in binary / unary operations (precedence is higher anyway).

### CODE REVIEW

**Comment by tdurieux** [comment]
I think it can be required when the element is casted.

**Comment by Egor18** [comment]
The case with casts is still handled:
https://github.com/INRIA/spoon/blob/fb04264db07ac7a91a014a84c58aa848aab0e673/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L357-L360

I added a test just in case.

**Comment by monperrus** [comment]
LGTM.

we may miss a special case here, but if there is no test, we don't know. We will catch it with jenkins and upcoming #2724

**Comment by Egor18** [comment]
Well, I looked through all of the possible CtTargetedExpressions: 
`CtAnnotationFieldAccess<T>, CtArrayAccess<T,E>, CtArrayRead<T>, CtArrayWrite<T>, CtConstructorCall<T>, CtExecutableReferenceExpression<T,E>, CtFieldAccess<T>, CtFieldRead<T>, CtFieldWrite<T>, CtInvocation<T>, CtNewClass<T>, CtSuperAccess<T>, CtThisAccess<T>`
and all possible binary and unary operators, and I don't see any counterexamples.

BTW, the similar fix is possible for #2330.

**Comment by nharrand** [comment]
LGTM too.

**Pull request merged**
