### PR TITLE
test: interface method overrides object method

### PR DESCRIPTION
**Pull request by pvojtechovsky**
I tried to reproduce the problem mentioned in #2023 but isOverriding seems to be working well for interfaces and Object.

### CODE REVIEW

**Comment by filkra** [comment]
Hi Pavel,

here's a small snippet to reproduce the problem.

```java
CtInterface<?> objectInterface = factory.Interface().get(ObjectInterface.class);
CtClass<?> objectClass = factory.Class().get(Object.class);

CtMethod<?> objectInterfaceEquals = objectInterface.getMethodsByName("equals").get(0);
CtMethod<?> objectEquals = objectClass.getMethodsByName("equals").get(0);

assertTrue(objectInterfaceEquals.isOverriding(objectEquals));
```

with `ObjectInterface` looking like this

```java
public interface ObjectInterface {
    void doSomething();
    boolean equals(Object other);
}
```

**Comment by monperrus** [comment]
@pvojtechovsky, Do we merge this first and move the problem to another PR? Or do we update this PR?

**Comment by pvojtechovsky** [comment]
Hi Filip,

the problem is still not reproducible. Do you use latest Spoon sources?

**Comment by filkra** [comment]
Hi Pavel,

the code I posted fails on the latest master branch (0c36243c58d56ee4bd42ab25989a326eeb546450). I think the code you used in this PR is working since you used `ModelUtils.buildClass(ObjectInterface.class)` instead of `factory.Interface().get(ObjectInterface.class)`.

**Comment by filkra** [comment]
Could you please try the following ([`CtLambdaImpl`](https://github.com/INRIA/spoon/blob/58978c64df20f7ef379924c4b34bbf087ad69106/src/main/java/spoon/support/reflect/code/CtLambdaImpl.java#L111-L139) does it the same way).

```java
CtClass<?> fooClass = factory.Class().get(Foo.class);
CtClass<?> objectClass = factory.Class().get(Object.class);

CtLambda<?> objectInterfaceLambda = (CtLambda<?>) fooClass.filterChildren(new LambdaFilter(factory.Interface().get(ObjectInterface.class))).list().get(0);
CtTypeReference<?> lambdaTypeReference = objectInterfaceLambda.getType();
CtType<?> lambdaType = lambdaTypeReference.getTypeDeclaration();

CtMethod<?> lambdaTypeEquals = lambdaType.getMethodsByName("equals").get(0);
CtMethod<?> objectEquals = objectClass.getMethodsByName("equals").get(0);

assertTrue(lambdaTypeEquals.isOverriding(objectEquals));
```

```java
public interface ObjectInterface {
    void doSomething();
    boolean equals(Object other);
}
```

```java
public class Foo {

    public void useLambda() {
        ObjectInterface objectInterface = () -> { /* do nothing */ };
        objectInterface.doSomething();
    }
}
```

**Comment by pvojtechovsky** [comment]
My origin tests were wrong. Now it finally fails, so I can fix it :-)

**Comment by pvojtechovsky** [comment]
@monperrus now SuperInheritanceHierarchyFunction always visits Object reference as end of interface super type hierarchy. But is it correct? Interface doesn't extend Object, but it inherits all it's public members... https://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html#jls-9.2

Optional I might add method `SuperInheritanceHierarchyFunction#interfacesExtendObject(boolean)`, which would activate this behavior only on client's demand.

WDYT?

**Comment by monperrus** [comment]
OK for me. Ping me back when ready for merge.

Thanks, --Martin

**Comment by pvojtechovsky** [comment]
@monperrus it is ready for merge

**Comment by monperrus** [comment]
thanks!

**Pull request merged**
