### PR TITLE
WIP fix(ElementSourceFragment): fix fragment handling of duplicated annotations

### PR DESCRIPTION
**Pull request by nharrand**
…ations

### CODE REVIEW

**Comment by nharrand** [comment]
I am not sure I am happy with this fix. 

Concretly the problem we have it that the following method declaration is represented in spoon with a duplicated `@NotNull` annotation.

```java
public JavaxImportTestSource setObject(@NotNull SomeObjectDto someObjectDto)
```

The annotation is put on both the tyep reference `SomeObjectDto` and the parameter `SomeObjectDto someObjectDto`. (The Annotation element is cloned.) This lead to an issue as the type reference has a child element which position is not included in its own position. Hence the SnipperPrettyPrinter failing.

This fix hide the error and makes the SnipperPrettyPrinter not crash.

WDYT? Any opinion? Is it better not to fix until we have a better idea?

**Comment by monperrus** [comment]
Thanks for the analysis.

This is the definition of a workaround.

Pragmatically, I'm OK to merge it as long as long as we have a well explained open issue about it and a link to the issue in the source code.

Could you open the issue and document it in code?

**Comment by monperrus** [comment]
ping @nharrand

**Comment by nharrand** [comment]
The thing I'm not completely clear about is how does this case relates to Java language specification. Should the annotation be indeed cloned and added to both the parameter and the type reference, or is it a workaround of spoon?
Because in the first case, we have (to my understanding) in the position of the type reference (it should include the annotation's position). In the second case, we need a workaround for the workaroud, which can be what is implemented in this PR AFAIU.

**Comment by nharrand** [comment]
See #3359

**Pull request closed without merging**
