### PR TITLE
REVIEW fix(SniperPrettyPrinter): fix pretty-printing of joint declarations (#3386)

### PR DESCRIPTION
**Pull request by nharrand**
Reproduces #3386

### CODE REVIEW

**Comment by monperrus** [comment]
Ohh that will be tough

the ElementSourceFragment is `int a;|99, 108|int a, c;|`, it covers two elements while being attached to only `int a` (`elementFragment.getElement() == <int a>` only)

**Comment by monperrus** [comment]
The ElementSourceFragment of `int c` is merged into that of `int a` because it is a strict subset.

**Comment by monperrus** [comment]
Here is a first fix so that @fermadeiral can proceed.

It's a partial fix, fields with joint declarations won't be snipered, but the improvement is that the resulting code will compile. 

It's mergeble but it does not close #3386.

**Comment by fermadeiral** [comment]
Thanks @monperrus!

**Pull request merged**
