### PR TITLE
WIP : sonarqube-repair : add transient modifier in CtExecutableReferenceImpl.java

### PR DESCRIPTION
**Pull request by ashutosh1598**
Another run of sonarqube-repair. Adds 4 transient modifiers.

### CODE REVIEW

**Comment by monperrus** [comment]
Hi @ashutosh1598 still WIP or to be closed?

**Comment by ashutosh1598** [comment]
I don't understand why [sonarqube dashbord](https://sonarqube.ow2.org/project/issues?fileUuids=AWIvavK-RIyoeYNsnfPD&id=fr.inria.gforge.spoon%3Aspoon-core&open=AWOsMpLhRIyoeYNspj-B&resolved=false&rules=squid%3AS1948&types=BUG) is marking a List of CtTypeReference as a bug even though CtTypeReference is Serializable.

**Comment by pvojtechovsky** [comment]
> I don't understand why ...

Copied from SonarQube explanation: This rule raises an issue on non-Serializable fields, and on **collection fields when they are not private** (because they could be assigned non-Serializable values externally), and when they are assigned non-Serializable types within the class.

**Comment by ashutosh1598** [comment]
Thanks @pvojtechovsky . Then I don't see any solution(apart from making it private), because adding transient fails some tests. I'm closing this.

**Comment by monperrus** [comment]
No, they should be private to the maximum extent.

**Pull request closed without merging**
