### PR TITLE
checkstyle: fix checkstyle violations in TestSniperPrinter.java

### PR DESCRIPTION
**Pull request by zielint0**
Reintroduced https://github.com/INRIA/spoon/pull/2512

### CODE REVIEW

**Comment by monperrus** [comment]
let's try to be more specific than "clean". For instance, PRs with only line changes take too much time to review, for too little added value. We'll handle that with #2557.

So I propose to close this one.

**Comment by zielint0** [comment]
@monperrus 
Sorry for not clear title. I corrected it. It is fix of SonarQube warning - remove commented code (I also fixed other minor things).

**Comment by monperrus** [comment]
could you please provide a minimal diff?

**Comment by zielint0** [comment]
@monperrus 
Sure, will do saturday.

**Comment by zielint0** [comment]
@monperrus 
> could you please provide a minimal diff?

It's here: refactor: remove commented code (SonarQube) #2576

**Pull request merged**
