### PR TITLE
fix: doesn't adjust position for implicit source code

### PR DESCRIPTION
**Pull request by petitpre**

### CODE REVIEW

**Comment by monperrus** [comment]
do you have a test case? Thanks!

**Comment by petitpre** [comment]
No, but you can contribute :p

This modification only remove warning when the pretty printer cannot adjust position of implicit elements...

**Comment by monperrus** [comment]
We don't have a single assertion about the line-preserving mode, it
would be great to have some.

If you use this mode, you should be able to write a nice test :-)

**Comment by GerardPaligot** [comment]
Thanks @petitpre for this PR.

**Pull request merged**
