### PR TITLE
REVIEW: fix JDT error with nullable annotation

### LINKED ISSUE #1971: bug: type javax.annotation.Nullable cannot be resolved.
Hi all, I got again this JDT error, when I parse this minimal code, in not classpath.
It would be great to be able to fix it.

```java
import javax.annotation.Nullable;
import com.google.common.collect.Lists;

public class Test {
}
```

The exception disappears when  one of the import is removed.

Exception:

```java
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files

	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:159)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:226)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2432)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:4887)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromCompoundName(LookupEnvironment.java:1682)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromConstantPoolName(LookupEnvironment.java:1712)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromConstantPoolName(LookupEnvironment.java:1720)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createAnnotation(BinaryTypeBinding.java:170)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createAnnotations(BinaryTypeBinding.java:179)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:804)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:910)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:529)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1022)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1003)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:303)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:317)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:257)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:527)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:586)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:435)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:501)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:60)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:168)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:397)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:359)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:335)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:720)
```

### PR DESCRIPTION
**Pull request by tdurieux**
fix #1971

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
It looks good to me. @tdurieux are you finished?

**Comment by tdurieux** [comment]
The question is do we disable all the problems or just the problem "16777540" that is related to this issue?

**Comment by pvojtechovsky** [comment]
Good question, I guess nobody knows here how JDT compiler works internally, so it is safer to disable only known problems. It is easy to disable next one .. if needed. But if we disable everything, then real problems will be hidden and it will be hard to debug it. Is it like this?

**Comment by tdurieux** [comment]
> Is it like this?

I think so. computeSeverity is a HUGE switch with a lot of level, I just understood that 0 means unknow and 256 is ignore and then it is based on problem category and a bit flip :/.

**Comment by surli** [comment]
Remember that we now are in noclasspath mode by default.
I'm ok with the solution but as @pvojtechovsky stated it might be hard to debug in the future: what about making an environment value for this one, not necessarily with an open API, but at least with a switch for us for the test cases?

**Comment by tdurieux** [comment]
the option is setNoclasspath

**Comment by surli** [comment]
> the option is already available it is setNoclasspath

I meant another one: you might have a specific thing to debug even in no classpath. But as you wish.

**Pull request merged**
