### PR TITLE
feature CtQuery#filterChildren(null)

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Support for calling filterChildren without filter. It returns all visited elements.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
What is the problem? I do not know how to fix it.

**Comment by pvojtechovsky** [comment]
>> Filter filter = new ...;
>> element.map(new ParameterScopeQuery).map(e->filter.matches(e))...
>
> Martin wrote: I like it, esp with lambdas, it's clear and explicit. Let's first aim at this simplest version.

There is one more problem when Filter is used in existing `CtQuery#map(CtFunction)`. It is that query engine will throw ClassCastException, when Filter input **type** does not matches. 

So you have to write
```java
Filter filter = new ...;
element.map(new ParameterScopeQuery)
  .map(e->filter.matches(e)).failurePolicy(QueryFailurePolicy.IGNORE)...
```

**Comment by monperrus** [comment]
super atomic PR, thanks.

Would you add one line of Javadoc in   filterChildren to document the contract?

**Comment by monperrus** [comment]
> It is that query engine will throw ClassCastException, when Filter input type does not matches.

which is the default behavior we want, because it's very explicit at runtime, right?

**Comment by pvojtechovsky** [comment]
>> It is that query engine will throw ClassCastException, when Filter input type does not matches.
> 
> which is the default behavior we want, because it's very explicit at runtime, right?

right. We want to throw CCE on standard mapping functions, because otherwise it is very hard to found "Why my query does not work and returns nothing..."

**Comment by pvojtechovsky** [comment]
Done from my point of view

**Comment by monperrus** [comment]
rebase?

**Comment by pvojtechovsky** [comment]
Done.

**Pull request merged**
