### PR TITLE
WIP refactor: fix order

### PR DESCRIPTION
**Pull request by zielint0**
The purpose of this PR is to show *missorted modifiers* in testing code (testclasses).

Perhaps (perhaps!) some of modifier sorting could be useful.

I have chose only these testclasses that I consider useful to *fix*. But there is high probability of introducing unwanted changes!

Guys take a look, perhaps some commits could be merged.

PR as a whole is rather informational. It is more detailed response for: https://github.com/INRIA/spoon/pull/2755

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
The `WIP` prefix in the issue name is enough to stop us from merging. 
The `review` prefix in the issue name says you are finished - we can have a look.
No prefix + every test pass ... merge is possible.

**Comment by zielint0** [comment]
> The `WIP` prefix in the issue name is enough to stop us from merging.

No, one of my WIP PR was merged in the past, so I am cautionus now ;-)

**Comment by pvojtechovsky** [comment]
Are you aware that you modify `**/testclasses/**` which is intended for test models. What is purpose for cleaning there?

Note: if everything in Spoon will be "clean" - including models - then Spoon will be not tested on real life messy source code ;-)

I suggest o keep `**/testclasses/**` as it is.

@monperrus  WDYT?

**Comment by zielint0** [comment]
> Are you aware that you modify `**/testclasses/**` which is intended for test models. What is purpose for cleaning there?

It is not cleaning. It is an answer for your question about missorted modifiers - https://github.com/INRIA/spoon/pull/2755

> Is it the only occurrence of that problem in tests? If there is more could we make one PR for more/all such changes?

**Comment by zielint0** [comment]
@pvojtechovsky 
> Note: if everything in Spoon will be "clean" - including models - then Spoon will be not tested on real life messy source code ;-)

I have chosen only these testclasses where test case focuses on something different than keywords order (but there could be mistakes with choice).

The benefit is easier reading of test cases.

**Comment by zielint0** [comment]
> > but there could be mistakes with choice
> 
> I do not think it makes sense to spent our free time to check whether this change is safe or not. I will rather live with arbitrary order of modifiers ;-)

Yeah, this PR was just answer for your question! ;-)

**Pull request closed without merging**
