### PR TITLE
Fix Type package with incomplete sources

### PR DESCRIPTION
**Pull request by diorcety**
I triggered an issue with packaging and incomplete sources.
For example if a class is missing (generated or something like that).
The file add a import

package com.abcd.project2
import com.abcd.project1.MyClass

void aa() {
  new MyClass();
}

The MyClass object will be reported as com.abcd.project2.MyClass. Even if the class is not present we explicitly have an import. Shouldn't we use the import?

### CODE REVIEW

**Comment by monperrus** [comment]
It looks interesting, could you add a test case?

**Comment by diorcety** [comment]
I will try

**Comment by diorcety** [comment]
I added the test case. Without the fix i have

org.junit.ComparisonFailure: 
Expected :fr.inria.internal
Actual   :fr.inria

**Comment by GerardPaligot** [comment]
Nice bug. Thanks for your PR. Unfortunately, as you can see, some checks have errors in Travis. Can you fix them or you need some help?

**Comment by diorcety** [comment]
i will try. Thanks

**Comment by diorcety** [comment]
I can't understand the final remaining issue...

**Comment by GerardPaligot** [comment]
Hi @diorcety,

PR done on your private repository. It fixes error here.

**Comment by monperrus** [comment]
Thanks for the nice contribution!

**Pull request merged**
