### PR TITLE
added a test for Comment Association and Printing

### PR DESCRIPTION
**Pull request by tempuser1909**
For Issue #2482. Added a test class for the following issues:
1. Comment association are mixed up
2. And the comment at the end of the file is not printed

### CODE REVIEW

**Comment by tempuser1909** [comment]
Hi @pvojtechovsky, just wanted to confirm my understanding of comment association.

So for the comment associated with class `TestClassWithComments`, it is
```
//end class test
```

For comments associated with interface `testInterface`, they are
```
// ------------------------------------ //
// test / test test     //
// ------------------------------------ //
/**
   * test2
   */ 
```

And finally, the comment associated with method `mytest` under `testInterface`, it is
```
/**
   * test3
   */ 
```

Am I right? Also, I would like to ask why is
```
// ------------------------------------ //
// test / test test     //
// ------------------------------------ //
```
considered to be to associated with `testInterface` instead of being comments associated as part of class `TestClassWithComments`?

**Comment by pvojtechovsky** [comment]
>  just wanted to confirm my understanding of comment association.

you are right

> why is `// test / test test     //` considered to be to associated with testInterface instead of being comments associated as part of class TestClassWithComments?

Because in java there is usually true that comment belongs to the element which follows after the comment. But note... there are some rare exceptions from this rule.

**Comment by tdurieux** [comment]
Sorry @pvojtechovsky, I was not available this weekend.

Your fix seems good, ready for merge?

**Comment by tdurieux** [comment]
> considered to be to associated with testInterface instead of being comments associated as part of class TestClassWithComments?

It is really difficult to find a rule that will work in all the cases. You should probably take into account the number of new lines before and after the comments but I don't know what is the limit.

**Comment by pvojtechovsky** [comment]
>  ready for merge?

yes, I just added test contract comment. So then it is ready for merge

**Comment by monperrus** [comment]
Thanks a lot!

**Pull request merged**
