### PR TITLE
add simple support for enter/exit in DJPP as in CtScanner

### PR DESCRIPTION
**Pull request by monperrus**
design exploration for #1494

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
Why? To use CtScanner#enter and #exit methods for listening? Or do you mean something else?

**Comment by monperrus** [comment]
> To use CtScanner#enter and #exit methods for listening?
Yes, to extend DJPP and override #enter and #exit methods for listening.

**Comment by pvojtechovsky** [comment]
I did not debugged it, but looking at code, it looks like CtScanner#enter/exit are NEVER called by DJPP, because it always directly calls DJPP#scan method.

**Comment by monperrus** [comment]
Good point! See  c256281

My point here is not to duplicate existing responsibilities... and thanks to this discussion, we can even make DJPP come under CtScanner.

**Comment by pvojtechovsky** [comment]
> add call to enter and exit
Then, I suggest to keep `DJPP extends CtVisitor` and just add new 
`protected enter/exit(CtElement){}` methods into DJPP, same like they are in CtScanner.

I have feeling like the extending from CtScanner is confusing, because all the code of CtScanner is never called. 

But new enter/exit methods of DJPP, might be good substitution for my `PrinterListener`. I can accept that solution for now.

**Comment by monperrus** [comment]
> I have feeling like the extending from CtScanner is confusing, because all the code of CtScanner is never called.

I tend to agree... 

958c353 is an alternative. WDYT?

**Comment by pvojtechovsky** [comment]
> depends on CtAbstractVisitor instead

is better then CtScanner.

Do we want to force change of DJPP if we add new method into CtVisitor?
If DJPP extends CtAbstractVisitor, then new CtVisitor method is added to CtAbstractVisitor and may stay empty in DJPP, so DJPP will do nothing for that new method. 
Actually all the methods of DJPP implements some behavior for each method of CtVisitor. So it would make sense to force it by `DJPP implements CtVisitor`.

But I can live with both solutions. It is up to You ;-)

**Comment by monperrus** [comment]
good point again. [KISSed](https://en.wikipedia.org/wiki/KISS_principle) it accordingly: e59a7fd

**Comment by pvojtechovsky** [comment]
Looks good for me. Even the `scan(CtReference ref)` seems to be correct way. If tests pass, I agree with merge.

**Pull request merged**
