### PR TITLE
Review: to fix issue #1979

### LINKED ISSUE #1979: feature: CtScanner-based DFS Iterator for a CtElement
I am working with Spoon for a project and needed an iterator that would go over a **CtElement's** descendants in a depth-first search manner, since **CtScanner** does not do this one element at a time, but rather at once (using `enter()` and `exit()`) it was not fitted for my designs. So I created a **CtIterator**.

If you can't see why this would be needed instead of an extended CtScanner consider you have two elements and need to go through both their trees but only advance on one, when a condition is met on the other and vice-versa. 

### Example behaviour

```java
CtIterator iterator = new CtIterator(/** some CtElement*/); 
while (iterator.hasNext()) { 
    CtElement next = (CtElement) iterator.next(); 
    System.out.println(next.toString()); 
}
```

If you would like me to create a PR to spoon with my implementation of CtIterator, please say so. Otherwise just close this issue.

😃

### PR DESCRIPTION
**Pull request by msramalho**
Implements an iterator for any `CtElement` that can be used as follows:
```java
CtIterator iterator = new CtIterator(/** some CtElement*/); 
while (iterator.hasNext()) { 
    CtElement next = (CtElement) iterator.next(); 
    System.out.println(next.toString()); 
}
```

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for this PR!

> creating the tests

Here is a suggestion. One can visit of a small tree, put the elements in a list, a verify the order of the list in an assertion.

**Comment by msramalho** [comment]
I think this is ready for merge, if you want someone who knows how to improve the tests by using an `AbstractProcessor` wants to do so, they are welcome 😄

**Comment by monperrus** [comment]
Looks like the PR for #1077. Correct?

**Comment by msramalho** [comment]
Actually the PR for #1979 

A friend of many actually suggested that this `CtIterator` can be used to fix #1077 as well, just by wrapping it and providing a class that implements `Iterable`. He might have something to say @AndreFCruz

**Comment by monperrus** [comment]
I'm OK to merge this one: good feature, good test, good documentation.

**Comment by monperrus** [comment]
We'll discuss about #1077 after that. @tdurieux suggests a simple `iterator` method in CtElement.

**Comment by monperrus** [comment]
Thanks a lot for this first contribution, looking forward to the one for #1077 @AndreFCruz

**Pull request merged**
