### PR TITLE
test: CtComment with \r separator

### PR DESCRIPTION
**Pull request by surli**

### CODE REVIEW

**Comment by monperrus** [comment]
thanks

**Comment by pvojtechovsky** [comment]
I afraid that this PR destroyed existing test testJavaDocCommentOnUnix which expects that JavaDocComment file contains unix EOL. I suggest to make new  JavaDocCommentMac.java file with MAC EOL.

**Comment by surli** [comment]
> I afraid that this PR destroyed existing test testJavaDocCommentOnUnix which expects that JavaDocComment file contains unix EOL

Actually I kept your own file and copy it in resources after changing the new line character. So I don't think so :)

**Comment by pvojtechovsky** [comment]
The ok, thanks for explanation ;-)

**Pull request merged**
