### PR TITLE
feat: CtPackageDeclaration

### PR DESCRIPTION
**Pull request by pvojtechovsky**
This is new Spoon model element, which represents package declaration - the line at top of compilation unit. Example:
```java
package your.nice.package.name;
...
```
It is needed to complete #2702 ... and at the sniper mode of compilation unit header.

Actually it is not used in CompilationUnit. I plan to add it to compilation unit in PR #2702, which changes CompilationUnit a lot so it makes no sense to add it now.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
needs merge of #2706 first to pass tests

**Comment by pvojtechovsky** [comment]
I rebased on master. Now the test should pass. It is ready for review.

**Comment by monperrus** [comment]
LGTM. We need the corresponding tests to specify this new metamodel concept.

**Comment by pvojtechovsky** [comment]
I made this PR as a minimal baby step, which adds new metamodel element, which is needed by already big enough #2702

**Comment by monperrus** [comment]
Can we create the node in JDTTreeBuilder in this PR? Then we can test the presence of the node and
the pretty-printing.

**Comment by pvojtechovsky** [comment]
It makes this PR more complicated ... (less baby)
* I have to modify CompilationUnit and to add there code, which will be again removed in #2707 ... so it is wasting of effort.
* I have to learn and modify JDTTreeBuilder (so I would need more time for that) - I would like to have it as the last step - first we need a model and then we can fill it in and use it.

... therefore less compatible with #2707, which is the main purpose of this PR.

**Pull request merged**
