### PR TITLE
fix: fragments can be computed for IntersectionTypeReference and used in sniper

### PR DESCRIPTION
**Pull request by woutersmeenk**
See #3224

### CODE REVIEW

**Comment by moraispgsi** [comment]
Also having this issue. Looking forward for this fix.

**Comment by monperrus** [comment]
Bug fixed. The problem was that IntersectionTypeReferences had no position.

**Comment by nharrand** [comment]
LGTM!

**Comment by monperrus** [comment]
Thanks Nicolas!

**Pull request merged**
