### PR TITLE
doc: Remove incorrect Maven usage of spoon-control-flow

### PR DESCRIPTION
**Pull request by LakshyAAAgrawal**

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks! Since the two changes are very different in nature, would you split them in two PRs?

**Comment by monperrus** [comment]
Thanks a lot @LakshyAAAgrawal

**Comment by monperrus** [comment]
For the record, should you be ready to create another PR, the FAQ suggestion is

>  What does launcher.prettyprint() do?It returns void, although I expected it to return a String representation of the model.
```launcher.prettyprint``` prints the model (could be transformed or not) in an output directory which one can set up with ```launcher.setSourceOutputDirectory()``` (there is a default one too). If you want the output in the STDOUT, use toString method defined for every CtElement. It will first get the prettyprinter from the environment and return the result.
Source: https://github.com/INRIA/spoon/issues/4274

**Comment by LakshyAAAgrawal** [comment]
Thanks a lot @monperrus and sorry for the late response, I had been away for the past few days. I will create another PR.

**Pull request merged**
