### PR TITLE
Add quiet switch

### PR DESCRIPTION
**Pull request by diorcety**
Add quiet switch when output messages (incomplet sources for example) are too verbose

### CODE REVIEW

**Comment by GerardPaligot** [comment]
We'll talk about this new feature at the next merge session to know if you want this feature or not.

Thanks for you PR!

**Comment by monperrus** [comment]
Hi @diorcety, 

instead of having multiple boolean switches (verbose, quiet), whose interactions are often hard to understand if not counter intuitive, I propose transform the "verbose" item into an enum with for instance:
QUIET: absolutely nothing on standard output, even in case of errors
ERROR: outputs something only in case of non recoverable errors
INFO: displays information about the Spoon process
WARNING: displays warnings
DEBUG: maximal level of output for debug

In command-line, this would read:

   spoon -v QUIET -i ...
   spoon -v INFO,WARNING  -i ...

what do you think?

**Comment by diorcety** [comment]
i agree

**Comment by GerardPaligot** [comment]
@diorcety Do you want make it yourself or you prefer a PR on your branch?

**Comment by diorcety** [comment]
I will off for one week. So please go for it with a new PR i will close mine at the right time.

**Pull request closed without merging**
