### PR TITLE
Feat: add notNullable property for processor properties

### PR DESCRIPTION
**Pull request by MartinWitt**
See #3339 for discussion why. I would add a simple boolean field to the property annotation because:
- Change the null to a nullObject like in SourcePosition would be backwards breaking
- Doesn't pollute the namespace with a new method.

Maybe a open issue issue is where to document it? 

Edit: need to fix git sry
Edit2: git fixed

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the proposal.

The idea is interesting, but it does not make the log more useful.

I would propose to invert the annotation nullable -> notNullable.

If notNullable==true and properti is null we throw a SpoonException.

WDYT?

**Comment by monperrus** [comment]
ping @vmassol

**Comment by vmassol** [comment]
I think it's not the role of the spoon framework to handle that and that's the jib of the Processor to tell what it needs and to report when it doesn't get what it needs to work.

**Comment by MartinWitt** [comment]
@monperrus but wouldn't your change break the old behavior? If a user updates and gets your version, he could get exceptions for code working before. 
Is this "issue" so important, that you would throw away backwards compatibility?

@vmassol Your message reads like you would remove the log message completely, would the proposed change still fit your needs?

**Comment by vmassol** [comment]
> @vmassol Your message reads like you would remove the log message completely,

Yes I'd remove it completely and let the processor do the validation.

>  would the proposed change still fit your needs?

Sure.

**Comment by monperrus** [comment]
> @monperrus but wouldn't your change break the old behavior?

No, it's fully backward compatible if properties are still nullable by default.

**Comment by MartinWitt** [comment]
Changed nullable -> notNullable and added the SpoonException. Should we still write into the log, even if there is a exception thrown?

**Comment by monperrus** [comment]
Great.

> Should we still write into the log, even if there is a exception thrown?

no

could you add the `//contract ` line in each test?

with that, we'll go towards merge

thanks!

**Comment by MartinWitt** [comment]
github seems to have some problems, but the CI looks green.

**Pull request merged**
