### PR TITLE
feature(CtElement): add a method to get direct children of an element

### LINKED ISSUE #2902: question: how to get descendants with the same parent by Breadth-First-Search
## WANT
 get descendants with the same parent

## Implement
get something like `CtElement#descendantIterator()` to filter descendants with parent. Since `CtElement#descendantIterator()` seems to be DFS, it is not effective when the tree is too deep. **Has any approach fulfilling my need existed?**

### PR DESCRIPTION
**Pull request by nharrand**
fix #2902

### CODE REVIEW

**Comment by monperrus** [comment]
add a test?

**Comment by monperrus** [comment]
and some documentation in "AST traversal"?

Thanks!

**Comment by nharrand** [comment]
Shall we rename this method `getDirectChildren()` to avoid confusion?

**Comment by monperrus** [comment]
LGTM

**Pull request merged**
