### PR TITLE
test(field): Specify what is a field++ and ++field.

### LINKED ISSUE #482: Specify what is a field++

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #482

### CODE REVIEW

**Comment by monperrus** [comment]
we have a problem in the model, i++ is both a read and a write

**Comment by GerardPaligot** [comment]
> we have a problem in the model, i++ is both a read and a write

The actual specification seems good for me and is used like this since the beginning of the project.

**Comment by GerardPaligot** [comment]
Adds documentation in javadoc of `CtFieldRead/Write`, `CtVariableRead/Write`, `CtArrayRead/Write`.

**Comment by GerardPaligot** [comment]
@monperrus PR ok.

**Pull request merged**
