### PR TITLE
test: Migrate AstCheckerTest to Junit5

### PR DESCRIPTION
**Pull request by Rohitesh-Kumar-Jain**
#3919

This PR just migrates AstCheckerTest to Junit5, pure refactoring.

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
Hi migrating AstCheckerTest to Junit5 involved only 2 changes, I was wondering that should I raise PRs that are this small 😅, or should prioritize bigger tests first instead of going sequentially?

**Comment by slarse** [comment]
@Rohitesh-Kumar-Jain Yes, your recent changes have made it clear that these migrations are pretty tiny. Let's try to bunch them up a bit.

Let's try something semi-extreme: try to migrate every test class in the the `spoon.reflect` that does not require any extensive changes (i.e. at most swap the order of arguments to some assertion).

**Review by slarse — APPROVED** [review]
This one is also fine.

**Comment by Rohitesh-Kumar-Jain** [comment]
> @Rohitesh-Kumar-Jain Yes, your recent changes have made it clear that these migrations are pretty tiny. Let's try to bunch them up a bit.
> 
> Let's try something semi-extreme: try to migrate every test class in the the `spoon.reflect` that does not require any extensive changes (i.e. at most swap the order of arguments to some assertion). Keep going until you've a total of ~100 changes (insertions + deletions).

Yes, this seems a good idea and for the test involving many changes, I will raise PRs for them separately.

**Pull request merged**
