### PR TITLE
refactor: move VisitorFake.java to testclasses in visitor

### PR DESCRIPTION
**Pull request by zielint0**
I am ready to merge.

### CODE REVIEW

**Comment by surli** [comment]
Is this visitor really used?

**Comment by zielint0** [comment]
No. Checked by full text search / grep.

**Comment by zielint0** [comment]
@surli 
https://github.com/INRIA/spoon/issues/2197

**Comment by monperrus** [comment]
this is not a testclass.

a test class is a java file that is parsed in a Spoon model.

This is a regular test, but not a standard one. The test is itself done by the compiler, see comment in the class: `the compiler ensures that we have correctly defined all visit method in CtAbstractVisitor`

**Pull request closed without merging**
