### PR TITLE
fix: fix regression in field accesses of static fields

### PR DESCRIPTION
**Pull request by monperrus**
fixing the latest regressions, starting with Moshi https://ci.inria.fr/sos/job/Moshi/

### CODE REVIEW

**Comment by monperrus** [comment]
ready for review.

**Comment by nharrand** [comment]
This may also fix https://ci.inria.fr/sos/job/Bukkit/ as far as I understand.

**Comment by nharrand** [comment]
LGTM. I'll merge if CI is happy.

**Comment by monperrus** [comment]
Thanks. The fix is successful: https://ci.inria.fr/sos/job/Moshi/1112/

**Comment by nharrand** [comment]
Is also fixed https://ci.inria.fr/sos/job/Commons-codec/

**Pull request merged**
