### PR TITLE
Add test for https://github.com/INRIA/spoon/issues/3206

### PR DESCRIPTION
**Pull request by woutersmeenk**
Testcase for #3206

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot for the failing test.

**Comment by monperrus** [comment]
working on it, it's tough

**Comment by monperrus** [comment]
#3215 is a fix. let's cool it down.

**Comment by monperrus** [comment]
Thanks again for the great failing test case. Will next look at #3205

**Comment by woutersmeenk** [comment]
Thanks for the quick response!

**Pull request closed without merging**
