### PR TITLE
review: feat: Add Environment#setFactory

### PR DESCRIPTION
**Pull request by surli**
Add a setFactory method to environment and set it when calling the main factory constructor with a given environment. 
This allows to use the `getFactory()` of Environment without NPE.

### CODE REVIEW

**Comment by tdurieux** [comment]
Why the environment has a factory?

**Comment by surli** [comment]
> Why the environment has a factory?

Because of the method `getFactory` I assume.
Anyway, I need it to access factory from `DefaultJavaPrettyPrinter` environment.

**Comment by tdurieux** [comment]
My point is the `getFactory` in Environment makes no sense.

Currently, there is no usage of `env.getFactory` In `DefaultJavaPrettyPrinter`.

**Comment by surli** [comment]
> My point is the getFactory in Environment makes no sense.

In that kind of situation: https://github.com/INRIA/spoon/pull/1672/files#diff-5f33bf5d1f38230de815e4c60a67a215 

I consider it cleaner to call `this.env.getFactory()` than `wildcardReference.getFactory()`.

**Comment by tdurieux** [comment]
I do not agree, the Environment is only used for configuration and logging.
They should not be sate in the Environment.

The double reference factory -> Environment; Environment -> Factory is really awful.

I looked where Environment.getFactory is used and it is only in the StandardEnvironment... 
and getFactory can only return null. 
I propose to remove getFactory from the Environment.

**Comment by monperrus** [comment]
I would agree with @tdurieux . The responsibility of Environment is to handle the configuration not the state.

A better solution would be to remove `getFactory` from Environment.

**Comment by surli** [comment]
> The cycle reference Factory -> Environment; Environment -> Factory is really awful.

Agreed! 
Just wanted to use it as it was already there, but I'm ok to remove it :)

**Pull request closed without merging**
