### PR TITLE
bug with generic invocation due to JDT (waiting for JDT fix)

### PR DESCRIPTION
**Pull request by boeserwolf91**
Type mismatch: cannot convert from Integer to double at D:\Programmieren\CubeEngine\spoon\src\test\java\spoon\test\casts\Castings.java:12

However this could be a jdt bug too. I didn't investigate it yet.

Don't merge it accidentally. :smile: The PR just shows a bug and doesn't fix it.

### CODE REVIEW

**Comment by boeserwolf91** [comment]
Maybe I should mention that the bug just occurs with this generic invocation.

invoking the test method with ```test(Integer.valueOf(3))``` or ```test(new Integer(3))``` works fine.

**Comment by GerardPaligot** [comment]
Unfortunately, the bug don't come from Spoon but in JDT and the [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464496) is already reported on their bugtracker.

**Comment by boeserwolf91** [comment]
okay thanks @GerardPaligot 
So this is going to be fixed in a few years (maybe) :smile:

**Comment by GerardPaligot** [comment]
I hope no ... I [up their issue in their bugtracker](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464496#c2).

**Comment by GerardPaligot** [comment]
I create the [issue of this bug](https://github.com/INRIA/spoon/issues/328). This PR can be closed.

**Pull request closed without merging**
