### PR TITLE
checkstyle: AccessTest.java

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by monperrus** [comment]
For space only PRs, we'll accept them once we've activated checkstyle for src/test, see #2611.

So we'll closing this one for now, and you'll reopen it when checkstyle is activated.

**Comment by zielint0** [comment]
I would like it to be merged (to avoid spending time on reopening etc.), and all following PRs with spaces/minor issues would follow when checkstyle is ready :-)

**Comment by zielint0** [comment]
> For space only PRs, we'll accept them once we've activated checkstyle for src/test, see #2611.

BTW. I am working on it.

**Comment by monperrus** [comment]
> BTW. I am working on it.

Good, thanks!

**Pull request closed without merging**
