### PR TITLE
chore(deps): update dependency org.jacoco:jacoco-maven-plugin to version 0.8.9

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
*Beep boop, this action was performed manually.*

 I guess I am cosplaying as renovate now… The release was 3 days ago, maybe renovate would have come around in the future. But this fails the 20-ea CI on other PRs, so we should fix it.

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]
Good bot. 🤖

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
Thanks @I-Al-Istannen. Fast merge because we have some PRs needing this PR.

**Comment by MartinWitt** [comment]
Looks like this crashed the CI https://github.com/INRIA/spoon/actions/runs/4629755815/jobs/8190428284

**Comment by I-Al-Istannen** [comment]
No, it passed when re-running it. This test seems to be flaky instead? That's a quite recent development then, but I noticed that a few times over the last days.

**Pull request merged**
