### PR TITLE
fix: fix invalid if model with empty statements in then/else branch

### PR DESCRIPTION
**Pull request by Egor18**
Hi! I found out that spoon is probably wrong about the following code:

```
if (x);
else System.out.println();
```

It says that `ifElement.getThenStatement()` here is `System.out.println()` and `ifElement.getElseStatement()` is null. But it's incorrect.
Then statement should be null and the else statement should be System.out.println();

This PR provides a failing test case.

### CODE REVIEW

**Comment by monperrus** [comment]
working on this

**Comment by monperrus** [comment]
Thanks a lot for the bug report and the failing test case.

An invalid model is one of most serious bugs we can have.

Fixed!

**Comment by monperrus** [comment]
If you look at the test failures, handling empty statements while remaining fully backward compatible is a challenge :)

Suggestions welcome!

**Comment by pvojtechovsky** [comment]
I will have a look at it now

**Comment by pvojtechovsky** [comment]
Do we want to see Empty statements in Spoon model?
For example this java code
```java
;;;;;;;;;;
```
Should it be represented as
A) no statement
B) 10 empty statements

WDYT?

Current solution which represents empty statement as CtComment with implicit=true and non empty position with source code `;` is breaking some internal concepts like:
* implicit element has no source position

**Comment by pvojtechovsky** [comment]
It seems to me that the cleaner solution is to introduce new element `CtEmptyStatement`. WDTY?

**Comment by Egor18** [comment]
I've just discovered another bug with that kind of code. Spoon (master branch) fails to build a model when encounters the following code:

```
if (true) // comment
    ;
```

```
java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTCommentBuilder$1.visitCtIf(JDTCommentBuilder.java:435)
	at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:45)
	at spoon.reflect.visitor.CtInheritanceScanner.scan(CtInheritanceScanner.java:183)
	at spoon.support.compiler.jdt.JDTCommentBuilder$1.scan(JDTCommentBuilder.java:300)
	at spoon.support.compiler.jdt.JDTCommentBuilder.insertCommentInAST(JDTCommentBuilder.java:498)
	at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:159)
	at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:115)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:446)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:374)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:339)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:122)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:105)
	at spoon.Launcher.buildModel(Launcher.java:767)
	at spoon.Launcher.run(Launcher.java:718)
	at spoon.Launcher.run(Launcher.java:118)
	at spoon.test.comment.CommentTest.getSpoonFactory(CommentTest.java:104)
```

That's because here in JDTCommentBuilder.java if `e.getThenStatement()` is `null`, we will get NPE:
```
public void visitCtIf(CtIf e) {
    if (!(e.getThenStatement() instanceof CtBlock)) {
        if (comment.getPosition().getSourceEnd() <= e.getThenStatement().getPosition().getSourceStart()) {
```

We can simply discard that comment in that case, or probably do something better.

**Comment by pvojtechovsky** [comment]
Hi Egor, thanks for these tests. It shows another reason why we need empty statement ... to be able to link comment to some entity.

I have found that `CtElement extends CtStatement`, but it is quite wild concept from my point of view, which cannot be used to describe something like:
```java
/*a*/;/*b*/;
```

**Comment by monperrus** [comment]
> Do we want to see Empty statements in Spoon model?

I would say no. One core design principle of Spoon is to abstract over syntax, and empty statements are purely syntactic.

I propose to fix this bug and the comment one in two different PRs.
@pvojtechovsky could you create an issue with the comment bug?

However, we can have temporary empty statements. In this particular bug, we need a fake node just for the exiter, and we can remove it afterwards. This is the best solution I see so far.

WDYT?

**Comment by pvojtechovsky** [comment]
> One core design principle of Spoon is to abstract over syntax, 

I like that design principle a lot. It allows powerful Patterns, Matchers, ... etc. 

> and empty statements are purely syntactic.

I am not sure here.

I agree that
```java
print();;;
```
should be simplified to 
```java
print();
```
by Spoon. Nobody wants to analyze empty statements.

But 
```java
if (x) ;
then print();
```
is may be something else. If we represent it as **empty implicit CtBlock**, then it is not consistent, because we have no AST node which represents that statement `;`... it will probably cause problems in sniper printer, because it expectes that implicit elements has no source code ... The nicer and may be better for analyze it would be to have implicit CtBlock with one `CtEmptyStatement` in it. I do not know. I never needed to analyze something like that ;-)

@Egor18 WDYT? What would you expect in your use case? Could you describe your use case of these empty statements so we can fix it best way?

**Comment by Egor18** [comment]
@pvojtechovsky, I was trying to run Spoon over the [spotbugs](https://github.com/spotbugs/spotbugs) tests, just to see if it's ok with some tricky code like this one, and unfortunately, the model build failed.

From my point of view, the best possible solution is just to fix that case only (return null for the then part). 
A new `CtEmptyStatement` or implicit `CtBlock` in that would break backward compatibility. 
For example, in our analyzer I have the code, which relies on the fact that `ifElement.getThenStatement() == null`, to detect suspicious code like that (odd semicolon after if):
```
if (cond);
{
  /* ... */
}
```
It's not a big deal to change that code, but all the users would have to do that.

Regarding the comment: `if (cond) /* comment */ ;`
I believe we can simply attach it to the whole CtIfStatement (it's a rare and strange case anyway).

**Comment by pvojtechovsky** [comment]
ok, thanks for feedback. I will do it like you suggest.

**Comment by monperrus** [comment]
> I agree that
>
> print();;;
>
> should be simplified to
>
> print();
Good, I also agree.

> If we represent it as *empty implicit CtBlock*, then it is not consistent, because we have no AST
> node which represents that statement
This is the current definition of an implicit node in Spoon: something in the model that is not in
the source.

WDYT?

**Comment by pvojtechovsky** [comment]
Looks like all tests passed. It is ready for review.

**Comment by monperrus** [comment]
really elegant! I will merge.

**Comment by pvojtechovsky** [comment]
Thanks for compliment :-)

**Pull request merged**
