### PR TITLE
fix: Qualified name in catch clause resolved incorrectly (noclasspath)

### LINKED ISSUE #3372: bug: Qualified type references in catch clauses resolved incorrectly (noclasspath)
I have a problem in noclasspath mode where a qualified type reference in catch clauses are resolved incorrectly. Take the following code snippet.

```java
public class CatchQualifiedReference {
    public static void main(String[] args) {
        try {
        } catch (some.neat.pkg.CustomException e) {
        }
    }
}
```
In noclasspath mode, `some.neat.pkg.CustomException` becomes a type references with the qualified name `some`. Which is pretty wild. The problem appears to be that `TypeBinding.readableName()` actually returns just `some` here:

https://github.com/INRIA/spoon/blob/3a8d04df7cb0319896ae98b08986a7006b208fa6/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L961

So this could be a problem with the JDT library rather than with Spoon. I'm not certain. I'll put up a PR with a test case, but I haven't had the time to look into a solution.

### PR DESCRIPTION
**Pull request by slarse**
This is a test case to reproduce #3372 

I haven't yet had the time to look into solutions.

update fixes #3372

### CODE REVIEW

**Comment by slarse** [comment]
It appears as if using the closest match (if available from `TypeBinding.closestMatch()`) at least lets you resolve the correct readable name. I'll try some stuff with that.

**Comment by MartinWitt** [comment]
Hi,
if you mark your test with @Ignore("UnresolvedBug") the CI will check that the test fails and be green afterwards.

**Comment by slarse** [comment]
Hi!

Based on the contributing guidelines, I thought that was supposed to be used if you want to submit just a failing test case? I intend to try to solve this problem, I just haven't had the time to look into it yet.

**Comment by monperrus** [comment]
just pushed a fix, let's wait for CI

**Comment by slarse** [comment]
@monperrus Looks like it solved the problem? CI failure seems unrelated.

**Comment by monperrus** [comment]
unwip-ed, @nharrand ping

**Pull request merged**
