### PR TITLE
Use Java 8 functional interfaces for filtering model elements.

### PR DESCRIPTION
**Pull request by seintur**

### CODE REVIEW

**Comment by boeserwolf91** [comment]
:-1: for this.For me this change is not worth to set the language level to java 8. I prefer the java version 6.

**Comment by pschichtel** [comment]
:-1: from me too. I'd say that's better done in an extra java8 support module

**Comment by GerardPaligot** [comment]
I agree with @boeserwolf91 and @pschichtel. It seems overkill to upgrade java version support from 1.6 to 1.8 just to have a beautiful syntax with filters in spoon.

**Comment by seintur** [comment]
No problem guys, Time is on my side ;-)

**Pull request closed without merging**
