### PR TITLE
WIP: setImplicit applied to arguments and component types for type references

### PR DESCRIPTION
**Pull request by oscarlvp**
Changes concerning #2872

### CODE REVIEW

**Comment by monperrus** [comment]
LGTM. Could you add a test case to specify this new behavior?  Thanks!

**Comment by monperrus** [comment]
ping @oscarlvp

**Comment by pvojtechovsky** [comment]
I would say it is not always correct to mark all children non implicit. For example in code like:
```java
List<>
//internally there is where Object typeRef is implicit
List<Object>
```
Now if you call setImplicit(true) on that List, then all is implicit - OK
The you call setImplicit(false) on that List, then all is NOT implicit, 
```java
List<Object>
```
but what if client wants to again
```java
List<>
```
I agree with @surli that calling of setImplicit(false) with recursive algorithm is risky and some clients might expect different behavior - sometime recursive and sometime not recursive.
It seems to me like the call of setImplicit(true) can be recursive always.
WDYT?

**Comment by monperrus** [comment]
closing the stalled PR, thanks Oscar for the suggestion!

**Pull request closed without merging**
