### PR TITLE
fix: handle special cases in CtAnnotationType

### PR DESCRIPTION
**Pull request by Charmik**
I added tests from discussion:
https://github.com/INRIA/spoon/issues/2946

1 test passes and the second one fails with exception. I can fix tests and commit them after your fix.
I am not sure that I put them in the right place, by the way.

### CODE REVIEW

**Comment by monperrus** [comment]
The bug comes from JDT :-(, it does not call `visit(AnnotationMethodDeclaration, ClassScope` but `visit(MethodDeclaration, ClassScope)`

Just pushed a workaround here.

WDYT?

**Comment by Charmik** [comment]
> The bug comes from JDT :-(, it does not call `visit(AnnotationMethodDeclaration, ClassScope` but `visit(MethodDeclaration, ClassScope)`
> 
> Just pushed a workaround here.
> 
> WDYT?

seems okay for me!
can we merge it to master?
did you create bug in JDT repository? I think better to do it;)
your build seems failed, by the way.

**Comment by Charmik** [comment]
> The bug comes from JDT :-(, it does not call `visit(AnnotationMethodDeclaration, ClassScope` but `visit(MethodDeclaration, ClassScope)`
> 
> Just pushed a workaround here.
> 
> WDYT?

by the way your condition 
`&& (type instanceof CtAnnotationType)`
doesn't make sense, because at the start there is `if` 
`!(child instanceof CtTypeParameter)` and `return`

so this condition is always true, so you can remove it.

**Comment by monperrus** [comment]
The previous implementation and fix made too many assumptions on the type of methods.

Here is a better fix for which all test cases pass.

@nharrand WDYT? Merge?

**Pull request merged**
