### PR TITLE
chore: improve CI logs with test case names

### PR DESCRIPTION
**Pull request by monperrus**
Goal: we want to have the list of all executed test cases in the CI log.

Bonus: this gives us execution time in the logs for performance analysis

### CODE REVIEW

**Comment by MartinWitt** [comment]
Have you thought about using https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/TestExecutionListener.html or https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/listeners/LoggingListener.html?

**Comment by monperrus** [comment]
yes, if you want help out in this more elegant way, please free to push on this branch :) that would 
be awesome!

**Comment by MartinWitt** [comment]
I have created an initial implementation, does this fit your wanted features?

**Comment by monperrus** [comment]
Waooow, it's super cool! It works perfectly.

Thanks a lot @MartinWitt will merge.

**Comment by monperrus** [comment]
thanks a lot for doing this valuable work @MartinWitt

**Pull request merged**
