### PR TITLE
review: fix(pattern): ForEachNode#replaceNode

### PR DESCRIPTION
**Pull request by pvojtechovsky**

### CODE REVIEW

**Comment by zielint0** [comment]
Cann't -> Cannot

**Comment by pvojtechovsky** [comment]
Tomasz pointed at this problem in another PR, so I noticed that there is wrong code here. This PR contains a fix, but I do not know how to test it. The test would have to 
1) define a pattern parameter
2) to use it as inline forEach 
3) to replace that parameter again
... does this use case makes sense? Hard to say...

**Comment by zielint0** [comment]
Thank you for deeper inspection than in my PR :)

**Comment by surli** [comment]
I'm ok to merge it without a test: but can you at least add some comments on the method to explain that specific situation?

**Comment by surli** [comment]
Apparently you broke the checkstyle when pasting the comment I think. Could you fix it?

**Pull request merged**
