### PR TITLE
Fix NPE with properties directory is empty

### PR DESCRIPTION
**Pull request by diorcety**
getXmlRootFolder().listFiles() can return null
which will cause an NPE in the for loop

### CODE REVIEW

**Comment by GerardPaligot** [comment]
Can you add a test case for this PR?

Thanks in advance!

**Comment by diorcety** [comment]
Done. Sorry i'm a lazy guy :)

**Comment by diorcety** [comment]
it's not empty. But non existing directory

**Comment by monperrus** [comment]
Thanks a lot for the contribution!

**Pull request merged**
