### PR TITLE
refactor: remove CtParameterReferenceImpl#declaringExecutable

### PR DESCRIPTION
**Pull request by monperrus**
By analyzing #1869, I realize that `CtParameterReference` and `CtParameterReferenceImpl` are badly designed. The problem is that `CtParameterReference` is stateful with a superfluous pointer to an executable reference:

- this goes against the design of philosophy of Spoon references that are mean to be resolved dynamically (instead of hard-wired links)
- when a parameter reference is moved in a transformation (eg from one variable to another), the result of `getDeclaration()`, done with dynamic lookup, can become inconsistent with the result of `getDeclaringExecutable()`
- when a parameter reference is cloned, the result of `getDeclaration()`, done with dynamic lookup is correct (see https://github.com/INRIA/spoon/issues/1869#issuecomment-366798381), yet inconsistent with the result of `getDeclaringExecutable()`, which is not changed during cloning. This is one facet of the problem discussed in #1869.

The solution presented here it to remove the `get/setDeclaringExecutable` from interface `CtParameterReference`, and to remove the corresponding state in the implementation (field `declaringExecutable`).

This fixes the three problems described above. There are a few test changes, which are minor, they were simply directly unit-testing `get/setDeclaringExecutable`.

Once this one is merged, there will be other PRs for #1869.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
I agree that field `CtParameterReferenceImpl#executable` should be removed.

But would it be possible to KEEP `CtParameterReference[Impl]#getDeclaringExecutable()` ?? May be we can mark it @Derived and compute it's value from the Spoon model?

**Comment by monperrus** [comment]
you're right. it's better for backward compatibility. done.

**Comment by pvojtechovsky** [comment]
Looks good to me. @monperrus are you done with this PR? Do you want to merge it soon (tomorrow morning) or should we wait for feedback of others here?

**Comment by monperrus** [comment]
OK to merge.

**Pull request merged**
