### PR TITLE
bug: test to reproduce the error with wildcards

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by monperrus** [comment]
@pvojtechovsky you touched the imports recently, would you have a look at this one?

**Comment by pvojtechovsky** [comment]
I will have a look

**Comment by pvojtechovsky** [comment]
I rebased this new test to #2683 and it passes well. So I do not want to try to fix it using old import code, which I would like to get rid.

**Comment by monperrus** [comment]
OK. Let's finish #2683 then.

**Pull request closed without merging**
