### PR TITLE
fix: ClassTypingContext#isSameSignature for generic methods

### PR DESCRIPTION
**Pull request by pvojtechovsky**
The method with this declaration
```java
<U> void visitCtConditional(final CtConditional<U> conditional)
```
defined in class and inteface returned false for ClassTypingContext#isSameSignature(methodFromIface, methodFromClass).

### CODE REVIEW

**Comment by monperrus** [comment]
Indeed, there is a bug, thanks.

However, this bug fix is super hard to review because there are too many changes in the test. 

The reason is that the test data (test classes and methods in this case) is changed (and not only added).

It's better to keep the same test classes/methods, and only add new ones to demonstrate the bug. Doing that, there is mostly new content in tests (as opposed to modified content), and at most a few well documented changed assertions (if the incorrect behavior was already specified and enforced).

**Comment by pvojtechovsky** [comment]
You are right. Now I did only minimum changes in existing test - because of change of useless hard to implement API method.
I also added new small test to reproduce problem.

**Comment by pvojtechovsky** [comment]
I am done here

**Comment by monperrus** [comment]
thanks Pavel

**Pull request merged**
