### PR TITLE
refactor: adopt jspecify

### PR DESCRIPTION
**Pull request by tenax66**
This is a pull request for issue #5320 .

- add the dependency for `jspecify`.
- applied the `@Nullable` annotation to several packages as a first step:`spoon`, `spoon.compiler`, `spoon.metamodel` and `spoon.pattern.internal`.

Note: This pull request does not include checks for annotations. We may use [jspecify-reference-checker](https://github.com/jspecify/jspecify-reference-checker) in the future.

### CODE REVIEW

**Comment by tenax66** [comment]
When annotating a return type of a method by jspecify's `@Nullable`, it should look like this.
```java
public @Nullable String foo() {
  return ""
}
```
That is to say, the annotation is applied directly to the return type.

But this does not pass Qodana's checks (MissortedModifiers).

**Comment by SirYwell** [comment]
> When annotating a return type of a method by jspecify's `@Nullable`, it should look like this.
> 
> ```java
> public @Nullable String foo() {
>   return ""
> }
> ```
> 
> That is to say, the annotation is applied directly to the return type.
> 
> But annotations in that position don't pass Qodana's checks (MissortedModifiers).

This is configurable in IntelliJ, but I don't know if/how it can be configured using the `qodana.yaml`. @MartinWitt maybe you know more about that?

**Comment by MartinWitt** [comment]
Hey,

The current qodana config does not allow this directly, but you could try
adding the .idea config file to the repo after changing the seting in IJ.
If this does not work disabling the rule with a comment why ist also fine
for me.
Otherwise great progress.

Hannes Greule ***@***.***> schrieb am So., 13. Aug. 2023,
09:49:

**Comment by tenax66** [comment]
> you could try adding the   `.idea` config file to the repo after changing the setting in IJ.
> If this does not work, disabling the rule with a comment why is also fine for me. 

I tried the latter, as I could not find any information that the `.idea` folder can modify qodana's CI settings.

**Comment by MartinWitt** [comment]
@SirYwell can you provide the config file with the changed IJ setting?

**Comment by I-Al-Istannen** [comment]
Okay, I give up. It seems to work locally, but what do I know. Let's disable that modifier.

**Comment by MartinWitt** [comment]
@I-Al-Istannen so we merge and fix this at a later stage?

**Comment by MartinWitt** [comment]
Thanks @tenax66 for your work.

**Pull request merged**
