### PR TITLE
Remove useless test case

### PR DESCRIPTION
**Pull request by duribreux**
This test doesn't test anything - @GerardPaligot

### CODE REVIEW

**Comment by GerardPaligot** [comment]
This test come from [this commit](https://github.com/duribreux/spoon/commit/f57cd71363273703a8b31364fb206eb50df75f4e). It isn't useless but just not finished.

A better contribution could be to add the missing asserts: clone the local variable and add these asserts:

```diff
+ assertEquals(localVarRef.getDeclaration(), declaration);
+ assertTrue(localVarRef.getDeclaration() == declaration);
+ assertEquals(localVarRefCloned.getDeclaration(), declarationCloned);
+ assertTrue(localVarRefCloned.getDeclaration() == declarationCloned);
```

**Comment by duribreux** [comment]
I improved the test based on your comment and I "probably" found a bug.
I seems that the `parent` of `localVarRef` is `null` and `getDeclaration()` needs it.

I don't have time to dig into Spoon to understand what's happening :/

**Comment by GerardPaligot** [comment]
Someone made shit recently. :-°

**Comment by monperrus** [comment]
> Someone made shit recently. :-°

It's not appropriate to say this.

It's called a regression on a untested case.

**Comment by monperrus** [comment]
closed by #888 

Thanks @duribreux , it starts with a System.out, it ends with a bug.

**Pull request closed without merging**
