### PR TITLE
refactor(getActualClass): Improve design and reability

### PR DESCRIPTION
**Pull request by MartinWitt**
This PR tries to remove some old code and improve the code style. The method has the same behavior as before, but doesn’t need to build a model for array types anymore. In a feature PR there should be an enum for primitive types, but this is out of scope for this PR.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks @MartinWitt. It seems that handling concurrency is the main goal here, right?

**Comment by MartinWitt** [comment]
The main goal was to remove the `Launcher.parseClass` call, but because I was already refactoring the code, I fixed the rest also.

**Comment by monperrus** [comment]
The diff is hard to decipher, but it is overall OK, plus it is code much executed by the test suite which is green.

OK to merge.

Next time, it'd be great to split in smaller and clearer PR :)

**Comment by monperrus** [comment]
thanks @MartinWitt

**Pull request merged**
