### PR TITLE
sonarqube: make field local in MavenLauncher.java

### PR DESCRIPTION
**Pull request by zielint0**
Fix SonarQube: *Remove the "model" field and declare it as a local variable in the relevant methods.*

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
@nharrand is that OK for you? Should not we add getter instead? WDYT?

**Comment by pvojtechovsky** [comment]
> I would rather have a getter, or make it protected. I think it make sense to keep the information from the pom in a MavenLauncher instance.

I think so.
@nharrand, will you make a PR for that?

@zielint0 I suggest to close this one, OK?

**Comment by nharrand** [comment]
Yes sure!

**Comment by zielint0** [comment]
Thank you for clarification guys!

**Pull request closed without merging**
