### PR TITLE
test(DefaultPrettyPrinter): Check that DefaultPrettyPrinter is checkstyle compliant

### PR DESCRIPTION
**Pull request by nharrand**
Related to #3623 .

This test check that spoon sources parsed by spoon and pretty printed with the DefaultPrettyPrinter passes the rules from `checkstyle.xml`. 

Note that it is simple to define a different rule set if we want to.

This test is probably not meant to be run with the rest of unit tests (too slow) but can help to isolate more precise violations.

Output:

```
Violations: 
V: [WhitespaceAfter] -> 77
   Ex: src/main/java/spoon/testing/utils/ModelUtils.java:23:59:
V: [NoWhitespaceBefore] -> 99
   Ex: src/main/java/spoon/support/gui/SpoonModelTree.java:9:94:
V: [RightCurly] -> 2
   Ex: src/main/java/spoon/metamodel/MetamodelProperty.java:391:17:
V: [ParenPad] -> 167
   Ex: src/main/java/spoon/refactoring/MethodInvocationSearch.java:38:37:
V: [WhitespaceAround] -> 61
   Ex: src/main/java/spoon/refactoring/CtParameterRemoveRefactoring.java:149:17:
V: [RegexpSingleline] -> 230
   Ex: src/main/java/spoon/refactoring/CtDeprecatedRefactoring.java:71:
V: [RegexpSinglelineJava] -> 57432
   Ex:src/main/java/spoon/SpoonAPI.java:13:
V: [NewlineAtEndOfFile] -> 661
   Ex: src/main/java/spoon/SpoonAPI.java:1:
V: [UnusedImports] -> 1
   Ex: src/main/java/spoon/refactoring/CtDeprecatedRefactoring.java:13:8:
```

### CODE REVIEW

**Comment by monperrus** [comment]
nice! ready to merge?

**Comment by nharrand** [comment]
Sure! Go ahead.

**Comment by monperrus** [comment]
Could you add in the test an explanation of the intention and why it is ignored? Thanks!

**Comment by nharrand** [comment]
Hope it is more clear now!

**Comment by monperrus** [comment]
Thanks a lot!

**Pull request merged**
