### PR TITLE
fix: relax intercession test to fit #2615 - new fluent API return types

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Relax contract of IntercessionTest#testSettersAreAllGood so the new Spoon API (e.g. #2702) can be made in correct way.

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
@monperrus @surli could you please review and merge this one, so #2707 becomes green and we can discuss it as next bapy step?

**Comment by surli** [comment]
LGTM. WDYT @monperrus ?

**Comment by surli** [comment]
LGTM. WDYT @monperrus ?

**Comment by surli** [comment]
LGTM. WDYT @monperrus ?

**Comment by surli** [comment]
LGTM. WDYT @monperrus ?

**Pull request merged**
