### PR TITLE
WIP: Bugs and TODOs of Templates and TemplateMatcher

### PR DESCRIPTION
**Pull request by pvojtechovsky**
This PR marks (by javadoc) all the problems I have found during learning of Template and TemplateMatcher related code.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks. The next 21 PRs :)

**Comment by surli** [comment]
@pvojtechovsky is this one still useful? Have you finished?

**Comment by pvojtechovsky** [comment]
Yes, it is still useful. It points to all the problems of TemplateMatcher. I want to fix them, by I have only little time, so I expect to have it finished in 2-3 months...

**Comment by surli** [comment]
> Yes, it is still useful. It points to all the problems of TemplateMatcher. I want to fix them, by I have only little time, so I expect to have it finished in 2-3 months...

No problem, I just wanted to be sure it's still open issues :)

**Comment by pvojtechovsky** [comment]
These problems will be solved in #1686. Closing this one

**Pull request closed without merging**
