### PR TITLE
new(tool): new Spoon AST visualisation tool

### PR DESCRIPTION
**Pull request by arnobl**
A new Spoon AST visualisation tool, as discussed in #3071

Requires a JDK 11, so I am not sure it can be built with the rest of the tool suite.

### CODE REVIEW

**Comment by monperrus** [comment]
Super cool, thanks a lot! Could you set up Travis for compiling and testing it?

**Comment by arnobl** [comment]
The Travis instance seem to have issues : `Timeout waiting for network availability.`

**Comment by arnobl** [comment]
It finally builds

**Comment by monperrus** [comment]
great, thanks a lot!

LGTM (+made small changes in doc)

**Comment by nharrand** [comment]
LGTM too.
Thanks for the contribution!

**Comment by monperrus** [comment]
Thanks a lot @arnobl that's a really cool contribution!

**Comment by monperrus** [comment]
Maybe we could mention it on the website, with a pull-request on the `doc` folder.

**Comment by arnobl** [comment]
> Maybe we could mention it on the website, with a pull-request on the `doc` folder.

Sure. But I do not have time this week to do that.

**Comment by arnobl** [comment]
Do not hesitate to poke me on issues or feature requests of this tool.

**Pull request merged**
