### PR TITLE
fix: comment of CtAnnotation value

### LINKED ISSUE #2209: bug: comment not attached to element (error message in log)
I see the following stack trace in the logs:
```
2018-07-12 17:41:16,176 ERROR spoon.support.compiler.jdt.JDTCommentBuilder - // prevent users from disabling is not added into the AST
spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for class spoon.support.reflect.code.CtCommentImpl (/Users/urli/Github/runelite/runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java:46)
	at spoon.support.reflect.declaration.CtElementImpl.getParent(CtElementImpl.java:365)
	at spoon.support.compiler.jdt.JDTCommentBuilder.insertCommentInAST(JDTCommentBuilder.java:485)
	at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:156)
	at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:112)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:480)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:391)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:129)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.Launcher.buildModel(Launcher.java:769)
	at Main.main(Main.java:10)
```

Reproduction steps:
```
git clone https://github.com/runelite/runelite
git checkout runelite-parent-1.4.7
cd runelite/runelite-client
mvn dependency:build-classpath
```

```java
Launcher launcher = new Launcher();
        launcher.addInputResource("runelite/runelite-client/src/main/java");
        launcher.getEnvironment().setSourceClasspath(CLASSPATH.split(":"));
        CtModel model = launcher.buildModel();
```

### PR DESCRIPTION
**Pull request by monperrus**
fix #2209 

Note that it's a partial fix, the comment should be added to the expression inside the annotation, but it's still much better than the dirty exception in logs of before.

### CODE REVIEW

**Comment by tdurieux** [comment]
It is not a fix, you basically remove the log. 

I strongly disagree with this solution.

This log is designed to detect thoses cases.

**Comment by monperrus** [comment]
It's not only removing the log, the comment is attached to an element, so there is a new best-effort behavior.

Are you against this best-effort behavior?

**Comment by tdurieux** [comment]
I'm against this one because from my experience the computed parent of comment can be pretty far from an acceptable target.

And also because you removed the only way to detect those buggy case. From my point of view, this log is one of the best logs you can have. When this log is printed it means that there is a bug in the application.
With your changes, you completely remove the ability to detect unhandled cases, and the only argument you used was to make the logs nicer when a bug is present.

The solution is to fix the bug that the log you want to remove detected.

**Comment by monperrus** [comment]
I see what you mean. I've deleted the best effort idea and restored the log.

I've isolated the problem in a failing test case, could you have a look at it? Thanks!

**Comment by monperrus** [comment]
@pvojtechovsky could you have a look at this one?

**Comment by pvojtechovsky** [comment]
ok, I will have a look

**Comment by monperrus** [comment]
Many thanks Pavel!

**Comment by pvojtechovsky** [comment]
You are welcome Martin ;-)

**Pull request merged**
