### PR TITLE
release  Spoon 9.1.0

### PR DESCRIPTION
**Pull request by monperrus**
# New features

* Add mode ignore-syntax-errors. (PR: #4054)
* Add API method CtAbstractSwitch.addCaseAt. (PR: #4015)
* Add OFF log level to StandardEnvironment. (PR: #3904)
* Add CtFormalTypeDeclarer.addFormalCtTypeParameterAt. (PR: #3896)
* Add CtExecutable.addParameterAt. (PR: #3902)
* Add CtAbstractInvocation.addArgumentAt method. (PR: #3885)

# Bug fixes

* noclasspath: Handle type resolution of anonymous class with unresolved constructor. (PR: #3971)
* spoon-control-flow: Fix disconnected graphs for switch statements. (PR: #4004)
* spoon-visualiser: Bump Interacto to use the latest version on Central. (PR: #3861)
* Fix type parameter contract of setParent. (PR: #4099)
* Make lambda type implicit to avoid auto-importing type targeted in lambda. (PR: #4093)
* Fix sniper bug delated to source position of super reference. (PR: #4092)
* Fix the insertion order for CtStatementListImpl.insertBegin. (PR: #4065)
* Get correct descriptions from CtJavaDocImpl. (PR: #4061)
* Fix compliance level support for old code. (PR: #4068)
* Set correct names to modules in JDTBatchCompiler. (PR: #4073)
* Fix the insertion order for CtCaseImpl.insertBegin. (PR: #4063)
* Fix equality for CtCodeSnippet. (PR: #4024)
* Simplify code using Map.computeIfAbsent. (PR: #4027)
* Fix method resolution for inner interfaces. (PR: #4008)
* Fix crash on handling parameterized ProblemReferenceBinding. (PR: #3964)
* Fix crash on null type binding in nested type during search. (PR: #3961)
* Ensure that for init/update are registered in listeners. (PR: #3941)
* Fix snippet compilation bugs. (PR: #3897)
* Fix infinite loop on type parameter in qualified name. (PR: #3905)
* Fix snippet compilation when snippet follows a CtComment. (PR: #3888)
* Fix sniper printer failing to prepend whitespace to top-added CtModifiable. (PR: #3856)
* Fix a race condition in AbstractParallelProcessor. (PR: #3844)

# Documentation

* Clarify use of default/case labels in CtCase.setCaseExpression/s(). (PR: #4039)
* Add note in CONTRIBUTING.md about force-pushing. (PR: #4013)
* Improve Javadoc quality in Environment interface. (PR: #3968)
* Add missing Javadoc tags to documented public methods in CtScanner. (PR: #3934)
* Update list of contributors. (PR: #3900)
* Add website deployment documentation. (PR: #3889)
* Update README and docs related to spoon-smpl. (PR: #3869)
* Add API documentation to 3 undocumented public methods. (PR: #3854)

# Refactoring

* ReferenceBuilder
  * Refactor getting type refeference from TypeVariableBinding. (PR: #3991)
  * Extract small reference-building subroutines into helpers. (PR: #3981)
  * Remove dead code. (PR: #3976)
  * Extract parameterized type reference creation into helpers. (PR: #3966)
* Fix unchecked type conversions. (PR: #4095)
* Simplify set creation in CtReferenceImpl. (PR: #4097)
* Fix wonky indentation in CtModifierHandler.setModifiers. (PR: #4081)
* Simplify implementation of `getCaseExpression` and `setCaseExpression`. (PR: #4023)
* Remove unused local variable declarations. (PR: #4028)
* Revert incorrect move of test. (PR: #4029)
* Remove redundant if statement. (PR: #4011)
* Remove unnecessary unchecked cast in getParent(Class). (PR: #3973)
* Implement check for recursive type bound without using Object. (PR: #3865)
* Fix violation of Sonar rule 1444. (PR: #3853)
* Fix violation of Sonar rule 2142. (PR: #3930)
* Fix violation of Sonar rule 2097. (PR: #3972)
* Fix violations of Sonar rule 2057. (PR: #3866)
* Fix 1 violation of Sonar rule 2142. (PR: #3852)

# Performance

* Replace regex in identifier checks with loop. (PR: #4072)

# Tests

* Add tests for CtStatementList. (PR: #4089)
* Add test for CacheBasedConflictFinder. (PR: #4088)
* Add additional tests for CtCase.insertBegin/End. (PR: #4082)
* Add test for createReference. (PR: #4078)
* Add test for removeAnnotation method. (PR: #4056)
* Add tests for CtComment.equals. (PR: #4053)
* Migrate more tests to junit-5. (PR: #4045)
* Add tests for JavaOutputProcessor class. (PR: #4043)
* Make CtInheritanceScanner architecture test print correct class name. (PR: #4037)
* Add tests for the Check class. (PR: #4034)
* Add test reproducing issue #4021. (PR: #4030)
* Add additional tests for the Substitution class. (PR: #4018)
* Unite all tests for Substitution in one place. (PR: #4016)
* Add test for Substituion.insertAllSuperInterfaces. (PR: #4012)
* Add tests for the SpoonTreeBuilder class. (PR: #4006)
* Migrate support and testing tests to Junit5. (PR: #4009)
* Migrate all refactoring tests to Junit5. (PR: #4007)
* Add test for Substitution.insertAllConstructors. (PR: #4005)
* Add test for Substitution.insertAllNestedTypes. (PR: #3998)
* Add test for insertAllFields method. (PR: #3995)
* Add test for AbstractTemplate.isWellFormed(). (PR: #3990)
* Migrate all the template tests to Junit5. (PR: #3986)
* Improve tests for NameFilter class. (PR: #3975)
* Improve the test for SpoonTagger class. (PR: #3982)
* Migrate CtTypeReferenceTest to Junit5. (PR: #3969)
* Migrate ProcessingTest to Juit5. (PR: #3959)
* Migrate AstCheckerTest to Junit5. (PR: #3960)
* Migrate CtGenerationTest to junit5. (PR: #3958)
* Migrate CorrectIdentifierTest to JUnit5. (PR: #3956)
* Migrate FilterTest to Junit5. (PR: #3946)
* Migrate LogTest to JUnit5. (PR: #3939)
* Migrate TestSniperPrinter to JUnit5. (PR: #3921)

# Other

* Add tag pinning to GHA digest update. (PR: #4080)
* Migrate Javadoc regression script to Python. (PR: #4032)
* Try to list new errors in javadoc regression check. (PR: #4025)
* Format parent pom. (PR: #3994)
* Fix incorrect early exit in Javadoc quality script. (PR: #3932)
* Improve ci-checkstyle-javadoc.sh usability. (PR: #3924)
* Add CI check for method/constructor Javadoc quality. (PR: #3907)
* Add job for sorald-buildbreaker. (PR: #3912)
* Move Checkstyle config location into property. (PR: #3910)
* Fixed license URL in pom.xml. (PR: #3892)
* Bump license-maven-plugin to version 4.0. (PR: #3887)
* Disable Git's autocrlf feature to fix Windows build failures. (PR: #3881)
* Remove all traces of Travis CI. (PR: #3883)
* Update github action to use setup-java v2.0.0. (PR: #3874)
* Add script for SNAPSHOT version injection in CI. (PR: #3873)
* Remove snapshot repository to self. (PR: #3864)
* Remove outdated instances of maven.inria.fr. (PR: #3860)
* Use the kramdown Markdown processor for Spoon's website. (PR: #3859)
* Make URL to apidocs site relative. (PR: #3862)
* Add website CNAME. (PR: #3863)
* We're now 9.1.0-SNAPSHOT.

# Authors
| Name    | Nb Commit |
|---------|-----------|
| Simon Larsén | 47 |
| renovate[bot] | 35 |
| Rohitesh Kumar Jain | 33 |
| andrewbwogi | 8 |
| Martin Monperrus | 4 |
| Aman Sharma | 3 |
| Anton Lyxell | 3 |
| I-Al-Istannen | 3 |
| Hannes Greule | 3 |
| MartinWitt | 2 |
| Gabriel Chaperon Burgos | 1 |
| arno | 1 |
| André Silva | 1 |
| Mikael Forsberg | 1 |
| gtoison | 1 |
| jakobbraun | 1 |

### CODE REVIEW

**Comment by monperrus** [comment]
Will be done with Saturday's continuous delivery cron job.

**Comment by slarse** [comment]
erm, I might have forgotten to merge ...

**Comment by monperrus** [comment]
FYI, `9.1.0` is on Maven Central: https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/

**Comment by algomaster99** [comment]
@monperrus @slarse This release is not featured under the "Releases" heading on the homepage of the repository. Shouldn't we add it there?

**Comment by monperrus** [comment]
Yes, done! Thanks for the reminder. 

We should also update the [Continuous Delivery](https://github.com/SpoonLabs/spoon-deploy/blob/master/deploy-spoon-maven-central.sh) script to do so.

See https://github.com/INRIA/spoon/issues/3890

**Pull request merged**
