### PR TITLE
refactor: more idiomatic getAllJavaFiles

### PR DESCRIPTION
**Pull request by lyxell**
Simplify the implementation of `VirtualFolder::getAllJavaFiles` and `ZipFolder::getAllJavaFiles`.

Fixes two ([1](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&issues=AWhzp_GWOQZh-5uoMgNK&open=AWhzp_GWOQZh-5uoMgNK), [2](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&issues=AWhzp_GWOQZh-5uoMgNL&open=AWhzp_GWOQZh-5uoMgNL)) Sonar violations of rules S1117 and S125 respectively.

This patch was generated automatically using [Logifix](https://github.com/lyxell/logifix).

### CODE REVIEW

**Comment by monperrus** [comment]
Nice!

(1) is about `Rename "files" which hides the field declared at line 33.`

(2) is `This block of commented-out lines of code should be removed.`

Could you tell us more how Logifix comes up with these repairs, which don't directly target the error type?

Sidenote: this refactors uncovered, untested code, which should be avoided, would you add a test?

**Comment by lyxell** [comment]
Hi Martin,

> Could you tell us more how Logifix comes up with these repairs, which don't directly target the error type?

Certainly. To make Logifix produce more human-like patches for static analysis violations it has general strategies for code simplification. In this case the proposed changes are triggered by matching this loop:

```java
		for (SpoonFile f : getAllFiles()) {
			if (f.isJava()) {
				result.add(f);
			}
		}
```

The code is then simplified using six transformations

```diff
		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
+		result.addAll(getAllFiles.stream()
+			.filter(f -> f.isJava())
+			.collect(java.util.stream.Collectors.toList()));
		return result;
```

```diff
-		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
+		List<SpoonFile> result = new ArrayList<>(getAllFiles.stream()
+			.filter(f -> f.isJava())
+			.collect(java.util.stream.Collectors.toList())));
		return result;
```
```diff
-		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
-		return result;
+		return new ArrayList<>(getAllFiles.stream()
+			.filter(f -> f.isJava())
+			.collect(java.util.stream.Collectors.toList())));
```
```diff
-		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
-		return result;
+		return getAllFiles.stream()
+			.filter(f -> f.isJava())
+			.collect(java.util.stream.Collectors.toList()));
```
```diff
-		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
-		return result;
+		return getAllFiles.stream()
+			.filter(f -> f.isJava())
+			.collect(Collectors.toList()));
```
```diff
+import java.util.stream.Collectors;
...
-		List<SpoonFile> result = new ArrayList<>();
-		for (SpoonFile f : getAllFiles()) {
-			if (f.isJava()) {
-				result.add(f);
-			}
-		}
-		return result;
+		return getAllFiles.stream()
+			.filter(SpoonFile::IsJava)
+			.collect(Collectors.toList()));
```

When I created these transformations my intention was simply to make Logifix produce better code when fixing other violations, i.e. to clean up its own output, I did not intend to use these transformations to directly fix static analysis violations. However, I've discovered that there are static analysis violations that are very hard to fix with a "directed" approach, but where general strategies for code simplification can be effective.

Indeed, in the Logifix UI this proposed change is listed as "Simplify code using streams" and not as "Remove local variable that shadows class field". However, it would be totally possible to list it as the second.

> Sidenote: this refactors uncovered, untested code, which should be avoided, would you add a test?

Sure, can I open a separate issue or PR for this?

**Comment by monperrus** [comment]
Thanks for the explanation.

>  However, I've discovered that there are static analysis violations that are very hard to fix with a "directed" approach, but where general strategies for code simplification can be effective.

That's an interesting statement. I've never seen a paper about generic "code simplification" or "code improvement". The closest thing is obviously refactorings, but few of them would remove smells and warnings.

**Comment by monperrus** [comment]
> Sure, can I open a separate issue or PR for this?

Up to you, either here or in a PR we would merge first, before this one.

**Comment by monperrus** [comment]
ping @lyxell

**Pull request merged**
