### PR TITLE
fixes bug in printing of new Array with comment #911

### PR DESCRIPTION
**Pull request by pvojtechovsky**
In case of comment the last character is the last character of the
comment and not the ",".

### CODE REVIEW

**Comment by monperrus** [comment]
Hi Pavel,
Thanks for the contribution. Would you add a test case to avoid a regression in the future?
Thanks, --Martin

**Comment by pvojtechovsky** [comment]
Hi Martin,
The test was added and it comply with formatting rules now too. 
Best regards,
Pavel

**Comment by monperrus** [comment]
now it breaks a test, could you make it pass? thanks.

**Comment by pvojtechovsky** [comment]
I modified the fix by way it keeps formatting of annotations too.
Now all seems to be ok. I just actually do not know how to squash all commits into one, without creating new branch and loosing this PR.... but I will hopefully found it soon...

**Comment by monperrus** [comment]
excellent, thanks. We can squash at merge time.

**Pull request merged**
