### PR TITLE
chore(release): Scripts to publish automatically a release.

### PR DESCRIPTION
**Pull request by GerardPaligot**

### CODE REVIEW

**Comment by monperrus** [comment]
put them in chore instead of doc?

**Comment by GerardPaligot** [comment]
The folder named `doc/_release` seems more appropriate.

**Comment by GerardPaligot** [comment]
@monperrus Why spoon-bot have posted something here? Do you change something on Jenkins?

**Comment by monperrus** [comment]
> The folder named doc/_release seems more appropriate.

your PR is name "chore_release" :-)

**Pull request merged**
