### PR TITLE
fix(ContextBuilder): catch PositionBuilder exception and log them instead of crashing

### PR DESCRIPTION
**Pull request by nharrand**
fix#2888

### CODE REVIEW

**Comment by monperrus** [comment]
do we want to accept incorrect code?

the other solution would be to crash with an exception with a clear message.

WDYT?

**Comment by nharrand** [comment]
I agree that we do not necessarily want to accept silently incorrect code. 
But I don't think the place to catch it is in the PositionBuilder anyway. I would argue that the position builder should be best effort, and if it contains a bug it should not break the model build.

**Comment by monperrus** [comment]
I agree.

**Comment by nharrand** [comment]
Ok, after some thougths, I think that yes we do want to accept incorrect code inthis case.

In JDTBatchCompiler:168:

```java
if (jdtCompiler.getEnvironment().getNoClasspath()) {
	// in no classpath, we should proceed on error,
	// as we will encounter some
	errorHandlingPolicy = new IErrorHandlingPolicy() {
		@Override
		public boolean proceedOnErrors() {
			return true;
		}
	[...]
	};
}
```

In no classpath mode, we specifically say that the compiler should proceed on errors. otherwise it would fail on the first import outside of the project. I am not sure if there is a way to cherry pick errors that we want to tolerates and errors that we don't.

**Comment by monperrus** [comment]
Thanks

**Pull request merged**
