### PR TITLE
refactor: fix code inspection: Java7 - Explicit type can be replaced with diamond

### PR DESCRIPTION
**Pull request by zielint0**
This PR fixes defects detected by both:
- IDEA code inspection (explicit type can be replaced with diamond)
- SonarQube (Replace the type specification in this constructor call with the diamond operator ("<>").

On purpose I fixed only part of violations that have form:
```Set<X> x = new HashSet<X>(); -> Set<X> x = new HashSet<>();```

To avoid loss of readability, I did NOT fixed form:
```
Set<X> x;
...
...
...
x = new HashSet<X>();
```

I am ready to merge.

### CODE REVIEW

**Comment by zielint0** [comment]
I need your guidance. Why git all the time pushes old commits? First 4 commits on list.

```
@zielint0 refactor: move Main to testclasses - second try 47f60e7
@zielint0 Revert "refactor: move Main to testclasses - second try"  … bd7ef7a
@zielint0 Merge branch 'master' of https://github.com/INRIA/spoon 41fd248
@zielint0 Merge branch 'master' of https://github.com/INRIA/spoon d7220ba

@zielint0 refactor: use modern Java 7 syntax - diamond <> a04bea8
```

How can I prevent git pushing older commits?
I would like to push only 1 commit:
```@zielint0 refactor: use modern Java 7 syntax - diamond <> a04bea8```

**Comment by pvojtechovsky** [comment]
> How can I prevent git pushing older commits?

1) create new branch on master
2) cherry pick the new commit to that branch
3) push new branch

**Comment by zielint0** [comment]
@pvojtechovsky 
Thank you for tip. But it did not help me. Tried also reset --hard. Maybe something similar to it?

I tried 3 ways (including cherry-pick - the last branch) but git somehow remembers old commits. No matter how I create a branch, the result is the same. 
- https://github.com/zielint0/spoon/tree/refactor-code-inspection-code-style-issues-c-style-array-declaration
- https://github.com/zielint0/spoon/tree/refactor-c-style-array
- https://github.com/zielint0/spoon/tree/refactor-c-style-array-cherry-pick

Sorry for offtopic, but I was unable to Google nothing helpful :-(

**Comment by pvojtechovsky** [comment]
@zielint0 I guess the problem is in this step 
> 1) create new branch on master

because you are creating the new branch on the commit which is merge of Spoon master and your other branch. You have to start from pure Spoon master

**Comment by zielint0** [comment]
@pvojtechovsky 
You are right! I have an unwanted merge. gitk shown me the truth!
I checked a commit from Spoon master and then branched on it. Now I pushed this branch and it [does not have those old commits!](https://github.com/INRIA/spoon/pull/2230/commits) :)
Thank you so much! :)

**Pull request merged**
