### PR TITLE
test: reproduce bug for issue #3052

### PR DESCRIPTION
**Pull request by aveuiller**

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks @aveuiller a failing test case is super useful.

@Egor18 would you have a look at this one? that would be great.

**Comment by Egor18** [comment]
@monperrus, OK, I'll take a look.

**Comment by monperrus** [comment]
great, thanks.

**Comment by Egor18** [comment]
I located a problem, working on the PR.

**Comment by monperrus** [comment]
Closed per #3056

**Pull request closed without merging**
