### PR TITLE
fix(ImportCleaner): resolve imports of parent types

### PR DESCRIPTION
**Pull request by algomaster99**
Reference: https://github.com/SpoonLabs/sorald/issues/598

Type `B` in `A.B x = new A.B()` was not being resolved to `import somePackage.A` even though this import statement was present in the compilation unit.

I apologise for the bad test case. I wasn't able to reproduce the bug in a smaller test file. The reason was that whenever it used to visit `B` in `A.B x`, the visit was ended due to this [condition](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/AstParentConsistencyChecker.java#L21). However, this line didn't interfere with the original test resource which brought about this bug.

### CODE REVIEW

**Comment by algomaster99** [comment]
@slarse @MartinWitt @I-Al-Istannen can you please look at it?

**Comment by I-Al-Istannen** [comment]
I think this breaks the following:
```java
import java.util.Map.Entry;

class Hello {
	public void hey() {
		Entry<String, String> f = null;
	}
}

```

**Comment by algomaster99** [comment]
Thanks for pointing it out. I am looking into it.

**Comment by algomaster99** [comment]
> I think this breaks the following class (import is removed and Entry fully qualified):

You were right about it. I also added a condition which would check if the subtype is present. However, the reference to subtype here is `java.util.Map.Entry<String, String>` while the reference to import is `java.util.Map.Entry` (without type arguments). Thus, I skipped checking for `TYPE_ARGUMENT` while I compute their equality. Maybe we can put that method in `EqualVisitor` which allows you to skip for certain roles while getting the equality. What do you think?

**Comment by monperrus** [comment]
thanks @algomaster99

**Comment by slarse** [comment]
> Maybe we can put that method in `EqualVisitor` which allows you to skip for certain roles while getting the equality. What do you think?

@algomaster99 I don't think that's a good idea. What you're suggesting is some form of partial comparison, i.e. not equality.

**Comment by algomaster99** [comment]
I thought it would be beneficial in comparing references. For example, in this case, I needed to compare two references - reference to an import and a field's type. I just wanted to skip comparison for `TYPE_ARGUMENT` role because type argument cannot be there in import references.

**Comment by slarse** [comment]
I get the use case, but that's not equality, it's a different kind of comparison. So I don't think it's appropriate for the `EqualVisitor`.

Put simply, a reference with type arguments is not equal to a reference without type arguments, even if the referenced type is the same.

**Pull request merged**
