### PR TITLE
review: fix additional snippet bugs

### PR DESCRIPTION
**Pull request by andrewbwogi**

### CODE REVIEW

**Comment by monperrus** [comment]
Hi @andrewbwogi 

Moving the exception in another package is a breaking change. Why would we need to do that?

Thanks,

**Comment by andrewbwogi** [comment]
@monperrus, `SnippetCompilationError` just went along with the package change of `SnippetCompilationHelper`, I've placed it back again. Is moving `SnippetCompilationHelper` also a breaking change that is not worth the trouble? It was moved to use package-private methods in `PositionBuilder`.

**Comment by monperrus** [comment]
> Is moving `SnippetCompilationHelper` also a breaking change that is not worth the trouble?

Yes it would be breaking if there is at least one public method in the class.

> It was moved to use package-private methods in `PositionBuilder`.

One solution is to make them public instead.

**Comment by andrewbwogi** [comment]
I somehow did not see that this branch was already merged (#3897). I'm fine with it so I'm closing this one.

**Pull request closed without merging**
