### PR TITLE
Release Spoon 7.4.0

### PR DESCRIPTION
**Pull request by monperrus**
We have already 100+ Maven artifacts depending on spoon-7.4.0-beta, it's time to release.

With our new release pipeline, a release is meant to be as simple as this single pull-request.

The final release of Spoon 7.4.0 will be the commit just before that one at the time it's merged.

### CODE REVIEW

**Comment by surli** [comment]
> The final release of Spoon 7.4.0 will be the commit just before that one at the time it's merged.

which means there won't be any artifact spoon-core 7.4.0 in Maven repo? Only 7.4.0-beta?

**Comment by monperrus** [comment]
Yes, there will be 7.4.0 on Maven Central, corresponding to eaf0c42276b35f00c65bdd61cf99a2f2e56f6b8f

**Comment by surli** [comment]
> Yes, there will be 7.4.0 on Maven Central, corresponding to eaf0c42 

ok then, it's a pity that we don't have much control on when this release will be available. For example, here I spotted this PR and was about to upgrade Spoon on XWiki, but I can't since it's not released yet. So basically I have to periodically check maven central for doing this upgrade, I don't have a clear info anymore. 

Unless we also automated the release on Github during the job and then I should have a notification.

**Comment by monperrus** [comment]
> we also automated the release on Github during the job

Yes, this is the goal.

**Comment by monperrus** [comment]
One question, with a simple tag, it already appears on https://github.com/INRIA/spoon/releases

Does you get a notification?

**Comment by nharrand** [comment]
I can see release 7.4.0, but weirdly the latest release is still 7.3.0.

**Comment by surli** [comment]
> I can see release 7.4.0, but weirdly the latest release is still 7.3.0 (on github).

From what I remember pushing the tag is not enough on Github: it only provides a draft release  that you need to manually publish. For us it also means to add the release notes.

**Comment by surli** [comment]
FTR I published the release on GH release: https://github.com/INRIA/spoon/releases/tag/spoon-core-7.4.0

**Comment by monperrus** [comment]
Thanks!

**Pull request merged**
