### PR TITLE
feature: Add support for Java 11 local variable syntax

### LINKED ISSUE #2728: feat: Support Java 11 new features
Here's the list of new features in Java 11: https://openjdk.java.net/projects/jdk/11/

At first sight, I think we need to implement:
  * https://openjdk.java.net/jeps/323

### PR DESCRIPTION
**Pull request by Egor18**
Fix #2728.
This PR adds support for the following syntax (available since Java 11):
`(var x, var y) -> x + y;`

As far as I know, this is the only new _language_ feature in Java 11, so basically it allows us to support Java 11.

P.S. Had to update eclipse jdt a bit.

### CODE REVIEW

**Comment by surli** [comment]
LGTM

**Comment by monperrus** [comment]
Really cool, thanks Egor!

Could you modify the documentation at the appropriate place(s) to say that Java 11 is supported?

**Comment by Egor18** [comment]
I updated README.md. You might also want to edit github repository description.

**Comment by monperrus** [comment]
Thanks a lot, that's a milestone PR :-)

**Pull request merged**
