### PR TITLE
refactor: use isEmpty to make intention clear

### PR DESCRIPTION
**Pull request by zielint0**

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
I personally prefer positive `size() > 0`. so it is ok for me like it is now. If others thinks that `!isEmpty()` is better, them I can live with that too :-)

**Comment by zielint0** [comment]
I have fixed previous defects like this.
This PR fixes some new ones.

**Comment by monperrus** [comment]
`size() > 0` is slightly more explicit (you don't have to know the meaning and contracts of isEmpty).

If Pavel prefers it, let's keep it.

Thanks @zielint0 for the proposal.

**Comment by zielint0** [comment]
@pvojtechovsky 
@monperrus 
@surli 

I fixed a lot of them in:
https://github.com/INRIA/spoon/pull/2362
https://github.com/INRIA/spoon/pull/2348
https://github.com/INRIA/spoon/pull/2328
https://github.com/INRIA/spoon/pull/2282

These are the last ones to fix.
It was merged by @surli so I think that this is useful.

Please consider reopening this pull request.

**Comment by zielint0** [comment]
@monperrus 
To make reviewers life easy, I created a list of merged PRs.
If you want to see rationale or fact if something similar was merged or not, please take a look:
https://github.com/INRIA/spoon/issues/2105

**Comment by pvojtechovsky** [comment]
I checked #2362 #2348 #2328 #2282 and I agree that it is more readable only in this case:
```
		if (splitRange.length == 1 || splitRange[1].length() == 0) {
change to
		if (splitRange.length == 1 || splitRange[1].isEmpty()) {
```
because it is positive expression: "If empty then do something", but in all other cases I need more time to understand new expressions, because they often contain negative condition. E.g.
`if (!clone.getBody().getStatements().isEmpty()) {` is not better then before

and the worst case is:
```
		assertTrue(factory.Type().getAll().size() > 0);
changed to
 		assertFalse(factory.Type().getAll().isEmpty());
```
Before I read it like "Type getAll contains something". Now I have to read: "It is not true that type get all is empty". My mind needs three time more effort to understand that ... 
So I would not merge these other PRs.
Thomas I very appreciate your cleaning effort, but in this particular case, I would not agree with these changes.

**Comment by monperrus** [comment]
reopened per @zielint0 's request in #2475

**Comment by zielint0** [comment]
@monperrus 
Mercii!

@pvojtechovsky 
Thank you for this explanation. I will consider reworking it :-)

**Pull request closed without merging**
